### ISSUE TITLE
Helm Lint Error with | default {{ .Release.Namespace }}

### ISSUE THREAD

**Issue by alanmeadows** [kubernetes/helm#1761] opened 2016-12-23 23:35 UTC
Running helm 2.1.0, with the following template:

```
monitors: {{ .Values.storageclass.monitors | default "ceph.{{ .Release.Namespace }}:6789" }}
adminSecretNamespace: {{ .Values.storageclass.admin_secret_namespace | default "{{ .Release.Namespace }}" }}
```

We receive the following lint error:

```
$ helm lint ceph 
==> Linting ceph 
[ERROR] templates/storage.yaml: unable to parse YAML 
	error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Release.Namespace":interface {}(nil)}
```

in this context,  ```.Values.storageclass.monitors``` and  ```.Values.storageclass.admin_secret_namespace```  are set to literal null values in values.yaml, activating the default.

The linter is called out because a ```helm install --dry-run --debug``` interpolates the template as expected.

**Comment by technosophos** [comment] 2016-12-23 23:38
I believe this is a case where linter just fell a bit behind. Dropping this into 2.1.4

**Comment by technosophos** [comment] 2017-01-05 23:20
I'm still hunting down the cause of this bug, but I can tell you that the problem can be worked around by adding `| squote` to the end of the line. When the YAML interpreter hits an unescaped `{{`, it reads it as a JSON object.

Still trying to figure out what the key difference is between `helm install` and `helm lint` that only results in an error during lint.

**Comment by technosophos** [comment] 2017-01-05 23:36
Alright, at the risk of beating a dead horse, I have tracked this down. And the linter is right: The YAML produced by the above code snippet is in fact invalid according to the YAML spec.

It happens to work only in cases where the output of the template run is not passed into a YAML parser (or is re-interpolated). The technically correct solution is to `squote` the string, at which point the YAML parser will get this instead:

```
somekey: '{{ .Release.Namespace }}`
```

And if that goes through the template processor a second time, which I am assuming is your goal there, the result should still be correct.

So it turns out I was completely wrong. My initial assumption was that the linter did not correctly pass `.Release.Namespace` down the line, which caused a lookup error. The namespace is correctly set.

Sorry for taking so long. Let me know if the squote solution isn't a workable route for you.

**Comment by alanmeadows** [comment] 2017-01-06 16:05
Matt,

That makes perfect sense, and it does work for us.  I am bummed I didn't put two and two together and see that initially before having you spend time on the issue.  Appreciate the follow-up.

We can close this issue. Something that might make sense to turn this into a positive is a documentation augment adding an example highlighting this leveraging a variable with a default pipe to shield others.  I can work on a PR shortly.

**Comment by technosophos** [comment] 2017-01-11 18:26
Alright. I'll close this issue, and if you do have a PR for the documentation, ping me when it's ready and I'll merge it.

**Closed by technosophos** 2017-01-11 18:26 UTC

**Comment by Tohaker** [comment] 2019-06-03 09:27
We are still facing this problem, and the solution provided doesn't work. 
```
adminUser: {{ .Values.AdminUser }}
adminPassword: {{ .Values.AdminPass }}
```
Gives the error `Error: failed to parse modules/aks/jenkins/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.AdminUser":interface {}(nil)}`

With single and double quotes the YAML is parsed, but the literal values within them are created as the adminuser and password. 

Any idea how to get passed this?

**Comment by Sahilbhawke** [comment] 2021-11-12 05:55
> We are still facing this problem, and the solution provided doesn't work.
> 
> ```
> adminUser: {{ .Values.AdminUser }}
> adminPassword: {{ .Values.AdminPass }}
> ```
> 
> Gives the error `Error: failed to parse modules/aks/jenkins/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.AdminUser":interface {}(nil)}`
> 
> With single and double quotes the YAML is parsed, but the literal values within them are created as the adminuser and password.
> 
> Any idea how to get passed this?

hii did you got a solution for this i am facing the same

**Comment by vikomte** [comment] 2021-12-10 11:58
> > We are still facing this problem, and the solution provided doesn't work.
> > ```
> > adminUser: {{ .Values.AdminUser }}
> > adminPassword: {{ .Values.AdminPass }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Gives the error `Error: failed to parse modules/aks/jenkins/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.AdminUser":interface {}(nil)}`
> > With single and double quotes the YAML is parsed, but the literal values within them are created as the adminuser and password.
> > Any idea how to get passed this?
> 
> hii did you got a solution for this i am facing the same

Did you ?

**Comment by vvs82** [comment] 2023-06-27 12:44
> > > We are still facing this problem, and the solution provided doesn't work.
> > > ```
> > > adminUser: {{ .Values.AdminUser }}
> > > adminPassword: {{ .Values.AdminPass }}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Gives the error `Error: failed to parse modules/aks/jenkins/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.AdminUser":interface {}(nil)}`
> > > With single and double quotes the YAML is parsed, but the literal values within them are created as the adminuser and password.
> > > Any idea how to get passed this?
> > 
> > 
> > hii did you got a solution for this i am facing the same
> 
> Did you ?

Any update on this issue? Still has the same status for me.

**Comment by Tohaker** [comment] 2023-06-27 14:35
Sorry, I haven't worked on this project since shortly after posting the issue and no longer work at the company it was raised at... Hope you folks get a solution!
