### ISSUE TITLE
helm lint: Check for key validity

### ISSUE THREAD

**Issue by mcandre** [kubernetes/helm#2195] opened 2017-03-28 16:05 UTC
Could the `helm lint` command ensure key validity against the Kubernetes schemas, in addition to generic YAML syntax correctness?

**Comment by thomastaylor312** [comment] 2017-03-30 02:30
@mcandre This can be done with `--dry-run` on an `install` or `upgrade`. The only thing that won't catch is whether or not the API will accept those manifests (even if they are valid).

**Comment by technosophos** [comment] 2017-04-12 23:53
`helm lint` is supposed to be an "offline operation", which is why it does not contact the k8s API server to find out what is supported.

At some point we may have to re-visit the rationale for making `helm lint` offline. There are a number of things that it cannot check because of this limitation.

**Comment by bacongobbler** [comment] 2017-10-31 21:36
closing as a duplicate of #2575.

**Closed by bacongobbler** 2017-10-31 21:36 UTC
Labels: question/support
