### ISSUE TITLE
Upgrade fails with timeout (after upgrading to 2.4.1), then gets stuck

### ISSUE THREAD

**Issue by atombender** [kubernetes/helm#2412] opened 2017-05-07 20:43 UTC
Doing `helm install --namespace=staging --upgrade --timeout 300 --wait picaxe-staging .` now fails with timeout after upgrading from 2.3.0 to 2.4.1. The resources are updated, pods start just fine, etc., but then Helm times out.

If I try to do another upgrade, nothing even happens. It logs "Doing get for ..." and then nothing more. No resources are applied in Kubernetes. The client is stuck waiting forever. The server does not time out after 5 minutes. In other words, the first upgrade failed, subsequent upgrades don't even fail, they're just stuck.

Killing Tiller makes it work again, but it keeps timing out consistently.

Here's the Tiller log:

```
2017/05/07 20:14:27 storage.go:139: Getting release history for 'picaxe-staging'
2017/05/07 20:14:27 release_server.go:954: Executing pre-upgrade hooks for picaxe-staging
2017/05/07 20:14:27 release_server.go:983: Hooks complete for pre-upgrade picaxe-staging
2017/05/07 20:14:27 client.go:386: generating strategic merge patch for *unstructured.Unstructured
2017/05/07 20:14:27 client.go:386: generating strategic merge patch for *unstructured.Unstructured
2017/05/07 20:14:27 wait.go:47: beginning wait for resources with timeout of 5m0s
2017/05/07 20:19:27 release_server.go:329: warning: Upgrade "picaxe-staging" failed: timed out waiting for the condition
2017/05/07 20:19:27 storage.go:59: Updating "picaxe-staging" (v60) in storage
2017/05/07 20:19:27 storage.go:51: Create release "picaxe-staging" (v61) in storage
```

Status after:

```
$ helm status picaxe-staging
LAST DEPLOYED: Sun May  7 16:14:27 2017
NAMESPACE: staging
STATUS: FAILED
```

No information about why it's failing.

---

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
```

**Comment by hvalle** [comment] 2017-05-09 11:16
My temporary solution is to remove the `--wait` parameter.

**Comment by thomastaylor312** [comment] 2017-05-09 23:49
It is marked as failed because all resources didn't get to a ready state (e.g. the `--wait` flag) before the timeout.

**Comment by atombender** [comment] 2017-05-09 23:55
According to Kubernetes, they did get to the ready state. Rolled back to 2.3.1 and it works fine again, no other changes.

**Comment by thomastaylor312** [comment] 2017-05-10 00:09
@atombender Any way you can share the chart you are working with? I want to see if it is an edge case happening in the code

**Comment by simonswine** [comment] 2017-05-10 07:43
I also see this problem happening after upgrading to 2.4.1.

I wasn't able to reproduce with a default (`helm create`) chart. Will continue to try. But it worked fine with 2.3.1

Tiller:

```
2017/05/10 07:34:39 storage.go:139: Getting release history for 'website-staging'
2017/05/10 07:34:39 storage.go:74: Listing all releases in storage
2017/05/10 07:34:39 storage.go:139: Getting release history for 'website-staging'
2017/05/10 07:34:39 release_server.go:954: Executing pre-upgrade hooks for website-staging
2017/05/10 07:34:39 release_server.go:983: Hooks complete for pre-upgrade website-staging
2017/05/10 07:34:40 client.go:398: Looks like there are no changes for Secret "website-staging-website-htpasswd"
2017/05/10 07:34:40 client.go:398: Looks like there are no changes for Service "website-staging-website"
2017/05/10 07:34:40 client.go:398: Looks like there are no changes for Deployment "website-staging-website"
2017/05/10 07:34:40 client.go:398: Looks like there are no changes for Ingress "website-staging-website"
2017/05/10 07:34:40 wait.go:47: beginning wait for resources with timeout of 5m0s
2017/05/10 07:39:40 release_server.go:329: warning: Upgrade "website-staging" failed: timed out waiting for the condition
2017/05/10 07:39:40 storage.go:59: Updating "website-staging" (v22) in storage
2017/05/10 07:39:40 storage.go:51: Create release "website-staging" (v23) in storage

```

Helm:

```
helm upgrade website-staging contrib/charts/website --install --namespace website-staging \
	--set 'image.tag=master-1130' \
	--set 'ingressHostnames={website-staging.example.net}' \
	--set 'ingressTLS=true' \
	--set 'ingressHtpasswd=xx' \
	--set 'replicaCount=1' \
	--values .values.staging.yaml \
	--wait
Error: UPGRADE FAILED: timed out waiting for the condition
```

**Comment by unguiculus** [comment] 2017-05-10 16:35
I updated to 2.4.1 today and kept getting the same problem. I had to repeatedly kill Tiller to make it work again. Seems to be related to `--wait`.

**Comment by eduardobaitello** [comment] 2017-05-10 20:56
@atombender see this issue that I just opened, please #2426 

If you have Deployments being upgraded in your release, check if there is any old ReplicaSets, and try to manually delete then while the Tiller is "waiting for resources". Maybe we are with the same issue...

**Comment by eduardobaitello** [comment] 2017-05-18 12:11
@atombender This commit was released yesterday in `v2.4.2` patch.
This solved the `--wait`  problem in for me.
Commit: https://github.com/kubernetes/helm/commit/79c492b6aba9f018608d635530f00a17bf3539b8

**Comment by gullitmiranda** [comment] 2017-06-04 17:54
I have had the same problem when the number of reviews are great:

```sh
$ helm list | grep agendor-infra
agendor-infra            	195     	Sun Jun  4 14:42:46 2017	FAILED  	agendor-infra-0.9.0     	default

$ kubectl logs -n kube-system -f tiller-deploy-1651596238-gnxn7
2017/06/04 17:47:22 storage.go:139: Getting release history for 'agendor-infra'
2017/06/04 17:47:56 release_server.go:329: warning: Upgrade "agendor-infra" failed: timed out waiting for the condition
2017/06/04 17:47:56 storage.go:59: Updating "agendor-infra" (v194) in storage
2017/06/04 17:47:57 storage.go:51: Create release "agendor-infra" (v195) in storage
2017/06/04 17:49:35 storage.go:139: Getting release history for 'agendor-infra'
```

**Comment by whereisaaron** [comment] 2017-06-12 18:34
After upgrading from 2.3 to 2.4.2 yesterday, all my deployments started failing with timeouts. Looks like it is the `--wait` failing. Is there something I need to do before the 2.4.2 patch will work?

```
2017/06/12 18:07:16 wait.go:47: beginning wait for resources with timeout of 10m0s
2017/06/12 18:17:16 release_server.go:329: warning: Upgrade "my-test" failed: timed out waiting for the condition
```

```
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment] 2017-10-31 23:20
looks like this has been fixed in recent releases. Closing this, but please re-open if this isn't true on helm 2.7 with k8s 1.8 or later.

**Closed by bacongobbler** 2017-10-31 23:20 UTC
Labels: question/support
