### ISSUE TITLE
Unreadable Docs - Using Helm Section

### ISSUE THREAD

**Issue by sebasalvarado** [kubernetes/helm#4297] opened 2018-07-03 22:39 UTC
## Issue:

In the main docs, the section `Using Helm` has styles that are completely broken. The text is shifted to the right and it gets hidden under the left hand side panel.

Here are the pictures of how it looks with different browsers

Hardware: 
- macOS High Sierra Version 10.13.4

Google Chrome Version 67.0.3396.99 

<img width="1680" alt="screen shot 2018-07-03 at 6 35 21 pm" src="https://user-images.githubusercontent.com/15041987/42247776-3e2127c0-7ef0-11e8-8c8a-887de2b3ec5d.png">

Safari Version 11.1
<img width="1321" alt="screen shot 2018-07-03 at 6 35 47 pm" src="https://user-images.githubusercontent.com/15041987/42247791-4c061666-7ef0-11e8-8e5f-311e69de56a1.png">

Firefox Quantum 61.0
<img width="1680" alt="screen shot 2018-07-03 at 6 35 58 pm" src="https://user-images.githubusercontent.com/15041987/42247809-61b2f18c-7ef0-11e8-9853-85ab7db14346.png">

**Comment by bacongobbler** [comment] 2018-07-04 02:41
Oh interesting! I managed to hit this after clicking a few links on the site too.

cc @flynnduism, any insight into this particular issue?

**Comment by flynnduism** [comment] 2018-07-04 07:16
I've rebuilt the docs, the layout is corrected now: [https://docs.helm.sh/using_helm/](https://docs.helm.sh/using_helm/)

This layout bug is a regression, I'm investigating it to determine why the previous build went awry build.

**Comment by sebasalvarado** [comment] 2018-07-04 20:54
Thanks! @bacongobbler @flynnduism should I close this issue?

**Comment by maetthu** [comment] 2018-07-10 14:36
@sebasalvarado Looks like it's only partly fixed. Most anchors in the menu don't work and if you scroll down to the bottom, the layout is still screwed up. Looks like a part of the page is appended again to the end of the document.

**Comment by flynnduism** [comment] 2018-07-10 18:04
@maetthu @sebasalvarado I've fixed and pushed a fix to the site: [https://docs.helm.sh/using_helm/](https://docs.helm.sh/using_helm/) 

The glitch arising from a fresh site build happened again this morning; I'm working on the CI script today to resolve this and to stop it occurring. Apologies for the inconvenience.

**Closed** 2018-07-10 18:08 UTC
Labels: docs

**Comment by dave08** [comment] 2018-07-30 10:47
The sidebar doesn't scroll (especially command reference). I'm on Linux Mint, with Chrome (also tried Opera).

**Comment by sebasalvarado** [comment] 2018-08-02 14:59
Same ^^ the sidebar does not scroll, any ideas? @bacongobbler

**Comment by bacongobbler** [comment] 2018-08-02 15:10
I've opened https://github.com/helm/helm-www/issues/130. Please feel free to follow up there/contribute fixes!

**Comment by sebasalvarado** [comment] 2018-08-02 15:18
Thanks!
