### ISSUE TITLE
Set namespace for subchart?

### ISSUE THREAD

**Issue by WillemMali** [kubernetes/helm#2813] opened 2017-08-15 12:43 UTC
What I want to do:

* Deploy Jenkins in a separate namespace, based off the default chart

How I do it:

* Fork the default chart
    * but keep the repo structure so it's easy to keep up-to-date with the `stable` version
* Add namespace parameters to the fork
* Add the fork as a submodule to the repo containing my Helm deployment charts (by which I mean, charts that manage a deployment like `dev`, `staging` or `prod`)
* Make symlinks to the right directory
* Add `file://` references in my Chart.yaml
* Add Makefile targets to manage the symlinks and submodules

My ideal workflow:

* Use Helm to set the namespace of 3rd-party charts

Am I doing it wrong or is this the state of this particular area of Helm? Would a way to configure subchart namespaces be a useful feature to have?

Edit: from prose to bullet points

**Comment by jascott1** [comment] 2017-08-16 23:53
@WillemMali  From a Helm point of view a release (parent chart and its sub-charts) goes into a single namespace. Im not sure what the behavior would be if you sub divide it into multiple namespaces but its not designed around doing that as far as I understand it.

**Comment by jascott1** [comment] 2017-08-16 23:59
More info: https://github.com/kubernetes/helm/issues/980

**Comment by bacongobbler** [comment] 2017-08-17 04:46
I'm not aware of any tools that solve your use case. Sorry!

I am going to close this issue as this is intentional by design, but please feel free to re-open if necessary. Thanks!

**Closed by bacongobbler** 2017-08-17 04:46 UTC
Labels: question/support
