### ISSUE TITLE
Request: Have a DEPLOYING status

### ISSUE THREAD

**Issue by nimeshksingh** [kubernetes/helm#1773] opened 2016-12-30 20:04 UTC
It looks like a helm release is DEPLOYED as soon as k8s accepts all of the commands, but there are kubernetes objects that aren't necessarily fully created / deployed at that time, like deployments and ingresses.  It would be great to keep the helm release status as DEPLOYING until all the objects are actually fully created and deployed.

This may tie into something like https://github.com/kubernetes/helm/issues/1498, but at least for deployments it could wait until "kubectl rollout status deployment" returns success.

**Comment by technosophos** [comment] 2017-01-03 19:59
This is a good idea. The rules for what constitutes "DEPLOYED" probably need to be described, though. Does every resource type need its own definition of what it means to be "DEPLOYED" instead of just "DEPLOYING"?

**Comment by nimeshksingh** [comment] 2017-01-04 04:26
Currently the ```kubectl rollout``` subcommands only support deployments, but they way the usage text is written it looks like it's intended to eventually support more resources.  I'd say just piggybacking on whatever information is available via kubectl rollout would be a reasonable way to go.

**Comment by technosophos** [comment] 2017-01-26 23:09
Today we merged support for the `--wait` flag, which is probably as close as we will get in the near future.

Using `helm install --wait` will now keep Helm running until the entire release has been deployed.

**Comment by georgecrawford** [comment] 2017-03-03 00:08
I'm finding that with 2.2.0, after a `helm upgrade --wait` I still need to run `kubectl rollout status` to correctly wait until all old pods are torn down and the rollout is complete. Is there a chance that `helm upgrade` could wait for this entire process (ideally showing the progress of the rollout)?

**Comment by bacongobbler** [comment] 2017-03-03 05:02
@georgecrawford there's a known issue that helm install --wait doesn't work as intended on v2.2.0. See https://github.com/kubernetes/helm/pull/2016

**Comment by georgecrawford** [comment] 2017-03-03 09:14
Aah, thanks @bacongobbler

**Comment by bacongobbler** [comment] 2017-08-11 22:15
Is there anything actionable in this ticket, or shall we say this is closed with the introduction of the `--wait` flag? I haven't seen any demand for this feature ever since we introduced `--wait`.

**Closed** 2017-10-31 17:46 UTC
Labels: feature
