### ISSUE TITLE
Helm init on docker edge: cannot parse dnsName

### ISSUE THREAD

**Issue by koalalorenzo** [kubernetes/helm#3894] opened 2018-04-14 05:24 UTC
Every time I am running `helm init` on docker for mac (docker edge) I get the following output:
```
$HELM_HOME has been configured at /Users/koalalorenzo/.helm.
Error: error installing: Post https://localhost:6443/apis/extensions/v1beta1/namespaces/kube-system/deployments: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc."
```
but all the other cmds for k8s are working fine. Any suggestion? I know that I am using a beta feature, but it could be useful to investigate why this broke. Tiller doesn't get installed.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
The command hangs forever

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
docker-for-desktop (`Version 18.04.0-ce-mac62 (23965) - channel: edge - e0a85f64c1`)

**Comment by bacongobbler** [comment] 2018-04-14 05:25
closing as a duplicate of https://github.com/kubernetes/helm/issues/3873.

**Closed by bacongobbler** 2018-04-14 05:25 UTC
