### ISSUE TITLE
helm fetch <repo-name>/<chart-name> --untar doesn't work. 

### ISSUE THREAD

**Issue by jbowen93** [kubernetes/helm#810] opened 2016-06-10 18:55 UTC
`helm fetch <repo-name>/<chart-name> --untar` doesn't work. It returns the following error `Error: open <chart-name>/Chart.yaml: no such file or directory`. If I do a `helm fetch` and untar the dir myself and then rerun `helm fetch --untar` the command works. This leads me to believe that the `--untar` option is looking for the `Chart.yaml` locally before it is downloaded.

**Comment by technosophos** [comment] 2016-06-13 17:16
@vaikas-google Do you have a moment to take a look at this one? If not, I'll poke at it.

**Comment by technosophos** [comment] 2016-06-22 19:59
Cannot reproduce anymore. 

```
⇒  helm fetch kube-charts/alpine-0.1.0 --untar
⇒  ls
LICENSE         README.md       alpine          circle.yml      docs            glide.lock      pkg             scripts         ```

I'm marking this as closed. Please feel free to reopen if you can reproduce it.

**Closed by technosophos** 2016-06-22 19:59 UTC
