### ISSUE TITLE
"required" template function breaks linter

### ISSUE THREAD

**Issue by databus23** [kubernetes/helm#2347] opened 2017-04-28 12:59 UTC
Just noticed that `helm lint` goes out the door as soon as you add your first `{{ required ... }}` to any template.

Steps to reproduce:
```
> helm create something
> helm lint something/
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures

# add a label to the deployment with value: {{ required "missing required value blafasel" .Values.blafasel }}
> helm lint something/
[ERROR] templates/: render error in "blafasel/templates/deployment.yaml": template: blafasel/templates/deployment.yaml:13:17: executing "blafasel/templates/deployment.yaml" at <required "missing re...>: error calling required: missing required value blafasel
```

/cc @wilkers-steve @thomastaylor312

**Comment by wilkers-steve** [comment] 2017-04-28 13:32
@databus23 is the value you're requiring defined in values.yaml?  I'm linting charts with required values just fine currently.  If it's not defined, that's the expected behavior.

**Comment by databus23** [comment] 2017-04-28 13:42
Its not in the charts values.yaml.
Its supposed to be specified which an external values file or `--set` when installing the chart.

As lint does not take any external values you can't use lint anymore on charts having required values.

I'm not sure I follow your argument that a required values has to be present in the charts values file. If I put the value in the charts internal values file the required function becomes a loop as the value has a default set.

**Comment by wilkers-steve** [comment] 2017-04-28 14:00
The original issue for adding the required function can be found [here](https://github.com/kubernetes/helm/issues/1580).  The required function ensures that any value flagged as required as a matching entry in values.yaml, whether it's during linting or installation.

Lint indeed does not take external values, so linting a chart leveraging required values would need a default value set in your chart's values file.  My argument here is that linting is just syntax/render checking at the end of the day, so having a default value for a required value makes sense.  I feel any value seen as required should have a default value as a best practice, even if the intent is to override the value during installation.

**Comment by databus23** [comment] 2017-04-28 14:31
Having a default value for a required values in the charts yams file defeats the whole purpose of the `required` function, no? Its never going to fire.

Some charts require values that can't have a sensible default value, I thought the whole purpose of the `required` function was to provide a human readable errors message if you forget the specify a required value. If I have something like ( `requiredFlag: PLEASE_TYPE_SOMETHING_HERE`) in the charts `values.yaml` file that is not going to happen. The chart will be installed with the bogus value without any error.

I think for linting it would make sense to disable/replace the require function because as you said its a only a syntax/render checker.

**Comment by databus23** [comment] 2017-04-28 14:47
Reading the original issue I still think that my assessment is correct.
The confusion may come from the fact the issue suggested to put a value in the charts.yaml file and annotate that with a comment that it has be provided during chart installation.
```
minecraftServer:
  # @required: This must be overridden, since we can't accept this for the user.
  eula: "FALSE"
```
But this it not how the implemented `required` function works.

If you would put something like `{{ required "Eula needs to be accepted" .Values.minecraftServer.EULA }}` in a template it would happily install the chart.

Using the `required` function this values.yaml would have to look something like this:

```
minecraftServer:
  # This must be overridden, since we can't accept this for the user.
  # eula: "TRUE"
```

But as said before this breaks `helm lint` for this chart.

**Comment by wilkers-steve** [comment] 2017-04-28 15:57
I agree with some of the points you're raising, but gotpl also supports the generation of values.  In such a case, a default value must absolutely be present, whether it's through values.yaml or --set or through a user supplied values file.  If we're generating values that absolutely require defaults to be defined, then that generation falls apart if we don't have defaults present in values.yaml.  However, I also agree with you that some sensible defaults are impossible (example: using helpers for real endpoint lookups).

The required function works as intended if a default value isn't in charts.yaml but is supplied with an override during installation, just not linting.  I'd like to see the linter support values overrides in its runs, or at the very least displaying a warning if the strict flag isn't set and not failing linting due to required values not existing in values.yaml.  Furthermore, I'd like to see the required function included as part of a larger grouping of validation functionality for helm.  I actually would like to propose and work on building a validation method for values, because it does address some of the issues you've raised (re: sensible default values) and also some functionality desired in the original issue.

What are your thoughts?

**Comment by technosophos** [comment] 2017-04-28 23:28
So is the desired solution to be able to supply values file (via `-f` or `--set`) to `helm lint`?

**Comment by databus23** [comment] 2017-04-29 09:18
@technosophos I think the simplest most straight forward solution at least for the next minor release would be to disable/noop the `required` function during linting.
This would allow users to use the `required` function and still use `helm lint` as they are used to.

@wilkers-steve I'm not sure I understand your point gotpl also supporting generation of values. Can you maybe give a concrete example?

In general I'm still not convinced that `helm lint` should check/fail for missing required values that must be provided by the end user. In my mind linting should validate the internal structure of chart without requiring some additional values being passed in for it to succeed.

**Comment by databus23** [comment] 2017-05-02 15:25
With helm 2.4.0 right around the door can we agree to fix this initially by disabling `required` during linting? Right now if you use `required` as intended linting is broken without a good workaround.

I can do the PR if desired.

**Comment by maratoid** [comment] 2017-05-12 20:57
IMHO, linter requiring values to be supplied through -f or --set seems wrong. Chart is either valid, or not valid without outside additional values. Seems like this will also make validation of charts complicated in a CI scenario.

**Comment by sagikazarmark** [comment] 2017-06-20 21:11
For me linting is about checking if the syntax is right, not input validation. So in case of linting I would just replace the required function with one which does nothing and lets the validation pass (even without a value)

**Comment by sstarcher** [comment] 2017-07-27 18:38
Lint should ignored `required` failures.

**Comment by FUSAKLA** [comment] 2017-08-04 11:00
Ignoring required values seems like valid solution in this case.
Are you planning to implement this?

**Comment by Starefossen** [comment] 2017-09-28 13:11
Any update on this? Would like to use required in my custom charts, but that breaks all my CI/CD builds 😕

**Comment by bacongobbler** [comment] 2017-10-31 23:06
@Starefossen please feel free to implement a fix! We are incredibly busy so we haven't been able to get to this. Please feel free to hack up a PR though! This should be a relatively simple fix, so I'm labelling it as a starter issue.

**Comment by tmaier** [comment] 2018-01-04 02:25
I prefer to be able to set `--set` or `-f`. The reason is, that it allows me to lint certain scenarios, for example `subchart1.enabled=false,subchart2.enabled=true` or `controller.kind=DaemonSet`.

All this options may generate different sets of YAML files which need to be linted.

**Comment by Evesy** [comment] 2018-01-04 15:41
Ignoring required values would be my preference. 

While `--set` being supported could be useful I'd still like the option to simply ignored required values, as `--set` become less viable when using templates in CI/CD to do generic test/builds

**Comment by AmundsenJunior** [comment] 2018-01-24 08:15
I would like to take on resolving this issue, but I'd need help with understanding what the solution might be, as ignoring required values doesn't appear as straightforward as assumed.

I was able to reproduce the issue as @databus23 had reported. When I added a second required value to one of the chart templates, it made no difference to the output of `helm lint`, still showing only the one value on which 'required' errored. This is because `pkg/lint` is not doing that work itself, but is calling to `pkg/engine` to render the chart templates. `required` is part of the expanded funcMap, and when it fails in rendering (due to missing value), the entire process stops and returns error at that point back up to its caller - `pkg/lint` in our case. At that point, lint prints out the errors and fails the chart linting. 

If multiple 'required' functions are used within a chart, `pkg/engine` won't proceed after encountering the first `required` error. There isn't anything in-place (nor should there be) in `pkg/engine` to let it know that this is `pkg/lint` calling, so ignore your `required` errors and keep rendering. So the solution would be constrained to changes within `pkg/lint`. `pkg/lint` doesn't handle templates directly, so it wouldn't know which values are required before calling `engine.Render`, in order to "set" those values to linting defaults prior to rendering (unless added as part of the solution, that is).

This is where my imagination fails me, because I only can see a back-and-forth lint-engine.render cycle:

1. call `engine.Render` on the chart files
2. parse errors returned for any "error calling required"
3. set that value to a default, and call `engine.Render` again on the chart with the set value
4. repeat for any additional `required` errors returned.

**Comment by jeff-knurek** [comment] 2018-02-02 13:20
@AmundsenJunior yeah, I was looking into this issue myself the other day, and saw it's not a simple problem to solve. 

Besides the one solution you describe, my other idea was to maybe allow the user to set their `values.yaml` file as such:
```
myVal:
   name: foo
   value:   #required
```
and then in the `pkg/lint` rules, before `chartutil.CoalesceValues`, to convert the `#required` to be a default value _(of course that invokes a high risk of breaking changes, and is where my imagination stopped)_

**Comment by JonJam** [comment] 2018-02-16 07:56
Just came across this as I was having the same issue with lint and required; in my scenario I wanted to pass a secret value using --set and not have any value in values.yaml.

I did get required and lint working together in my scenario with something like the following:

values.yaml
```yaml
# Secret values that should be specified using --set.
secrets:
  value1:
  value2:
```

secret.yaml
``'yaml
apiVersion: v1
kind: Secret
metadata:
type: Opaque
data:
  SECRET1: {{ required ".Values.secret.value1 required!" .Values.secret.value1 }}
  SECRET2: {{ required ".Values.secret.value2 is required!" .Values.secret.value2 }}
```

Running lint
```
helm lint --set secret.value1=SECRETVALUE1,secret.value2=SECRETVALUE2 .
```

If I don't use set to specify the secret values, then I get the required error message.

**Comment by sstarcher** [comment] 2018-06-16 15:56
I don't believe this has been resolved yet. Looks like #4221 would address this

**Closed** 2018-07-16 16:23 UTC
Labels: feature, lifecycle/rotten, starter

**Comment by nvtkaszpir** [comment] 2019-06-05 10:33
Maybe just add `.lint.yaml` file to the chart/<chart-name> with example values so that linter picks it up in when executed?
Otherwise it requires customizations in CI/CD per chart.

**Comment by Nyefan** [comment] 2022-03-29 17:31
For anyone stumbling across this in future we work around this by performing a 

```sh
yq eval-all -Mi '. as $item ireduce ({}; . *+d $item )' values.yaml required.yaml
```

prior to linting/templating.  Any values in both `values.yaml` and `required.yaml` are deep merged with priority going to `required.yaml` in a conflict.  If there are no required values, this is effectively a noop.
