### ISSUE TITLE
Condition value in requirements.yaml gets propagated to subcharts but subcharts deployments/services are not generated

### ISSUE THREAD

**Issue by groundnuty** [kubernetes/helm#2479] opened 2017-05-22 21:36 UTC
~~~
helm version
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
~~~

How to reproduce:
~~~
helm create parent
cd parent/charts
helm create child-level-1
cd child-level-1/charts/
helm create child-level-2
~~~

`parent/requirements.yaml` content:
~~~
dependencies:
- name: child-level-1
  version: 0.1.0
  condition: child-level-1.enabled
  repository: file://%
~~~

`parent/charts/child-level-1/requirements.yaml` content:
~~~
dependencies:
- name: child-level-2
  version: 0.1.0
  condition: child-level-2.enabled
  repository: file://%
~~~

Append to `parent/values.yaml`
~~~
child-level-1:
  enabled: true
  child-level-2:
    enabled: true
~~~

Append to `parent/charts/child-level-1/values.yaml`
~~~
child-level-2:
  enabled: false
~~~

run 
~~~
helm install --dry-run --debug  parent
~~~
the output:
~~~
[debug] Created tunnel using local port: '56196'

[debug] SERVER: "localhost:56196"

[debug] CHART PATH: /tmp/bug/parent

NAME:   xrayed-jackal
REVISION: 1
RELEASED: Mon May 22 23:32:00 2017
CHART: parent-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
child-level-1:
  child-level-2:
    enabled: true
  enabled: true
  global: {}
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: stable
  ingress:
    annotations: null
    enabled: false
    hosts:
    - chart-example.local
    tls: null
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    externalPort: 80
    internalPort: 80
    name: nginx
    type: ClusterIP
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: stable
ingress:
  annotations: null
  enabled: false
  hosts:
  - chart-example.local
  tls: null
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  externalPort: 80
  internalPort: 80
  name: nginx
  type: ClusterIP

HOOKS:
MANIFEST:

---
# Source: parent/charts/child-level-1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: xrayed-jackal-child-level-1
  labels:
    chart: "child-level-1-0.1.0"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx
  selector:
    app: xrayed-jackal-child-level-1

---
# Source: parent/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: xrayed-jackal-parent
  labels:
    chart: "parent-0.1.0"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx
  selector:
    app: xrayed-jackal-parent

---
# Source: parent/charts/child-level-1/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xrayed-jackal-child-level-1
  labels:
    chart: "child-level-1-0.1.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xrayed-jackal-child-level-1
    spec:
      containers:
      - name: child-level-1
        image: "nginx:stable"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi


---
# Source: parent/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xrayed-jackal-parent
  labels:
    chart: "parent-0.1.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xrayed-jackal-parent
    spec:
      containers:
      - name: parent
        image: "nginx:stable"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
~~~

In *COMPUTED VALUES* all needed enabled variables are set to true, but the deployment/service/ingress of child-level-2 is not seen in an output.

On the other hand running:
~~~
helm install --dry-run --debug  --set child-level-2.enabled=true parent
~~~
Produces correct output:
~~~
[debug] Created tunnel using local port: '57275'

[debug] SERVER: "localhost:57275"

[debug] CHART PATH: /tmp/bug/parent

NAME:   giggly-mule
REVISION: 1
RELEASED: Mon May 22 23:44:40 2017
CHART: parent-0.1.0
USER-SUPPLIED VALUES:
child-level-2:
  enabled: true

COMPUTED VALUES:
child-level-1:
  child-level-2:
    enabled: true
    global: {}
    image:
      pullPolicy: IfNotPresent
      repository: nginx
      tag: stable
    ingress:
      annotations: null
      enabled: false
      hosts:
      - chart-example.local
      tls: null
    replicaCount: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    service:
      externalPort: 80
      internalPort: 80
      name: nginx
      type: ClusterIP
  enabled: true
  global: {}
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: stable
  ingress:
    annotations: null
    enabled: false
    hosts:
    - chart-example.local
    tls: null
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    externalPort: 80
    internalPort: 80
    name: nginx
    type: ClusterIP
child-level-2:
  enabled: true
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: stable
ingress:
  annotations: null
  enabled: false
  hosts:
  - chart-example.local
  tls: null
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  externalPort: 80
  internalPort: 80
  name: nginx
  type: ClusterIP

HOOKS:
MANIFEST:

---
# Source: parent/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: giggly-mule-parent
  labels:
    chart: "parent-0.1.0"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx
  selector:
    app: giggly-mule-parent

---
# Source: parent/charts/child-level-1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: giggly-mule-child-level-1
  labels:
    chart: "child-level-1-0.1.0"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx
  selector:
    app: giggly-mule-child-level-1

---
# Source: parent/charts/child-level-1/charts/child-level-2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: giggly-mule-child-level-2
  labels:
    chart: "child-level-2-0.1.0"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: nginx
  selector:
    app: giggly-mule-child-level-2

---
# Source: parent/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: giggly-mule-parent
  labels:
    chart: "parent-0.1.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: giggly-mule-parent
    spec:
      containers:
      - name: parent
        image: "nginx:stable"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi


---
# Source: parent/charts/child-level-1/charts/child-level-2/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: giggly-mule-child-level-2
  labels:
    chart: "child-level-2-0.1.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: giggly-mule-child-level-2
    spec:
      containers:
      - name: child-level-2
        image: "nginx:stable"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi


---
# Source: parent/charts/child-level-1/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: giggly-mule-child-level-1
  labels:
    chart: "child-level-1-0.1.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: giggly-mule-child-level-1
    spec:
      containers:
      - name: child-level-1
        image: "nginx:stable"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
~~~

**Comment by groundnuty** [comment] 2017-05-28 23:17
any comment on this? I think it's a major bug :(

**Comment by jascott1** [comment] 2017-05-31 19:02
@groundnuty Try including `child-level-1` in the condition

```
- name: child-level-2
  version: 0.1.0
  condition: child-level-1.child-level-2.enabled
  repository: file://%
```

**Comment by groundnuty** [comment] 2017-05-31 19:25
@jascott1 it did solve the issue, but I think it's not an acceptable hack.
I develop complex charts similar to OpenStack or Deis:
https://github.com/groundnuty/onedata-charts
the whole point is to create high-level charts that use other charts as a building block, overwriting values when needed or enabling extra dependencies of those lower charts.
Your solution would require modifying child-level-1 chart in order to customise its behaviour.

**Comment by jascott1** [comment] 2017-05-31 22:34
child-level-1 Chart.yaml does not need to be modified only requirements.yaml which already requires modification. You might be looking for a comma separated list of conditions (first one that exists wins) so you can do `condition: child-level-1.child-level-2.enabled, child-level-2.enabled`
Since you mentioned OpenStack, FYI I wrote this feature primarily for the OpenStack kolla-kubernetes project. https://github.com/openstack/kolla-kubernetes/search?utf8=%E2%9C%93&q=condition&type=

**Comment by technosophos** [comment] 2017-06-08 14:52
Do I mark this as a bug or as a support item?

**Comment by groundnuty** [comment] 2017-06-08 16:43
When I'm developing child-level-1 chart and in values.yaml I add `child-level-2.enabled=true`
I should be able to write a condition: `condition: child-level-2.enabled` which should be equivalent to writing in templates: `{{ .Values.child-level-2.enabled }}`. 

At the moment to achieve that one needs to write a condition: `condition: child-level-1.child-level-2.enabled`. 

I would consider this as a bug.

**Comment by jascott1** [comment] 2017-06-08 18:23
I disagree and submit that this is not a bug. It functions as designed which is not the same thing as not covering all use cases. We can discuss altering the design but its not a bug imo. If you are developing a public chart that has nested subcharts you know the hierarchy ahead of time. If you are incorporating others' charts as dependencies then you will need to modify requirements.yaml to accommodate them anyway.

**Comment by groundnuty** [comment] 2017-06-09 21:28
@jascott1 ok, let's say it's not a bug. but how do you expect it to work with aliases?

Let's say that the game plan is:
- you have building block charts that you download that you don't want to edit called `child-level-1` and `child-level-2`. `child-level-1` has requirements.yaml as follows:
~~~
dependencies:
  - name: child-level-2
    version: 0.1.0
    condition: child-level-1.child-level-2.enabled, child-level-2.enabled
    repository: file://%
~~~
and in `values.yaml` you include:
~~~
child-level-2:
  enabled: false
~~~
- you are creating a meta-chart `parent` that will use two child-level-1 charts:
~~~
dependencies:
      - name: child-level-1
        repository: file://%
        condition: alpha-child.enabled
        version: 0.1.0
        alias: alpha-child
      - name: child-level-1
        repository: file://%
        condition: beta-child.enabled
        version: 0.1.0
        alias: beta-child
~~~
and you want to enable alpha-child, beta-child and their inner child-level-2 dependencies, it would seem natural to write this in parent `values.yaml`:
~~~
alpha-child:
  enabled: true
  child-level-2:
    enabled: true
beta-child:
  enabled: true
  child-level-2:
    enabled: true
~~~ 

The condition expects values `child-level-1.child-level-2.enabled` or `child-level-2.enabled` to be set to true. as we use aliases just `alpha-child.child-level-2.enabled` and `beta-child.child-level-2.enabled` will be set to true. 

If we could just specify `child-level-2.enabled` in `child-level-1` `requirements.yaml` the whole problem goes away.

**Comment by jascott1** [comment] 2017-06-09 22:36
The meat of this is that its currently evaluated from the top level parent's values (as specified in the docs) and this change would mean the values are additionally evaluated at each sub level. This might be doable without much fuss but Id also like to coordinate with @sushilkm wrt to aliases to make sure any refactor considers that feature.

**Comment by groundnuty** [comment] 2017-06-13 21:15
any hope to see this in 2.5?

**Comment by jascott1** [comment] 2017-06-13 21:19
IIRC the release is Monday (June 19th). I am ok to work on this but not very confident it will make it into 2.5 since I have other priorities atm. I will do my best to at least assess the necessary changes in the next couple of days.

**Comment by groundnuty** [comment] 2017-06-15 23:34
Thank you. If I can, I'm ofc. happy to help however I can :)

**Comment by jascott1** [comment] 2017-07-05 18:34
@groundnuty I did look into this some and cant decide whether this might break the previous behavior. Either way I don't think it would make it into 2.6 as that is focused on stability and security but I will try to find out if its acceptable.

**Comment by groundnuty** [comment] 2017-07-06 07:07
Since our discussion, I managed to finish and publish some charts that we use in our CI/CD flow so I can give some more concrete examples:

I have a component chart that depends on many things:
https://github.com/groundnuty/onedata-charts/blob/master/oneprovider/requirements.yaml

This chart is consumed 3 times (aliases), by a chart the defines a proper deployment of a system:
https://github.com/groundnuty/onedata-charts/blob/master/onedata-3p/requirements.yaml

The proper deployment of the system chart is consumed by a chart that is responsible for this deployment initialization (create sample data etc):
https://github.com/groundnuty/onedata-charts/blob/master/cross-support-job-3p/requirements.yaml

Our CI/CD just deploys the last (*cross-support-job-3p*) chart and supplies a values file (`helm install -f landscape.yaml) (I wanted to use landscaper initial, hence the name) to customize the behavior (override Docker tags with never etc) of *cross-support-job-3p* and all its dependencies. 
https://github.com/onedata/k8s-deployment/blob/master/landscapes/develop/landscape.yaml

The problem in question is seen here:
https://github.com/onedata/k8s-deployment/blob/master/landscapes/develop/landscape.yaml#L97

In a perfect world this entry would be sufficient:
https://github.com/onedata/k8s-deployment/blob/master/landscapes/develop/landscape.yaml#L137
where I try to override the value that is nested like:
cross-support-job-3p.onedata-3p.oneprovider-krakow(alias for oneprovider).oneclient.enabled

It all works, just looks very improper atm. :)

**Comment by bacongobbler** [comment] 2017-08-11 21:54
labelling as question/support at this point. It's not a bug, but it's also a potential breaking fix so it sounds like there needs to be more discussion here on a resolution/workaround.

**Comment by bacongobbler** [comment] 2017-10-31 23:36
Closing this as a wontfix. @jascott1 is right; this is working as intended both for Openstack and for Deis users alike (both charts of which are maintained by ourselves, so we understand the scope of the proposed change here).

Umbrella chart conditional requirements are intended to be parsed at the umbrella chart's level, not of the subcharts. Changing this behaviour would be a breaking change and is not something we're going to consider. Sorry!

**Closed by bacongobbler** 2017-10-31 23:36 UTC
Labels: question/support
