### ISSUE TITLE
Release failed: unable to decode Third Party Resource

### ISSUE THREAD

**Issue by enisoc** [kubernetes/helm#1739] opened 2016-12-20 18:36 UTC
The [stable/etcd-operator](https://github.com/kubernetes/charts/tree/master/stable/etcd-operator) chart doesn't work with the latest Kubernetes 1.5.1 and Helm 2.1.0 releases. It seems to be related to the interaction of Helm with Third Party Resources. In https://github.com/kubernetes/helm/issues/1531#issuecomment-268103550, @lachie83 reported being able to successfully apply the dry-run output directly to Kubernetes.

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
Client: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ helm install --set cluster.enabled=true stable/etcd-operator
Fetched stable/etcd-operator to etcd-operator-0.1.0.tgz
Error: release interested-armadillo failed: unable to decode "": no kind "EtcdCluster" is registered for version "coreos.com/v1"
```

Deleting the release also fails:

```console
$ helm delete interested-armadillo
Error: deletion completed with 1 error(s): unable to decode "": no kind "EtcdCluster" is registered for version "coreos.com/v1"
```

**Comment by technosophos** [comment] 2016-12-20 19:44
Can you run `kubectl api-versions` and verify that coreos.com/v1 is in that list?

**Comment by enisoc** [comment] 2016-12-20 19:58
Looks like it's there:

```console
$ kubectl api-versions
apps/v1beta1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1beta1
autoscaling/v1
batch/v1
certificates.k8s.io/v1alpha1
coreos.com/v1
extensions/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1alpha1
storage.k8s.io/v1beta1
v1
```

**Comment by technosophos** [comment] 2016-12-21 22:02
@lachie83 is this something you can reproduce?

**Comment by lachie83** [comment] 2016-12-21 22:38
Yes. I can reproduce this same issue.

**Comment by paultiplady** [comment] 2017-01-05 01:08
@technosophos this could be a dupe of https://github.com/kubernetes/helm/issues/1468, which got  a code fix that doesn't seem to be working in 2.0.

**Comment by technosophos** [comment] 2017-01-11 17:21
I'm going to try to hunt down the cause of #1468 today

**Comment by technosophos** [comment] 2017-01-11 19:59
So the issue with the `etcd-operator` chart there is a race condition where the Deployment doesn't install the TPR before the chart tries to create a new resource. I updated #1531 accordingly. I am going to close this issue for the time being, since I think at this point it is basically a duplicated of #1531, and I will just keep updating that issue.

**Closed by technosophos** 2017-01-11 19:59 UTC
Labels: support
