### ISSUE TITLE
`helm delete` does not remove the associated pods

### ISSUE THREAD

**Issue by sameersbn** [kubernetes/helm#747] opened 2016-05-20 16:20 UTC
Deleting a release from Kubernetes using `helm delete <release-name>` deletes the RC and Service but leaves the Pods running. Deletion of the RC should typically remove the associated Pods but for some reason this is not happening with `helm`.

Manually deleting a RC using `kubectl delete rc <rc-name>` removes the RC and the associated Pods.

**Comment by runseb** [comment] 2016-05-20 16:25
actually kubectl does this because there is a reaper that deletes the underlying pods. But deleting an RC with an API call does not automatically deletes the pods.

there is a proposal for a cascading deletion which might make it to 1.3:

https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/garbage-collection.md

**Comment by technosophos** [comment] 2016-05-20 16:58
Okay. We'll have to keep an eye on this one. If we hit beta and the issue isn't resolved upstream, I think we'll need to implement the logic client-side.

**Comment by sameersbn** [comment] 2016-06-10 05:42
Should this issue be associated with a milestone?

**Comment by technosophos** [comment] 2016-06-10 15:36
Yeah, I'll put it on Alpha.3.

I wonder if we should add a `release: {{.Release.Name}}` label by convention, and then do a deletion by label in addition to doing the main delete op. /cc @adamreese

**Comment by technosophos** [comment] 2016-06-21 16:16
I have also noticed that when a deployment creates a replica set, neither the replica set nor its associated pods seem to get cleaned up.

**Comment by prydonius** [comment] 2016-07-08 15:40
+1 to getting a fix for this sooner

**Comment by ngtuna** [comment] 2016-07-10 15:34
Hi guys, I just start working on Helm. Is anyone working on this issue ? If not, I will go forward to take it.

**Comment by technosophos** [comment] 2016-07-15 15:35
Nobody is actively working on it. My understanding is that there is a way to trigger a "reaper" on the Kube API server to clean up these things, but I've never looked into it.

**Comment by ngtuna** [comment] 2016-07-16 17:56
Checked!

**Comment by adamreese** [comment] 2016-07-26 21:48
@ngtuna are you currently working on this?  Let me know if you need some help

**Comment by ngtuna** [comment] 2016-07-27 04:21
@adamreese Thanks. I didn't start. Will take a look this week and let you know.

**Comment by adamreese** [comment] 2016-07-28 15:49
@ngtuna I had some time to look at this and it was pretty straight forward.  I went ahead and implemented because It's a hot issue for our next release.

**Closed** 2016-07-28 17:33 UTC

**Comment by ngtuna** [comment] 2016-07-28 17:42
Great to know you took it so quick @adamreese. +1

**Comment by technosophos** [comment] 2016-07-28 20:15
Yeah, that one was a release blocker on Alpha.3, so we had to rush it along to make our deadline. Sorry for the quick switch on that.
