### ISSUE TITLE
`helm repo add` does not work with corporate certs

### ISSUE THREAD

**Issue by erip** [kubernetes/helm#3792] opened 2018-03-29 14:33 UTC
### Output of `helm version`:

```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

### Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud Provider/Platform (AKS, GKE, Minikube etc.):  

minikube

### Description:

I can curl a resource file:

```
$ curl --cacert ~/.cert/corporate-cert.pem https://lightbend.github.io/helm-charts/index.yaml
apiVersion: v1
entries:
  enterprise-suite:
  - apiVersion: v1
    created: 2018-03-07T18:46:14.935560601Z
    description: Lightbend Enterprise Suite
    # ...
```

but I cannot add with `--ca-file`:

```
$ helm repo add --ca-file ~/.cert/corporate-cert.pem lightbend-helm-charts https://lightbend.github.io/helm-charts

Error: Looks like "https://lightbend.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get https://lightbend.github.io/helm-charts/index.yaml: x509: certificate signed by unknown authority
```

I've added this cert to my minikube VM `/etc/ssl/certs/ca-certificates.crt`, but I still cannot add the repository.

**Comment by erip** [comment] 2018-04-03 11:19
@jascott1 You've marked this as a question -- does that imply this is expected behavior?

**Comment by jascott1** [comment] 2018-04-03 16:39
Hi @erip 

I did not have an immediate answer and have not confirmed the behavior to be a bug so I marked it as a support request. The error message suggests to me that your OS doesn't respect that CA for some reason, perhaps confirm that a tool that relies on system accepted CA works with that cert.

**Comment by nazarewk** [comment] 2018-04-12 09:09
@erip in my opinion this is a valid bug since `helm repo add` just ignores `--ca-file` here.

**Comment by bacongobbler** [comment] 2018-04-12 14:36
Tentatively fixed via #3258. Please reopen if this isn't true. Thanks!

**Closed by bacongobbler** 2018-04-12 14:36 UTC
Labels: question/support

**Comment by erip** [comment] 2018-04-12 14:37
@bacongobbler I'll give this a try on the next release of helm. Cheers!

**Comment by erip** [comment] 2018-04-12 15:00
Ooooh, that would be marvelous if this snuck into 2.9.0-RC4! Thanks again!

**Comment by jonsalvas** [comment] 2018-06-01 13:05
I can confirm that the issue not fixed in 2.9.1.  Still getting this error message when trying to pass a cert over --ca-file option.

**Comment by bacongobbler** [comment] 2018-06-01 14:45
@jonsalvas can you try with a canary release instead? I don't think this patch made its way into 2.9 after reviewing #3258.

**Comment by jonsalvas** [comment] 2018-06-04 05:56
@bacongobbler nope, did not work either..

`helm repo add --ca-file=C:\Dev\myurl.pem nexus https://my.url.net/nexus/repository/Helm/
Error: Looks like "https://my.url.net/nexus/repository/Helm/" is not a valid chart repository or cannot be reached: Get https://my.url.net/nexus/repository/Helm/index.yaml: x509: certificate signed by unknown authority`

**Comment by ReggieCarey** [comment] 2019-02-12 18:37
This apparently was only fixed for a specific subcommand.  Helm does not honor a CACERT configuration.  A simple operation 'helm version' reports "x509: certificate signed by unknown authority" when fetching kubernetes details from a remote cluster.  This is due to no mechanism for specifying corporate CA certificates for an invocation of the "helm" command.

OS: MacOS Mojave
Helm Version: 2.12.3
AWS EKS - as of 12 Feb 2019.  (1.11.5)

the existence of  ~/.helm/ca.cert has absolutely no effect.  The --tls parameter has no effect
The basic problem is that helm cannot communicate securely with Kubernetes even though kubectl can.

e.g.

MyMac:~ me$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Error: Get https://ec2-1-2-3-4.compute-1.amazonaws.com/k8s/clusters/c-xmnhv/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: x509: certificate signed by unknown authority

MyMac:~ me$ helm ls
Error: Get https://ec2-1-2-3-4.compute-1.amazonaws.com/k8s/clusters/clusterName/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: x509: certificate signed by unknown authority

MyMac:~ me$ helm ls --tls
Error: Get https://ec2-1-2-3-4.compute-1.amazonaws.com/k8s/clusters/clusterName/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: x509: certificate signed by unknown authority

**Comment by zoobab** [comment] 2019-04-18 08:14
Still have the problem with helm v2.13.1.

**Comment by kopf** [comment] 2019-04-23 13:18
> Still have the problem with helm v2.13.1.

Same here. Can we re-open this?

**Comment by bacongobbler** [comment] 2019-04-23 15:47
Can you re-open a new ticket with the commands that do not work with TLS certs? That way we can better track what action items are required to close the ticket. As far as the original report, `helm repo` commands now work with TLS certs so I'd like to see what exactly does not work for you and we can nail that down in a separate thread. Thanks!

**Comment by kopf** [comment] 2019-04-23 16:13
Hey @bacongobbler , thanks for the quick response! I've created #5632 with some debug logs. I hope that helps.
