### ISSUE TITLE
Dependency providing CRD, not installed first

### ISSUE THREAD

**Issue by zeenix** [kubernetes/helm#3632] opened 2018-03-08 13:38 UTC
I've been writing a [Helm exporter for the Habitat project](https://www.habitat.sh/blog/2018/02/Habitat-Helm/) for some weeks now and during my testing, I've come across a few issues. This is one of them and the most critical one for us. I'm using Helm version 2.8.2.

The template in the charts created by the said exporter, uses a particular CRD that is created/provided by habitat-operator. To avoid users having to install the habitat-operator manually before they could install the charts, we decided to make it completely transparent to user by making use of Helm's dependencies/requirements concept.

The problem is that Helm either tries to install both the main (exported) chart and the dependency habitat-operator chart simultaneously, in the wrong order or it just doesn't wait for the dependencies to be fully initialized in the cluster (i-e pod to be ready) before it tries to apply the chart's templates and hence it ends up in a failure:

```
# helm install nginx
Error: apiVersion "habitat.sh/v1beta1" in nginx/templates/habitat.yaml is not available
```

but this works out:

```
# helm install nginx/charts/habitat-operator-0.5.1.tgz 
...
# helm install nginx
```

While the good thing is that it's not hard to work-around this by manually installing the habitat-operator first but that't not a very useful workaround since you end up with two deployments of habitat-operator in the cluster then, which is not desirable at all.

The latest habitat-operator chart is available at https://kinvolk.github.io/habitat-operator/helm/charts/stable/habitat-operator-0.5.1.tgz.

**Comment by thomastaylor312** [comment] 2018-03-10 00:03
There are some workarounds for this where you can only install the CRD on install, and then all subsequent upgrades use the rest of the chart. The main issue is being tracked in #2994

**Comment by zeenix** [comment] 2018-03-12 14:12
@thomastaylor312 Thanks. 

> There are some workarounds for this where you can only install the CRD on install, and then all subsequent upgrades use the rest of the chart. 

I am not sure I understood which comment you mean. One comment pointed to the workaround in the [docs ](https://docs.helm.sh/chart_best_practices/#install-a-tpr-declaration-before-using-the-resource) and seems only the method 2 is the only solution. I tried that and turned the habitat-operator CRD deployment into a pre-install hook and it worked perfectly for installing the chart but deletion becomes a NOOP:

```
# helm install nginx
NAME:   fancy-tortoise
LAST DEPLOYED: Mon Mar 12 14:59:40 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ServiceAccount
NAME                             SECRETS  AGE
fancy-tortoise-habitat-operator  1        0s

==> v1beta1/ClusterRole
NAME                             AGE
fancy-tortoise-habitat-operator  0s

==> v1beta1/ClusterRoleBinding
NAME                             AGE
fancy-tortoise-habitat-operator  0s

==> v1beta1/Habitat
NAME                          AGE
nginx-1.11.10-20180216165808  0s


# helm list
NAME          	REVISION	UPDATED                 	STATUS  	CHART        	NAMESPACE
fancy-tortoise	1       	Mon Mar 12 14:59:40 2018	DEPLOYED	nginx-1.11.10	default  
# kubectl get pods
NAME                                               READY     STATUS    RESTARTS   AGE
fancy-tortoise-habitat-operator-84b67ff47b-9tqbv   1/1       Running   0          16s
nginx-1.11.10-20180216165808-665dd9dbd6-jvrlq      1/1       Running   0          15s
# helm delete --purge fancy-tortoise
release "fancy-tortoise" deleted
# kubectl get pods
NAME                                               READY     STATUS    RESTARTS   AGE
fancy-tortoise-habitat-operator-84b67ff47b-9tqbv   1/1       Running   0          55s
nginx-1.11.10-20180216165808-665dd9dbd6-jvrlq      1/1       Running   0          54s
```

Also #2994 seems to be about a much bigger issue: CRDs from a chart being 
used by templates in other charts and as one of the comment explains, that's a very hard issue to solve. However, my issue is a very simple one and I was wondering if it could be solved without having to change anything in the helm design: The umbrella chart should not be installed before all the required charts have been installed and their underlying k8s resources are ready. Or am I missing something?

**Comment by thomastaylor312** [comment] 2018-03-13 02:24
I forgot that was in the docs! The other way I was thinking of is how the [Istio chart did it](https://github.com/kubernetes/charts/blob/master/incubator/istio/templates/custom-resources/custom-resources.yaml#L1) (see also the README for that chart).

As for order of install, Helm takes all of the generated manifests (umbrella and subcharts) and sorts them in the order defined [here](https://github.com/kubernetes/helm/blob/500c9983b5fa6d32bad9d95f00c4bea8d7b5430a/pkg/tiller/kind_sorter.go#L29). But it doesn't wait for previous resources to be ready before continuing.

**Comment by zeenix** [comment] 2018-03-13 12:57
> I forgot that was in the docs! The other way I was thinking of is how the Istio chart did it (see also the README for that chart).

Thanks. That's not a very bad workaround at all but if we're going to ask the users to run two commands, we might as well ask them to install the operator manually before installing the chart using it.

> As for order of install, Helm takes all of the generated manifests (umbrella and subcharts) and sorts them in the order defined here. But it doesn't wait for previous resources to be ready before continuing.

That order seems good and in many cases (including ours), it will help if helm waited for the resources to be ready.

**Comment by thomastaylor312** [comment] 2018-03-14 00:11
@zeenix So I think that adding waiting like that would probably warrant a proposal. If you'd like to write one up, feel free to ping me and I'll get it tagged properly

**Comment by dotw** [comment] 2018-03-22 04:17
@zeenix How did you install another chart in pre-install hook? could u share some codes with us?

**Comment by zeenix** [comment] 2018-03-22 10:12
@dotw Sorry, I lost my test chart and I'm no longer working on this.

**Comment by thomastaylor312** [comment] 2018-03-23 16:55
@zeenix Did we get a sufficient answer to your question? Wanted to double check before closing

**Comment by zeenix** [comment] 2018-03-23 17:12
@thomastaylor312 Thanks. I dont quite understand. In this issue we identified ( a very serious IMO) problem with how Helm works, as you seemed to agree in https://github.com/kubernetes/helm/issues/3632#issuecomment-372861843. So I would expect this to be closed after the said issue has been resolved.

The reason I think the issue is very serious is that in every kind of package manager I have ever encountered, dependencies are guaranteed to be handled in a very sequential way. While the installation of independent dependencies can and should be parallelised, a dependency is always expected to be installed and ready before installation of dependent package is attempted.

But as I said, I'm no longer working on this myself so up to you how you want to proceed.

**Comment by bacongobbler** [comment] 2018-03-23 18:27
I'm pretty sure this is a duplicate of #2994. #2994 is about ensuring that CRDs are registered before we install the CRD resources, which appears to be the same problem as described here.

Let's follow up in #2994 instead so we're all working off of a single ticket. Thanks!

**Closed by bacongobbler** 2018-03-23 18:27 UTC
Labels: question/support
