### ISSUE TITLE
Upgrade fails when deployment.spect.template has a chart label

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#2494] opened 2017-05-25 10:14 UTC
I'm not sure why this is happening. I went ahead and added a `chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"` to a `Deployment`'s `spec.template.metadata.labels`. I upgraded the chart, and got this error:

```
Error: UPGRADE FAILED: Deployment.extensions "test-demo" is invalid: spec.template.metadata.labels: Invalid value: {"app":"test-demo","chart":"demo-0.1.1"}: `selector` does not match template `labels`
```

It seems that this label should **not** be applied to a deployment template?

**Versions**

```
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
```

**Reproduction Steps**

```
helm init demo
helm install --release test demo/
# add to the deployment's spect template labels: chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
# bump the version
helm upgrade test demo/
```

**Suggestion**

I'm guessing that helm expects certain labels for anything in the chart. There are also cases were labels must not be present. `helm lint` should cover this.

**Comment by seh** [comment] 2017-05-25 16:41
This is [a restriction in Kubernetes itself](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#selector), unrelated to Helm:
> `.spec.selector` is an optional field that specifies a label selector for the Pods targeted by this deployment.
> If specified, `.spec.selector` must match `.spec.template.metadata.labels`, or it will be rejected by the API. If `.spec.selector` is unspecified, `.spec.selector.matchLabels` will be defaulted to `.spec.template.metadata.labels.`

I take it you have a `.spec.selector` in your _Deployment_.

**Comment by mikesplain** [comment] 2017-06-28 15:13
Just for future reference I ran into this because I was adding `chart: "{{.Chart.Name}}-{{.Chart.Version}}"` as `.spec.template.metadata.labels` which would also become `.spec.selector.matchLabels` after the first release. On the second release if I bumped the version number, I'd get the above error (since `.spec.selector.matchLabels` and `.spec.template.metadata.labels` would now be different).  Removing the chart label from `.spec.template.metadata.labels` and only using it in `.metadata.labels` seems to make it work normally.

**Comment by jkamenik** [comment] 2017-10-20 19:54
I have this situation in a production deployment.  Is there a combination of steps I can perform to change the `.spec.selector` along with the `.spec.template.metadata.labels` to fix this.

**Comment by bacongobbler** [comment] 2017-10-31 23:45
deployment spec selectors are no longer mutable as of apps/v1beta2 and this is noted upstream in https://github.com/kubernetes/kubernetes/pull/50719. Short of `helm delete --purge myrelease` and running `helm install` again on your chart, there is no way to mutate the selector labels.

**Comment by bacongobbler** [comment] 2017-10-31 23:46
closing as a wontfix/working as intended according to upstream.

**Closed by bacongobbler** 2017-10-31 23:46 UTC
Labels: question/support

**Comment by rcorre** [comment] 2018-06-07 17:06
@bacongobbler should https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md#standard-labels be updated to stop recommending a `chart={{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}` label? Seems like anyone following the "best practices" will encounter this issue.

**Comment by rcorre** [comment] 2018-06-07 17:10
> Short of helm delete --purge myrelease and running helm install again on your chart, there is no way to mutate the selector labels.

Is `--purge` overkill? I'm not sure how wiping out your release history would help -- just deleting should remove the deployment and reset helm's internal state.

**Comment by desaintmartin** [comment] 2018-08-24 12:53
What is the official recommendation from Helm for Deployments regarding this issue? Deleting/recreating a Release or part of it during an upgrade is NOT an option in production, and --force would break any RollingUpdate.

**Comment by jkamenik** [comment] 2018-08-24 17:38
Not sure this is "official" but what I did was describe the deployments that were failing then I hand edited the chart to make the labels static.  That way when helm upgrades the charts those items are not seen as changed.

And I learned from this not to put dynamic data in labels.

**Comment by rcorre** [comment] 2018-12-04 18:29
It has been about 6 months and the [best practices](https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md#standard-labels) still recommend a `chart` label.

I'm seeing a lot of teams shooting themselves in the foot with this. You create a chart, deploy it successfully, everything seems fine. Then later on you try to upgrade and realize your only option is to `delete --purge` and incur downtime.

I see some mention of this in https://github.com/helm/charts/issues/3011, but that seems to be some large meta-issue for a repo separate from these docs.

**Comment by Draiken** [comment] 2019-03-28 12:35
@rcorre I do think you can manually fix the issue. It's not what Helm should force you to do, but it is a workaround.
You can remove the deployment/replicaset (without cascading, keeping the pods alive), then update the pods labels (and anything that depends on them, like services) then redeploy. The new deployment should recognize those same pods as up already. If not, the new deployment should go live and you can manually remove the old pods with no downtime.
I believe a teammate of mine did this successfully, but I'd definitely recommend testing it out first :slightly_smiling_face:

**Comment by desaintmartin** [comment] 2019-03-28 12:54
You can see how the community charts document this, for example Redis: https://github.com/helm/charts/pull/7686/files#diff-b290a06961a11374d72f584e5925762cR53
