### ISSUE TITLE
Feature Request: Ability to override/omit subchart templates.

### ISSUE THREAD

**Issue by josdotso** [kubernetes/helm#3045] opened 2017-10-19 15:41 UTC
I’ve written a helm parent chart to wrap a stable public chart.  The public chart didn’t provide for the creation of a basic auth secret, and so my wrapper chart adds that.  This works well.  

However, now I’d like to see some features added to the child chart — such as anti-affinity, more than 1 replica, and so on.  

Is there any way from a parent chart to override/omit the child chart templates, beyond what is exposed in values.yaml?  In this example, child chart doesn’t parameterize the replica integer.  I can always contribute parameterization upstream, but the intent is to not fork upstream for too long.  And contributing upstream has lag time.  Thoughts?

**Comment by jascott1** [comment] 2017-10-20 23:33
Hi @josdotso,

Its true that we should fork as a last resort but if the chart is not terribly complex then it might be the correct decision. Charts are generally not complex and update much less often than the actual images they install. That being said, `wrapper` charts that can re-compose the pieces (templates) of sub-charts is an interesting idea.
 
Im going to tag as a 'feature' with 'help wanted' to signify a detailed proposal/PR would be considered.

**Comment by Nitrogenycs** [comment] 2017-11-19 16:48
This is probably a duplicate of https://github.com/kubernetes/helm/issues/2399.

**Comment by bacongobbler** [comment] 2018-03-19 18:58
closing in favour of #2399

**Closed by bacongobbler** 2018-03-19 18:58 UTC
Labels: feature, help wanted, lifecycle/rotten

**Comment by muehlburger** [comment] 2018-06-06 08:09
#2399 does not mention on how to omit child templates in a parent chart. I'd like to omit a child template and reimplement it in the parent chart. How would this be possible?

**Comment by pavdmyt** [comment] 2019-02-06 13:16
@bacongobbler I'm having the same question as @muehlburger 

#2399 provides only solution for single value modification.

**Comment by prein** [comment] 2020-04-14 10:51
I guess the suggested way to achieve a wrapper-like functionality would currently be using "post renderer" (since Helm 3.1).

**Comment by musabmasood** [comment] 2020-07-03 20:00
The `--post-renderer` option is good but doesn't let you utilize values from `values.yaml` into templates. For instance, I would like to add an extra template to an upstream chart and utilize one of the values from `values.yaml`. I don't think `post-renderer` can do that.

**Comment by sslavic** [comment] 2020-07-10 17:12
Reopen?
