### ISSUE TITLE
helm delete sometimes silently fails with minikube

### ISSUE THREAD

**Issue by mcandre** [kubernetes/helm#2048] opened 2017-03-01 17:37 UTC
Sometimes, `helm delete <release>` reports success, but in fact, `kubectl get pods,pv,pvc` continues to show leftover resources.

# Workaround

It's crude, but `minikube delete && minikube start [--kubernetes-version "<version>"] && helm init` and redeploying the desired resources helps to work around this issue.

# System

I'm not sure if the root cause of this conflict is wholly in helm's camp, or minikube, or wherever, so I'll just report my stack specs:

* helm 2.2.1
* Kubernetes 1.4.5
* minikube 0.16.0
* VirtualBox 5.1.14
* macOS Sierra

**Comment by technosophos** [comment] 2017-03-07 22:17
Can you fetch the logs from `tiller`'s pod?

**Comment by technosophos** [comment] 2017-03-07 22:18
Oh! Also, some of this is from Kubernetes 1.4 itself, which doesn't necessarily reap pods that were created by sets (like Deployment).

**Comment by bacongobbler** [comment] 2017-10-31 20:22
IIRC this was fixed in future releases of Kubernetes since 1.4. I'd try helm 2.7 with k8s 1.8 and see if this can be reproduced.

I'm going to close this, but please feel free to re-open if this is still an issue for you. Thanks!

**Closed by bacongobbler** 2017-10-31 20:22 UTC
Labels: question/support
