### ISSUE TITLE
Sprig manipulation template in Helm

### ISSUE THREAD

**Issue by Mumrau** [kubernetes/helm#4133] opened 2018-05-28 13:53 UTC
Hello,

The docs suggests that :
> Helm has over 60 available functions. Some of them are defined by the Go template language itself. Most of the others are part of the Sprig template library. We’ll see many of them as we progress through the examples.

Nonetheless, I do believe that it would be quite great to import what's left (or at least file a properly detailed handbook for what's available). Some pretty essential functions that are desperately needed in order to handle a proper global configuration (for example a deployment configuration in which you just substitute the values files for every microservice you would like to deploy). Some of them incluses toUpper, toLower to handle the case, and even potentially every function.

I might actually have missed it, but I couldn't successfully import any of the desired functions or library into my templates code. So I am actually wondering whether I missed something or to suggest the addition of strings fuctions (at least) to Helm core.

What would you think about that addition, would it break something in the philosophy?

**Comment by omkensey** [comment] 2018-06-12 16:16
I have this issue filed recently as well: #4077

**Comment by bacongobbler** [comment] 2018-06-12 17:06
thansk for pointing that out @omkensey :) was having a hard time finding the duplicate. closing this as a duplicate of #4077

**Closed by bacongobbler** 2018-06-12 17:06 UTC
Labels: docs
