### ISSUE TITLE
Add sanity check to `helm upgrade` to check chart name matches release

### ISSUE THREAD

**Issue by nickjackson** [kubernetes/helm#2404] opened 2017-05-05 11:50 UTC
Unless I am mistaken, it appears to be possible to `helm upgrade` an existing release with **any** chart and version. This seems a bit dangerous to me.

Would it be possible to add a flag to `helm upgrade` to act as a sanity check, only allowing the upgrade to proceed if the chart name is the same and the chart version has been bumped?

**Comment by thomastaylor312** [comment] 2017-05-06 05:35
This sounds like a great feature idea.

**Comment by SlickNik** [comment] 2017-05-09 23:11
@thomastaylor312 @nickjackson Looking at a fix for this -- feel free to assign it to me when you get a chance. Thanks!

**Comment by thomastaylor312** [comment] 2017-05-10 00:10
@SlickNik I can't assign it to you because you didn't create the issue, so I am assigning it to me so others don't work on it. Thank you for taking this on!

**Comment by yan234280533** [comment] 2017-05-10 02:42
Surely, it a great feature idea.   In our usage scenario, We forbid the user to update the release when the name of the chart name is not the same.  Look forward to use this feature.

**Comment by technosophos** [comment] 2017-07-11 23:31
It was our intention to allow an upgrade to switch charts. So it has always been legal to do `helm install -n foo myChart` and then later `helm upgrade foo myChartTwo`. Likewise, it is possible (by design) to "upgrade" to a version that is lower, higher, or identical to the current chart.

I have actually taken advantage of this feature on several occasions, though I can certainly understand why some people would want to prevent this.

Because chart swapping is a feature of the current system, the only way to get this request into Helm 2 would be to hide the functionality behind a flag (`--no-chart-swap` or something).

**Comment by SlickNik** [comment] 2017-07-11 23:50
@technosophos @sushilkm Yes, when I initially took a look at implementing this I envisioned having a flag named "--safe"  or something similar which:
1. Would ensure that you're not trying to upgrade from a chart of one kind to a chart of a totally different kind.
2. Potentially could also check versions to ensure that you're not downgrading to a different lower or identical version of a chart. 

However, in order for it to be backwards compatible with the current functionality we have in helm today, it would necessarily have to be an additional flag. This would preserve the current functionality of the helm upgrade command.

**Comment by sushilkm** [comment] 2017-07-12 17:50
I think `no-chart-swap` should be default behavior,  and `swap-chart` could be a flagged change.
what i intend to suggest is that sanity checks should not be flag based instead they should be default.

However I am still open to implement it based on flag based sanity checks, if that is what we want to do.

**Comment by thomastaylor312** [comment] 2017-07-14 16:01
@sushilkm I think the debate with that is backward compatibility. We don't want to change the default behavior out under people, but adding something like a `--save` flag wouldn't be a problem.

**Comment by bacongobbler** [comment] 2017-10-31 23:14
should we slate this as a discussion topic for helm 3?

**Comment by thomastaylor312** [comment] 2017-10-31 23:17
Yeah, let's bump this out to the major milestone and slate it for Helm 3

**Comment by SlickNik** [comment] 2017-10-31 23:20
Agreed -- let's push this out to the next major milestone (Helm 3).

**Closed** 2018-03-31 01:41 UTC
Labels: feature, lifecycle/rotten
