### ISSUE TITLE
Helm upgrade stuck in locking release

### ISSUE THREAD

**Issue by eric4545** [kubernetes/helm#2627] opened 2017-06-28 09:42 UTC
When we `helm upgrade --wait` it will stuck forever, checked in tiller log it stop in `[storage] 2017/06/25 15:22:43 locking release` 

```
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

**Comment by thomastaylor312** [comment] 2017-06-29 04:37
@eric4545 What Kubernetes version are you running? Also, could this be related to #2426?

**Comment by eric4545** [comment] 2017-06-29 05:47
K8s server/client version:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

Attached the log, I only upgrading one release `testing-secure`, but in the log there is another lock suddenly appear, don't know is it related. 
```
E  [tiller] 2017/06/29 03:22:35 getting history for release testing-secure
E  [storage] 2017/06/29 03:22:35 getting release history for "testing-secure"
E  [storage] 2017/06/29 03:22:35 locking release testing-secure
E  [storage] 2017/06/29 03:22:35 listing all releases in storage
E  [tiller] 2017/06/29 03:22:35 preparing update for testing-secure
E  [storage] 2017/06/29 03:22:35 getting last revision of "testing-secure"
E  [storage] 2017/06/29 03:22:35 getting release history for "testing-secure"
E  [tiller] 2017/06/29 03:22:35 rendering secure chart using values
E  [tiller] 2017/06/29 03:22:35 performing update for testing-secure
E  [tiller] 2017/06/29 03:22:35 executing 0 pre-upgrade hooks for testing-secure
E  [tiller] 2017/06/29 03:22:35 hooks complete for pre-upgrade testing-secure
E  [kube] 2017/06/29 03:22:35 building resources from updated manifest
E  [kube] 2017/06/29 03:22:36 checking 5 resources for changes
E  [kube] 2017/06/29 03:22:36 Looks like there are no changes for ConfigMap "secure-conf"
E  [kube] 2017/06/29 03:22:36 Looks like there are no changes for ConfigMap "secure-nginx-conf"
E  [kube] 2017/06/29 03:22:36 Looks like there are no changes for Service "secure-svc"
E  [kube] 2017/06/29 03:22:36 Looks like there are no changes for Ingress "secure-ing"
E  [kube] 2017/06/29 03:22:36 beginning wait for 5 resources with timeout of 5m0s
E  [kube] 2017/06/29 03:22:38 resources ready: false
E  [kube] 2017/06/29 03:22:40 resources ready: false
E  [kube] 2017/06/29 03:22:42 resources ready: false
E  [kube] 2017/06/29 03:22:44 resources ready: false
E  [kube] 2017/06/29 03:22:46 resources ready: false
E  [kube] 2017/06/29 03:22:48 resources ready: false
E  [kube] 2017/06/29 03:22:50 resources ready: false
E  [kube] 2017/06/29 03:22:52 resources ready: false
E  [kube] 2017/06/29 03:22:54 resources ready: false
E  [kube] 2017/06/29 03:22:56 resources ready: false
E  [kube] 2017/06/29 03:22:58 resources ready: false
E  [kube] 2017/06/29 03:23:00 resources ready: false
E  [kube] 2017/06/29 03:23:02 resources ready: false
E  [kube] 2017/06/29 03:23:04 resources ready: false
E  [kube] 2017/06/29 03:23:06 resources ready: false
E  [kube] 2017/06/29 03:23:08 resources ready: false
E  [kube] 2017/06/29 03:23:10 resources ready: false
E  [kube] 2017/06/29 03:23:12 resources ready: false
E  [kube] 2017/06/29 03:23:14 resources ready: false
E  [kube] 2017/06/29 03:23:16 resources ready: false
E  [kube] 2017/06/29 03:23:18 resources ready: false
E  [tiller] 2017/06/29 03:23:18 getting history for release testing-secure
E  [storage] 2017/06/29 03:23:18 getting release history for "testing-secure"
E  [storage] 2017/06/29 03:23:18 locking release testing-secure
E  [kube] 2017/06/29 03:23:20 resources ready: false
E  [kube] 2017/06/29 03:23:22 resources ready: true
E  [tiller] 2017/06/29 03:23:22 executing 0 post-upgrade hooks for testing-secure
E  [tiller] 2017/06/29 03:23:22 hooks complete for post-upgrade testing-secure
E  [storage] 2017/06/29 03:23:22 updating release "testing-secure.v62"
E  [tiller] 2017/06/29 03:23:22 creating updated release for testing-secure
E  [storage] 2017/06/29 03:23:22 creating release "testing-secure.v63"
E  [storage] 2017/06/29 03:23:22 unlocking release testing-secure
E  [tiller] 2017/06/29 03:38:27 getting history for release testing-secure
E  [storage] 2017/06/29 03:38:27 getting release history for "testing-secure"
E  [storage] 2017/06/29 03:38:27 locking release testing-secure
E  [tiller] 2017/06/29 03:49:17 getting history for release testing.worker
E  [storage] 2017/06/29 03:49:17 getting release history for "testing.worker"
E  [storage] 2017/06/29 03:49:17 locking release testing.worker
E  [tiller] 2017/06/29 03:57:07 getting history for release testing-api
E  [storage] 2017/06/29 03:57:07 getting release history for "testing-api"
E  [storage] 2017/06/29 03:57:07 locking release testing-api
```

**Comment by eric4545** [comment] 2017-06-29 05:54
@thomastaylor312 seems not related.
Let me detail more
1. upgrade release `testing-secure`
2. upgrade `testing.worker` , after 5mins still no changes/ resource update in k8s.

**Comment by janssk1** [comment] 2017-07-04 12:48
I have similar issues with the locking mechanism. 

It becomes impossible the manage a release after someone does ctrl-c on helm while it is doing something (eg upgrading/installing/deleting) that has retrieved the lock. 

Example flow: 
* install a chart
* delete it
* helm delete taking a long time, got impatient and pressed ctrl-c 
* after that i'm not able to do anything anymore with the release.  All operations (delete/upgrade/..) are stuck on acquiring the lock.

**Comment by thomastaylor312** [comment] 2017-07-06 05:04
Sorry for the delay on this folks. I'll try duplicating this in the next few days. Thank you for the extra information

**Comment by technosophos** [comment] 2017-07-10 16:25
@janssk1 What lock is it waiting to acquire?

**Comment by rofc** [comment] 2017-07-12 19:22
Same behavior with, but no "--wait" used when upgrading (just a ``--values`` and a ``--set``).

``Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}``

``Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}``

**Comment by thomastaylor312** [comment] 2017-07-14 16:04
I am wondering if this is related to #2560. /cc @jascott1

**Comment by zjj2wry** [comment] 2017-07-21 02:15
i get same problem in delete my release. i restart my tiller solve it. 

my tiller log just return :
```
[storage] 2017/07/21 09:48:01 listing all releases with filter
```
k8s version:
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.2-dirty", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"dirty", BuildDate:"2017-05-02T10:28:22Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
helm version:
```
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"076ce0822ba55088863898e9640425902a09aaf5", GitTreeState:"clean"}
```

**Comment by yonnitempo** [comment] 2017-07-24 12:51
Hello,

I have a similar issue.

```
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}

Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

Tiller logs on hanging upgrade:
```
[tiller] 2017/07/24 11:22:23 getting history for release my-service-beta
[storage] 2017/07/24 11:22:23 getting release history for "my-service-beta"
[storage] 2017/07/24 11:22:23 locking release my-service-beta
```

I still cannot identify why this happens, but I was trying to upgrade the same chart on two different GKE 
Clusters:
```
helm upgrade --install my-service-beta stable/my-service/ --kube-context gke_service-myproject-west1-b_my-cluster --home /tmp/tmp.bPBzSHwrNH --dry-run --debug --wait --timeout 120 --values stable/my-service/my-cluster.yaml --set image.tag=1.4-2149
```
Note: `--wait --timeout` no longer works.

How can I get out of this state? Can I manually unlock a release?

**Comment by thomastaylor312** [comment] 2017-07-25 02:10
We just merged in a fix for #2560, can anyone having this issue see if the latest master fixes the issue?

**Comment by bacongobbler** [comment] 2017-07-25 04:03
Given that this appears to be the same area (release locks) I'm inclined to think this is a duplicate of #2560 and has indeed been fixed on master by my testing.

**Comment by thomastaylor312** [comment] 2017-07-26 04:30
Ok, I am good with that. Closing this issue as resolved. If there are still problems, please let us know

**Closed** 2017-07-26 04:30 UTC
Labels: question/support
