### ISSUE TITLE
Proposal: helm test to optionally show output of test commands

### ISSUE THREAD

**Issue by caseeker** [kubernetes/helm#2328] opened 2017-04-25 17:30 UTC
Helm test is simply showing if the test passed or failed.
To implement a deployment pipeline with helm, it will be very helpful to have test output visible when tests are failing.

At the moment, I am deploying with `helm upgrade --install` and run integration test with `kubectl run` command to see the output of the integration test.

Having `helm test` to show output of running tests will simplify the pipeline commands as it will solve the problem where `kubectl run` commands does not have an easy way to add some of the pod specs such as volume mounts and image pull policy.

Current workaround: `kubectl logs -f pod_name` upon test failure

**Comment by ahawkins** [comment] 2017-04-26 06:15
Confirm. I'm using a script to improve our `helm test` UX:

```
#!/usr/bin/env bash

set -euo pipefail

main() {
	local release="${1:-}"

	if [ -z "${release}" ]; then
		echo "USAGE: ${0} RELEASE" 1>&2
		return 1
	fi

	kubectl delete pod \
		-l "release=${release},app=smoke-test" \
		-n "${KUBE_NAMESPACE}" \
		--context "${KUBE_CONTEXT}" &> /dev/null

	if helm test "${release}" --kube-context "${KUBE_CONTEXT}"; then
		kubectl delete pod \
			-l "release=${release},app=smoke-test" \
			-n "${KUBE_NAMESPACE}" \
			--context "${KUBE_CONTEXT}" &> /dev/null

		return 0
	else
		echo "${release} test failed! Capturing logs and cleaning up"

		while read -r pod; do
			echo "${pod} Logs:"
			echo
			kubectl logs "${pod}" -n "${KUBE_NAMESPACE}" --context "${KUBE_CONTEXT}"
			kubectl delete pod "${pod}" -n "${KUBE_NAMESPACE}" --context "${KUBE_CONTEXT}"
			echo
		done < <(kubectl get pod \
			-o "custom-columns=NAME:.metadata.name" \
			-l "release=${release},app=smoke-test" \
			-n "${KUBE_NAMESPACE}" \
			--context "${KUBE_CONTEXT}" \
			| tail -n +2)

		return 1
	fi
}

main "$@"
```

**Comment by michelleN** [comment] 2017-04-27 22:16
yep. I'd really like to be able to stream pod logs on `helm test`

**Comment by michelleN** [comment] 2017-04-27 22:29
We should talk about what exactly this feature would look and feel like.

**Comment by michelleN** [comment] 2017-04-27 22:38
Actually, this is a duplicate of #1957 which is about adding a `--verbose` flag to the `helm test` command. I'll close this for now. Feel free to re-open if that's not what you're looking for.

**Closed by michelleN** 2017-04-27 22:38 UTC
Labels: feature, help wanted
