### ISSUE TITLE
Inject values during chart packaging

### ISSUE THREAD

**Issue by hmagph** [kubernetes/helm#3530] opened 2018-02-19 10:34 UTC
Helm provides elegant way to substitute values on the fly during install using --set arguments.
There is nothing equivalent during "helm package" operations.

Integrations with CI tools have to perform string replace operations to update built image information, when it could be made more clear using --set arguments.

Ask: provide --set arguments on "helm package" command to substitute chart variables (and likely other variant of this taking a file).

**Comment by bacongobbler** [comment] 2018-02-19 16:26
dupe of https://github.com/kubernetes/helm/issues/3141.

**Closed by bacongobbler** 2018-02-19 16:26 UTC
