### ISSUE TITLE
Error using repo add

### ISSUE THREAD

**Issue by raheelzubairy** [kubernetes/helm#2252] opened 2017-04-10 23:20 UTC
Running the following command on Windows 10. 
>helm repo add mb http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/microservicebuilder/helm/

Error: Looks like "http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/microservicebuilder/helm/" is not a valid chart repository or cannot be reached: open .helm\repository\cache\.helm\repository\cache\mb-index.yaml: The system cannot find the path specified.

**Comment by thomastaylor312** [comment] 2017-04-11 06:18
This may be related to #2254. Can you take a look at that issue (and related PR) @raheelzubairy and let me know if it looks like it might solve the issue?

**Comment by raheelzubairy** [comment] 2017-04-11 17:22
How would I see the change in the executable?  I am currently using the Windows binary file from here: https://github.com/kubernetes/helm/releases/tag/v2.3.0

Thanks!

**Comment by thomastaylor312** [comment] 2017-04-11 18:44
It has been merged into master, so you'd have to build from master. I don't think we put a canary build of helm anywhere

**Comment by raheelzubairy** [comment] 2017-04-12 20:46
Now I am having some issues with building.  After getting 'make' from here for windows: http://gnuwin32.sourceforge.net/packages.html

I am getting error when using the command 'make bootstrap build':
```
process_begin: CreateProcess(NULL, command -v glide;, ...) failed.
process_begin: CreateProcess(NULL, command -v gox;, ...) failed.
process_begin: CreateProcess(NULL, command -v git;, ...) failed.
The system cannot find the path specified.
'test' is not recognized as an internal or external command,
operable program or batch file.
makefile:111: *** You must install Git.  Stop.
```

I do have Git installed

**Comment by technosophos** [comment] 2017-04-12 22:50
If you have Docker, it might be easier to build in a container. /cc @mattfarina

**Comment by bacongobbler** [comment] 2017-06-14 22:09
looks like this is something that has been fixed in Helm v2.3.1 so it looks ready to close. We are *well* past v2.3.1 at this point. :)

**Comment by thomastaylor312** [comment] 2017-06-15 05:22
I'll go ahead and close this. Should this still be an issue, please let us know.

**Comment by dgoldssfo** [comment] 2017-08-07 17:16
Running helm 2.5.1 on Windows 10 Creators Edition aka Windows 10 Build 1703. . I am having a similar error:

PS C:\WINDOWS\system32> helm.exe repo add forgerock https://storage.googleapis.com/forgerock-charts
Error: Looks like "https://storage.googleapis.com/forgerock-charts" is not a valid chart repository or cannot be reached: open \.helm\repository\cache\.helm\repository\cache\forgerock-index.yaml: The system cannot find the path specified.

Same command works fine on Mac. 

I also tried running the command at the top of this thread and got the same error that raheelzubairy got. So it appears not fixed by #2254.

**Comment by dgoldssfo** [comment] 2017-08-07 17:35
BTW this is running in Administrator Windows PowerShell, which is where I ran helm.exe init. I don't see a .helm directory anywhere on my system, either in my $HOME directory or in c:\WIndows\System32 where I ran helm init.

**Comment by thomastaylor312** [comment] 2017-08-07 21:17
I'll have to give this a try on a windows machine unless there are other Helm users on Windows who may have ideas

**Comment by bacongobbler** [comment] 2017-08-08 17:53
I've been tossing around the idea of switching full-time over to a Windows dev environment so we can learn more about these issues for Helm so I might be able to take this on some time this week if I have free time. No promises though.

**Comment by dgoldssfo** [comment] 2017-08-08 18:00
Thanks! BTW I'm in the process of trying to port a deployment that is known to work on Mac/Linux VBox Minikube to Windows HyperV Minikube. I know next to nothing about Windows but will do my best to recreate issues.

**Comment by xiaogangwen** [comment] 2017-09-14 05:00
Actually more issues on Windows. I was able to workaround `helm repo add` by manipulating the file under c:\.helm but similar issue pops up when `helm repo update`. Sounds like there's still some distance to go to have helm fully working on Windows.

**Comment by thomastaylor312** [comment] 2017-09-14 16:05
@xiaogangwen I have to agree with that. Both @bacongobbler and I have had problems trying to get things working to even develop on Windows...

**Comment by bacongobbler** [comment] 2017-09-15 15:53
I have my hacked up MacBook Pro running Windows 10 up and running with minikube, helm and glide. I'll see if I can tackle this problem today.

**Comment by JohannesBertens** [comment] 2017-09-22 13:51
Doesn't seem to work on Windows 10 for me either.
Going to try it under Windows -> Bash as workaround

**Comment by bacongobbler** [comment] 2017-10-31 22:10
`helm repo add` failing on windows should be resolved with https://github.com/kubernetes/helm/pull/3024 so I'm going to close this as a duplicate of https://github.com/kubernetes/helm/issues/2071. If there are separate windows-related tickets, please open a new issue so we can triage and label it as such. Thanks!

**Closed by bacongobbler** 2017-10-31 22:10 UTC
Labels: question/support
