### ISSUE TITLE
Return resources as objects instead of one object of string type

### ISSUE THREAD

**Issue by pramodhkp** [kubernetes/helm#2579] opened 2017-06-15 05:57 UTC
Right now, `helm status` command returns something like this:

`{'time': '2017-06-13T13:18:52.317452346Z', 'status': 'DEPLOYED', 'description': 'Upgrade complete', 'resources': '==> v1/ConfigMap\nNAME                DATA      AGE\nonemore-configmap   0         1d\n\n==> v1/Service\nNAME      CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE\nonemore   10.43.114.234   <none>        8080/TCP   1d\n\n==> v1beta1/Deployment\nNAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE\nonemore   1         1         1            1           1d\n\n==> v1beta1/Ingress\nNAME      HOSTS                                    ADDRESS          PORTS     AGE\nonemore   something.devstack.india.endurance.com   172.23.150.224   80, 443   1d\n\n'}`

I guess we can modify the `status.proto` from  ` string resources = 3` to a deeper object maybe with each resource as different object, or it could be a list of objects of type resource. 

Can this be done?

**Comment by bacongobbler** [comment] 2017-06-15 06:17
The API must maintain backwards compatibility though v2.x. This could be done as a new endpoint, but not as a replacement.

**Comment by weiwei04** [comment] 2017-06-15 07:30
+1 for implement a new API to return a structured resources instead of string. We happens to wrap Tiller into our own system, if need some code side help I have some time to implement this new endpoint.

**Comment by pramodhkp** [comment] 2017-06-15 08:54
I have some time to commit to this as well. So, I can help implement/add anything required. It could be a starting point for me.

**Comment by pramodhkp** [comment] 2017-06-29 15:03
To maintain backward compatibility, how about adding a `-o yaml` flag, which when specified will return YAML instead of plain text?

**Comment by pramodhkp** [comment] 2017-06-29 15:05
How about adding a `-o yaml` to maintain backward compatibility for this?

**Comment by bacongobbler** [comment] 2017-11-01 00:13
Closing this as a duplicate of #1534 since that issue also asks about returning "structured output" for further post-processing.

**Closed by bacongobbler** 2017-11-01 00:13 UTC
Labels: question/support
