### ISSUE TITLE
Trunc wrong args

### ISSUE THREAD

**Issue by andrewhowdencom** [kubernetes/helm#1802] opened 2017-01-09 15:50 UTC
I'm getting a weird error, like 
```
`${CHART_PATH}/templates/_helpers.tpl:2:47: executing "name" at <trunc>: wrong number of args for trunc: want 2 got 1
```

It's intermittent; I don't know what causes it. I can lint the chart a bunch of times, and it sometimes happens on the root chart, sometimes on the dependency (always on one of them). 

_helpers.tpl

```
{{- define "name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 24 -}}
{{- end -}}

{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 24 -}}
{{- end -}}
```

I can't figure it out. Happens on both the most recent build (2.1.3, I think) and master.

**Comment by andrewhowdencom** [comment] 2017-01-09 15:54
lol appears to be based on where the variable is used. 
```
{{ template "fullname" . }}-app
```

**Comment by technosophos** [comment] 2017-01-09 20:36
It could happen if both arguments of `default` are `nil`, but that would be really strange, since .Chart.Name is a required field. `trunc` will definitely take an empty string as a second value, but I think the Go template engine may treat a `return nil` as if nothing was returned.

Lemme know if you can further narrow it down. Also, the particular error was originating from this line:

```
{{- default .Chart.Name .Values.nameOverride | trunc 24 -}}
```

Let me know if you ever see versions that are caused by the other line.

**Comment by andrewhowdencom** [comment] 2017-01-10 08:03
Will do. In the end, I copy pasted from another chart that works, but I will keep an eye out -- I think it's something wrong with my starter chart.

**Comment by technosophos** [comment] 2017-02-15 00:25
I'm going to close this one for now, but if you manage to reproduce it again, feel free to re-open.

**Closed by technosophos** 2017-02-15 00:25 UTC
Labels: support

**Comment by alexbrand** [comment] 2017-05-31 16:02
For the record, just ran into this and the issue was that I was using this helper in one of the templates but missing the `.` at the end. 

E.g.
```
{{ template "fullname" }}
```

instead of 
```
{{ template "fullname" . }}
```

**Comment by djhaskin987** [comment] 2018-02-28 22:16
There's avoiding footguns, and then there's violating least surprise. I had to grep the golang code to figure out why my "ReadWriteMany" directive is silently ignored. Perhaps a warning message or even a check to say, "Huh, you're specifying ReadWriteMany. That's not okay. Please specify ReadWriteOnce" and then an error is printed. Would be helpful :)
