### ISSUE TITLE
Allow to pass complex objects via --set

### ISSUE THREAD

**Issue by kenden** [kubernetes/helm#2226] opened 2017-04-06 16:51 UTC
We want to use the Chart aws-cluster-autoscaler at:
https://github.com/kubernetes/charts/tree/master/stable/aws-cluster-autoscaler

We would like to pass the autoscalingGroups[].name via the command line, using `--set`, and the other info via a file params.yaml:
```
autoscalingGroups:
- minSize: 2
  maxSize: 8
awsRegion: eu-west-1
```

When we try setting the autoscaling group name with:
```
$ helm upgrade cluster-autoscaler stable/aws-cluster-autoscaler -f params.yaml --set "autoscalingGroups[].name"="nodes.k8s.test.eu-west-1.aws.redacted.net"
```
But that doesn't work.

Reading the [documentation](https://github.com/kubernetes/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set), this is known, but it would still be nice to be able to do this.

**Comment by thomastaylor312** [comment] 2017-04-07 06:26
@kenden Thanks for opening this. It has definitely been discussed before. This is a duplicate of #2058, so I am going to close this, but please feel free to follow/comment in the other issue

**Closed by thomastaylor312** 2017-04-07 06:26 UTC
Labels: duplicate

**Comment by kenden** [comment] 2017-10-17 16:31
(Now possible in helm 2.5)
