### ISSUE TITLE
Helm list Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 127.0.0.1:8080: connect: connection refused

### ISSUE THREAD

**Issue by fossxplorer** [kubernetes/helm#3870] opened 2018-04-11 13:46 UTC
Output of `helm version`:
[ kubespray]$ helm version
Client: &version.Version{SemVer:"v2.9.0-rc3", GitCommit:"60abcdca41f544caaecb224acbfb92aee11e1f6e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0-rc3", GitCommit:"60abcdca41f544caaecb224acbfb92aee11e1f6e", GitTreeState:"clean"}
Output of `kubectl version`:
[ kubespray]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  OpenStack

[ kubespray]$ helm version
Client: &version.Version{SemVer:"v2.9.0-rc3", GitCommit:"60abcdca41f544caaecb224acbfb92aee11e1f6e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0-rc3", GitCommit:"60abcdca41f544caaecb224acbfb92aee11e1f6e", GitTreeState:"clean"}
[kubespray]$ helm list
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 127.0.0.1:8080: connect: connection refused
[ kubespray]$ kubectl --namespace=kube-system get all -o wide |grep tiller
tiller-deploy-686c785c58-44g8m                         1/1       Running   0          1h        10.233.66.6     glenna2-test-k8s-node-nf-1

tiller-deploy          ClusterIP   10.233.14.238   <none>        44134/TCP       1h        app=helm,name=tiller

tiller-deploy          1         1         1            1           1h        tiller                    gcr.io/kubernetes-helm/tiller:v2.9.0-rc3                                                                                                                                   app=helm,name=tiller

tiller-deploy-686c785c58          1         1         1         1h        tiller                    gcr.io/kubernetes-helm/tiller:v2.9.0-rc3                                                                                                                                   app=helm,name=tiller,pod-template-hash=2427341714

tiller-deploy          1         1         1            1           1h        tiller                    gcr.io/kubernetes-helm/tiller:v2.9.0-rc3                                                                                                                                   app=helm,name=tiller

tiller-deploy-686c785c58          1         1         1         1h        tiller                    gcr.io/kubernetes-helm/tiller:v2.9.0-rc3                                                                                                                                   app=helm,name=tiller,pod-template-hash=2427341714

I've been searching  alot about this issue, but could not find any solution.

**Comment by bacongobbler** [comment] 2018-04-11 22:35
dupe of https://github.com/kubernetes/helm/issues/2464

**Closed by bacongobbler** 2018-04-11 22:35 UTC

**Comment by rcsavage** [comment] 2018-12-04 13:17
I am seeing this behavior when I converted my cluster from Weave Net to Flannel.

**Comment by grajeshwaran** [comment] 2019-11-22 11:56
I encountered this problem in 2019 and was lucky to just upgrade helm to version 3 which does not require tiller anymore.

**Comment by onedr0p** [comment] 2019-12-05 00:51
This solved it for me

```bash
update-alternatives --set iptables /usr/sbin/iptables-legacy
```

**Comment by mor-anshuman** [comment] 2020-03-12 16:48
I used below to flush all the firewall rules and it worked for me, you can flush the specific rule also
`iptables -F`
