### ISSUE TITLE
Feature request: `helm outdated` command to find installed charts with available update

### ISSUE THREAD

**Issue by fhemberger** [kubernetes/helm#2604] opened 2017-06-21 13:27 UTC
Not sure if I haven't found it yet, but it would be nice to have a command showing all installed charts, where there's an update available, e.g.

```sh
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "incubator" chart repository
Update Complete. ⎈ Happy Helming!⎈


$ helm list
NAME           	REVISION	UPDATED                 	STATUS  	CHART                   	NAMESPACE
my-jenkins     	1       	Thu Jun 15 17:51:47 2017	DEPLOYED	jenkins-0.7.3           	default
my-ingress     	1       	Mon May 15 14:48:37 2017	DEPLOYED	nginx-ingress-0.4.2     	default


$ helm outdated
NAME           	CHART              	VERSION     	AVAILABLE       	CHANGELOG
my-ingress     	nginx-ingress      	0.4.2       	0.5.0           	https://charts.k8s.io/stable/nginx-ingress/CHANGELOG.md
```

(Additional bonus points for a command like `helm upgrade --outdated` to upgrade all charts in a cluster)

**Comment by michelleN** [comment] 2017-06-21 17:00
I think this would make for a really useful plugin. Where would you check in the release for the source repository of the chart? The repo commands are client side so I'm curious how the mapping would work between the source of the chart installed and the repositories associated with your helm client.

**Comment by bacongobbler** [comment] 2017-06-21 17:11
I have a work-in-progress plugin called [helm-whatup](https://github.com/bacongobbler/helm-whatup) that does exactly as proposed here.

**Comment by fhemberger** [comment] 2017-06-21 18:16
@michelleN Hmm, do I understand you correctly that after installation, there's no correlation between e.g. installed `nginx-ingress-0.4.2` and the source `stable/nginx-ingress` anywhere?

@bacongobbler Awesome, I'll have a look at it!

**Comment by fuhbar** [comment] 2017-06-25 21:48
Very nice! Just stumbled over this issue, right before trying to implement this very same feature by myself. Thanks @bacongobbler for your efforts! Looking forward to a working release. :)

**Comment by bacongobbler** [comment] 2017-11-01 00:21
closing as a duplicate of #1079.

**Closed by bacongobbler** 2017-11-01 00:21 UTC
Labels: plugin

**Comment by bacongobbler** [comment] 2018-02-09 00:28
FYI I finally got some time to work on this plugin. You can install it via `helm plugin install https://github.com/bacongobbler/helm-whatup`. Let me know how it works. :) Thanks!
