### ISSUE TITLE
The relationship between "helm lint" and "helm install"

### ISSUE THREAD

**Issue by shuqilou** [kubernetes/helm#2202] opened 2017-03-30 04:16 UTC
Hi ,guys
    I meet a situation which makes me confused recently.
    I make a wrong package _hello-0.1.0.tgz_ on purpose. When I run "helm lint", it returns failure that "misssing Chart.yaml"

    SHA1000121535:~/lsq # helm lint hello-0.1.0.tgz 
    ==> Skipping hello-0.1.0.tgz
    No chart found for linting (missing Chart.yaml)

    0 chart(s) linted, no failures

but when I still run "helm install", it can be deployed successfully.

    SHA1000121535:~/lsq # helm install hello-0.1.0.tgz --host=localhost:44134
    NAME:   jaunty-ragdoll
    LAST DEPLOYED: Thu Mar 30 20:53:40 2017
    NAMESPACE: default
    STATUS: DEPLOYED

    RESOURCES:
    ==> v1/Service
    NAME                   CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
    jaunty-ragdoll-hello   10.247.6.52   <none>        30009/TCP   0s

    ==> extensions/Deployment
    NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
    jaunty-ragdoll-hello   1         0         0            0           0s

    NOTES:
    MySQL can be accessed via port 3306 on the following DNS name from within your cluster:
    jaunty-ragdoll-hello.default.svc.cluster.local

    To get your root password run:

    printf $(printf '\%o' `kubectl get secret --namespace default jaunty-ragdoll-hello -o jsonpath="{.data.mysql-root-password[*]}"`);echo

    To connect to your database:

    1. Run an Ubuntu pod that you can use as a client:

        kubectl run -i --tty ubuntu --image=ubuntu:16.04 --restart=Never -- bash -il

    2. Install the mysql client:

        $ apt-get update && apt-get install mysql-client -y

    3. Connect using the mysql cli, then provide your password:
        $ mysql -h jaunty-ragdoll-hello -p

and the release created is as follows:

    SHA1000121535:~/lsq # helm list --host=localhost:44134
    NAME          	REVISION	UPDATED                 	STATUS  	CHART      
    jaunty-ragdoll	1       	Thu Mar 30 20:53:40 2017	DEPLOYED	hello-0.1.0

I just can't understand the logic that the release can be created in the case of failure lint validation. Normally, when validator failes, the next step can not be executed or throws error to the user. Could anybody help me to explain the relationship between  "helm lint" and "helm install"? Thx!

**Comment by shuqilou** [comment] 2017-03-30 06:41
If I add --verify=true, it would not install and throw out the error:

    SHA1000121535:~/lsq # helm install hello-0.1.0.tgz --host=localhost:44134 --verify=true
    Error: could not load provenance file /root/lsq/hello-0.1.0.tgz.prov: stat /root/lsq/hello-0.1.0.tgz.prov: no such file or directory

So we can choose whether to check！

**Comment by thomastaylor312** [comment] 2017-04-07 07:04
@shuqilou: `helm lint` is meant to be run on a non compressed chart while developing it. As for verification, it will always fail unless you sign it as described [here](https://github.com/kubernetes/helm/blob/master/docs/provenance.md)

**Comment by bacongobbler** [comment] 2017-10-31 21:39
closing as a wontfix since this is working as intended. If you want to lint a chart, it needs to be uncompressed and on the local filesystem. It's not intended to be used on packaged charts that (should) have already gone through the linting process.

**Closed by bacongobbler** 2017-10-31 21:39 UTC
Labels: question/support
