### ISSUE TITLE
Add an annotation to keep resources around after "helm delete"

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes/helm#1326] opened 2016-10-10 21:07 UTC
In helm classic there was an annotation "helm-keep" that allowed chart admins to mark a resource to be kept around even after a release was deleted.

We should add this back.

An example use case is when users create PVCs for databases and want them to be kept around for manual inspection/deletion after the helm release is deleted.

**Comment by technosophos** [comment] 2016-10-10 22:09
I'd prefer something like a `helm.sh/resource-policy: keep` sort of syntax, based on @viglesiasce 's suggestion in Slack. Are there other states we know we want for sure?

**Comment by aegixx** [comment] 2016-11-22 18:55
Based on what I'm seeing in `2.0.0`, PVCs are already being left automatically when `helm delete` is ran.  I'm actually looking for a built-in mechanism for removing them when the release is destroyed.

**Comment by michelleN** [comment] 2016-12-06 14:19
@aegixx I could not reproduce that behavior. What version of kubernetes are you on? Are you still seeing that behavior?


If we "keep" a resource, does that mean the release still exists? Do we detach the release from the resources at that point? 
What should happen if there is a keep annotation but the purge flag is added to the delete command?

**Comment by michelleN** [comment] 2016-12-06 14:22
Should the `helm status` output of a deleted release show the resources that are left and their statuses?

**Comment by michelleN** [comment] 2016-12-06 14:43
What (if any) kind of feedback should the `helm delete` command give to the user if resources are being kept?

**Comment by technosophos** [comment] 2016-12-13 00:31
Closed by #1652

**Closed** 2016-12-13 00:31 UTC
