### ISSUE TITLE
Intermittent `x509: certificate signed by unknown authority` error

### ISSUE THREAD

**Issue by munnerz** [kubernetes/helm#1749] opened 2016-12-22 18:50 UTC
Hi there

I'm occasionally receiving the following error when running `helm repo update` - probably 1/5 times? It's a big issue for us as we're automating the installation/upgrade of a number of charts.

I have also seen x509 cert errors when running `helm install` occasionally. This doesn't seem to be specific to the GCS bucket from stable, although I'll try and find some command outputs to post here showing this.

I'm unsure what's causing the issue here - does `helm repo update` run client-side, or on tiller?

```
➜  gke-infra-dm git:(master) ✗ helm --debug repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com/):
	Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: certificate signed by unknown authority
Update Complete. ⎈ Happy Helming!⎈
```

**Comment by technosophos** [comment] 2016-12-23 19:32
I have seen this happen on rare occasion, too. It seems that perhaps one of the Google certs is signed with the wrong CA. @viglesiasce Is this something you can check on?

**Comment by technosophos** [comment] 2017-01-04 17:00
Is this still happening? I'm hoping the bad server got fixed or flushed from rotation.

**Comment by vpetersson** [comment] 2017-01-07 15:56
I can confirm that this is still happening for me.

**Comment by vpetersson** [comment] 2017-01-07 16:01
Another interesting observation:

```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com/):
        Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: certificate signed by unknown authority
...Unable to get an update from the "deis" chart repository (https://charts.deis.com/workflow):
        Get https://charts.deis.com/workflow/index.yaml: x509: certificate signed by unknown authority
Update Complete. ⎈ Happy Helming!⎈
```

I'm getting the error here. 

However, I'm unable to reproduce this with `curl`:

```
$ helm --debug  repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com/):
        Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: certificate signed by unknown authority
...Unable to get an update from the "deis" chart repository (https://charts.deis.com/workflow):
        Get https://charts.deis.com/workflow/index.yaml: x509: certificate signed by unknown authority
Update Complete. ⎈ Happy Helming!⎈
➜  Documents curl -I https://charts.deis.com/workflow/index.yaml
HTTP/1.1 200 OK
Content-Type: binary/octet-stream
Content-Length: 1959
Connection: keep-alive
Date: Sat, 07 Jan 2017 16:00:01 GMT
Last-Modified: Fri, 06 Jan 2017 19:03:11 GMT
ETag: "2429044dc98b5bec93ce34b0956d78c7"
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 e00584961bd0e81cd2b5bf84f9ffe964.cloudfront.net (CloudFront)
X-Amz-Cf-Id: RfAz3sLdl8CflDXSr40RRTlBBViTdXxQKlCN2llMjQFxqpmqQmN5NA==
```

**Comment by munnerz** [comment] 2017-01-09 09:37
Oddly I am also getting this error with kubectl when doing a simple `get pods`. It seems to be with googles `accounts.google.com` URL.

It's intermittent and performing the same command straight after returns fine.

**Comment by munnerz** [comment] 2017-01-09 09:39
FWIW, I'm running:

* Mac OS X 10.12.1
* kubectl:
`Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-22T13:56:59Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}`
* helm: `Client: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}`

All of the examples I've posted are run against a GKE cluster.

**Comment by technosophos** [comment] 2017-01-09 17:18
@viglesiasce Any insight into this?

**Comment by vpetersson** [comment] 2017-01-14 21:25
I think I have a lead on this one. It started to happen to me for `kubectl` today as well after upgrading `gcloud`.  As it turns out, it turns out that the issue only happens with the version shipped by Google with `gcloud`, not with the one from Brew.

```
$ which kubectl
/Users/mvip/google-cloud-sdk/bin/kubectl
$ kubectl get pods
Unable to connect to the server: Post https://accounts.google.com/o/oauth2/token: x509: certificate signed by unknown authority
```

Now, let's instead use the version from `brew`:

```
$ /usr/local/bin/kubectl get pods
[...]
```

Voila. 

This leads me to believe that it has something to do with Go and/or how it is compiled on macOS.

**Comment by cblecker** [comment] 2017-01-14 21:55
This sounds extremely similar to:
golang/go#18141
golang/go#18203

The upstream fix to go1.7.4 was patched into the go1.7.4 distributed with Homebrew [here](https://github.com/Homebrew/homebrew-core/pull/8628), and then kubectl was recompiled from source using that version [here](https://github.com/Homebrew/homebrew-core/pull/7845) with the release of Kubernetes 1.5.2.

I'm going to bump the revision number of helm in Homebrew, and that may resolve this intermittent problem.

**Comment by cblecker** [comment] 2017-01-15 07:12
@munnerz vpetersson --
I'm not sure if you're already using the version of kubectl/helm from [Homebrew](http://brew.sh/) or not, but you may wish to try it as it's been compiled with a version of go1.7.4 with the upstream fix. If this fixes the issue, then we have likely identified root cause.

```
brew install kubernetes-cli kubernetes-helm
```

**Comment by vpetersson** [comment] 2017-01-15 09:34
@cblecker I'm actually using the brew version of Helm right now. This is likely what solved my issue a few days (ran a `brew upgrade` to fix something else). 

As of right now, I'm unable to reproduce the issue with either `helm` or `kubectl`.

**Comment by munnerz** [comment] 2017-01-16 09:10
@vpetersson 

excellent - I am in fact using the gcloud version (and was until recently using the Helm version too!).

I've just switched back to the Homebrew version and hopefully all shall be resolved.

**Comment by jasonroelofs** [comment] 2017-01-17 13:52
I'd like to add another confirmation that using the Homebrew build of `kubectl` fixes this problem over the Google SDK version.

```
] kubectl get pods
Unable to connect to the server: Post https://accounts.google.com/o/oauth2/token: x509: certificate signed by unknown authority

] /usr/local/bin/kubectl get pods
NAME                           READY     STATUS    RESTARTS   AGE
...
```

Which must write new credentials because after running the Homebrew version, the Google SDK version now works again.

**Comment by technosophos** [comment] 2017-01-26 23:20
It looks like this was fixed in upstream Go. I'm marking this as closed.

**Closed by technosophos** 2017-01-26 23:20 UTC
Labels: support
