### ISSUE TITLE
Helm verification seems to choke with gpg2 or yubikeys

### ISSUE THREAD

**Issue by andrewhowdencom** [kubernetes/helm#1592] opened 2016-11-27 13:36 UTC
A similar issue seems to be here: https://github.com/keybase/keybase-issues/issues/1885

```
$ helm verify --keyring ${HOME}/.gnupg/pubring.kbx mysql-0.2.1.tgz
Error: failed to load keyring: openpgp: invalid data: tag byte does not have MSB set
```

```
$ helm package --sign --key="hello@myemailaddress.com" --keyring /home/ahowden/.gnupg/pubring.kbx mysqlError: openpgp: invalid data: tag byte does not have MSB set
```

As a heads up also, the keyring for gpg2 also seems to have been moved.

This issue is a little hard to track down, as I don't have a private key that *isn't* on the yubikey.

Possibly related: #1475

**Comment by technosophos** [comment] 2016-11-29 18:06
I spent a lot of time with @vdice tracking this down a while back. We didn't find a good solution. I think we ended up doing some export/import cycle a few times or something like that.

With the plugin stuff, I am starting to think that maybe stand-alone sign/verify plugins may be better. I wrote one for Keybase yesterday, and it was much nicer to just take advantage of the native tooling instead of working with Go's PGP implementation.

I'll post a link to the plugin (which can be used stand-alone) when I create a repo for it.

If I can figure out the keyring support, at least some of these issues should be resolved. But I'm not sure it will be a cure-all.

**Comment by andrewhowdencom** [comment] 2016-11-30 08:06
That seems reasonable. The only issue I can foresee is that one person signs with one plugin, and another verifies with another plugin we might end up with the same issue, but with the additional complexity of multiple plugins. 

That being said, if there's one "defacto" plugin maintained by someone else (such as keybase) that works consistently, that's awesome.

I appreciate your work though! Helm is now my preferred method of constructing k8s projects.

**Comment by technosophos** [comment] 2016-11-30 16:43
My intent was to preserve the OpenPGP style signing. So you can use any implementation of PGP to sign and to verify. My test case was to sign with Keybase and verify with GPG and Helm.

Mainly, the issue is that if we want to support the more sophisticated aspects of tools like GnuPG or Keybase, we either have to write a ton of Go code (and probably fork Go's OpenPGP library), or figure out a clever way to expose those tools. Plugins might be the way to expose those tools.

That said, I will probably try to finish the gpg-agent PR simply because that gets us several wins for the default implementation.

**Comment by technosophos** [comment] 2016-12-05 18:50
Over the weekend, I wrote a `helm gpg` plugin just to test out some of the ideas here. https://github.com/technosophos/helm-plugins

It's not great, but it does allow you to use a lot more of the native GnuPG features. I'm going to keep working on this idea as we move toward the Helm 2.1.0 release.

**Comment by andrewhowdencom** [comment] 2016-12-06 07:45
Awesome! I love the plugin structure also. The plugin doesn't work for me at the minute (a missing function and changed signatures); if I get time today I'll find a reasonable common ground and get a pull request in.

**Comment by technosophos** [comment] 2016-12-19 21:22
Did you have any luck with the plugin? I updated once (I think) after you filed this issue.

**Comment by technosophos** [comment] 2017-01-11 18:18
I'm marking this as closed, since I think the plugin is the intended destination for this feature.

**Closed by technosophos** 2017-01-11 18:18 UTC
Labels: support

**Comment by andrewhowdencom** [comment] 2017-01-12 13:23
Sorry man! I haven't had a chance to look at this. I'm dropping a bunch of my obligations at the minute, as some higher prio stuff has taken all my time. FWIW, no, it doesn't work: 

```
$ helm gpg sign prometheus-0.1.4.tgz 
+ [[ 2 < 1 ]]
+ type gpg
+ case "${1:-"help"}" in
+ :
+ [[ 2 < 2 ]]
+ shift
+ keyname=
+ '[' prometheus-0.1.4.tgz '!=' '' ']'
+ case $1 in
+ break
+ sign prometheus-0.1.4.tgz
+ is_help prometheus-0.1.4.tgz
+ case "$1" in
+ return 1
+ chart=prometheus-0.1.4.tgz
+ echo 'Signing prometheus-0.1.4.tgz'
Signing prometheus-0.1.4.tgz
++ openssl sha -sha256 prometheus-0.1.4.tgz
++ awk '{ print $2 }'
Invalid command 'sha'; type "help" for a list.
+ shasum=
++ tar -zxf prometheus-0.1.4.tgz --exclude charts/ -O '*/Chart.yaml'
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: */Chart.yaml: Not found in archive
tar: Exiting with failure status due to previous errors
+ chartyaml=
Error: plugin "gpg" exited with error
```

```
$ gpg --version
gpg (GnuPG) 2.1.17
libgcrypt 1.7.5-beta
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/${PLACEHOLDER}/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512,
```

```
$ openssl version
OpenSSL 1.1.0c  10 Nov 2016
```

```
$ tar --version
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```

```
$ sudo hostnamectl
   Static hostname: ${PLACEHOLDER}
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: ${PLACEHOLDER}
           Boot ID: ${PLACEHOLDER}
  Operating System: Debian GNU/Linux stretch/sid
            Kernel: Linux 4.8.0-2-amd64
      Architecture: x86-64
```

"Managing Expectations" -- I'm not going to be able to look at this much further. If I get to use this in prod, I'll modify the script so it works for me and submit a pull.

**Comment by jedcunningham** [comment] 2022-01-10 23:56
For visitors landing here via search, the [Helm GnuPG plugin](https://github.com/technosophos/helm-gpg) @technosophos [commented about](https://github.com/helm/helm/issues/1592#issuecomment-264940950) did work for me 👍
