### ISSUE TITLE
helm upgrade requires deleting failed installs

### ISSUE THREAD

**Issue by bmperrea** [kubernetes/helm#3415] opened 2018-01-29 15:07 UTC
I have been regularly using `helm upgrade -i --wait` to either install or upgrade a deployment - and it's great!

But, I often end up in a state where I have to delete a failed release before I can run this command again. For instance, when I start up a series of these commands on a fresh env (e.g. a local one) it can fail midway either because I kill it, or it dies, or an error like #3409. My current work around to make it more idempotent is to check for the error message below, and then call `helm del --purge` on the failed release before doing `helm upgrade -i` again.

```
Error: UPGRADE FAILED: "local-gold-shared-data-stack" has no deployed releases
$ helm ls
NAME                            REVISION    UPDATED                     STATUS    CHART                      NAMESPACE
local-gold-shared-data-stack    1           Sat Jan 27 14:03:19 2018    FAILED    shared-data-stack-1.0.3    local-gold-shared-data-stack
``` 

It looks like `helm upgrade -i` uses install when the chart is not there, and otherwise does an upgrade. My issue seems to appear when it fails on an install, and then the next time I run `helm upgrade -i` it follows the upgrade path but fails because there are no successful releases, hence the error message above. I hope to go poking around in the code to see what I can do, but any guidance on this issue would be appreciated.

**Comment by andreychernih** [comment] 2018-01-31 01:19
That affects me as well. I am getting the same error with Helm v2.7.2

**Comment by Nowaker** [comment] 2018-01-31 01:24
I've been encountering the same issue too. Version 2.8.0.

**Comment by bmperrea** [comment] 2018-01-31 20:14
Thanks @jascott1 for adding the label. I would call this a feature request. The feature would be that `helm upgrade -i` be idempotent even against Failed releases for at least some combination of arguments.

**Comment by bacongobbler** [comment] 2018-01-31 20:23
Closing as a duplicate of #3353.

**Closed by bacongobbler** 2018-01-31 20:23 UTC
Labels: question/support
