### ISSUE TITLE
Tiller doesnt starts inside kubernetes cluster

### ISSUE THREAD

**Issue by sashgorokhov** [kubernetes/helm#1504] opened 2016-11-03 11:57 UTC
`helm version` says `Client: &version.Version{SemVer:"v2.0.0-rc.1", GitCommit:"92be174acf51e60a33287fb7011f4571eaa5cb98", GitTreeState:"clean"}`

Just made `helm init`, and tiller has gone in crashloop. 
```
$ kubectl get po

NAME                                           READY     STATUS             RESTARTS   AGE
tiller-deploy-351466555-5rs9v                  0/1       CrashLoopBackOff   25         57m
```
`kubectl logs tiller-deploy-351466555-5rs9v` shows nothing.
```
$ kubectl describe po/tiller-deploy-351466555-5rs9v

Name:           tiller-deploy-351466555-5rs9v
Namespace:      kube-system
Node:           node3/10.0.2.15
Start Time:     Thu, 03 Nov 2016 10:47:45 +0000
Labels:         app=helm
                name=tiller
                pod-template-hash=351466555
Status:         Running
IP:             18.16.96.2
Controllers:    ReplicaSet/tiller-deploy-351466555
Containers:
  tiller:
    Container ID:       docker://4559420e6ae1a0056c6c742e554ee8560d854b5e9740052501c009859c4eff52
    Image:              gcr.io/kubernetes-helm/tiller:v2.0.0-rc.1
    Image ID:           docker://sha256:56ec16141caa81ebdfaa4d6712c879004afdddf0d704d687aa216a0480c34dd6
    Port:               44134/TCP
    State:              Waiting
      Reason:           CrashLoopBackOff
    Last State:         Terminated
      Reason:           Error
      Exit Code:        2
      Started:          Thu, 03 Nov 2016 11:49:37 +0000
      Finished:         Thu, 03 Nov 2016 11:49:45 +0000
    Ready:              False
    Restart Count:      27
    Liveness:           http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:          http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mp5jg (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True 
  Ready         False 
  PodScheduled  True 
Volumes:
  default-token-mp5jg:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-mp5jg
QoS Class:      BestEffort
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From            SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----            -------------   --------        ------          -------
  1h            59m             8       {kubelet node3}                 Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=tiller pod=tiller-deploy-351466555-5rs9v_kube-system(f459154b-a1b2-11e6-a6aa-022e63516e2d)"

  59m   59m     1       {kubelet node3} spec.containers{tiller} Normal  Created         Created container with docker id 7abbc724c954; Security:[seccomp=unconfined]
  59m   59m     1       {kubelet node3} spec.containers{tiller} Normal  Started         Started container with docker id 7abbc724c954
  59m   59m     1       {kubelet node3} spec.containers{tiller} Normal  Killing         Killing container with docker id 7abbc724c954: pod "tiller-deploy-351466555-5rs9v_kube-system(f459154b-a1b2-11e6-a6aa-022e63516e2d)" container "tiller" is unhealthy, it will be killed and re-created.
  59m   57m     14      {kubelet node3}                         Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=tiller pod=tiller-deploy-351466555-5rs9v_kube-system(f459154b-a1b2-11e6-a6aa-022e63516e2d)"

  56m   56m     1       {kubelet node3} spec.containers{tiller} Normal  Created         Created container with docker id 8ac58007c3c4; Security:[seccomp=unconfined]
  56m   56m     1       {kubelet node3} spec.containers{tiller} Normal  Started         Started container with docker id 8ac58007c3c4
  56m   56m     1       {kubelet node3} spec.containers{tiller} Normal  Killing         Killing container with docker id 8ac58007c3c4: pod "tiller-deploy-351466555-5rs9v_kube-system(f459154b-a1b2-11e6-a6aa-022e63516e2d)" container "tiller" is unhealthy, it will be killed and re-created.
  51m   51m     1       {kubelet node3} spec.containers{tiller} Normal  Started         Started container with docker id 7f2656abdf88
  51m   51m     1       {kubelet node3} spec.containers{tiller} Normal  Created         Created container with docker id 7f2656abdf88; Security:[seccomp=unconfined]
  51m   51m     1       {kubelet node3} spec.containers{tiller} Normal  Killing         Killing container with docker id 7f2656abdf88: pod "tiller-deploy-351466555-5rs9v_kube-system(f459154b-a1b2-11e6-a6aa-022e63516e2d)" container "tiller" is unhealthy, it will be killed and re-created.
  1h    2m      28      {kubelet node3} spec.containers{tiller} Normal  Pulling         pulling image "gcr.io/kubernetes-helm/tiller:v2.0.0-rc.1"
  51m   2m      19      {kubelet node3} spec.containers{tiller} Normal  Started         (events with common reason combined)
  1h    2m      28      {kubelet node3} spec.containers{tiller} Normal  Pulled          Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.0.0-rc.1"
  51m   2m      19      {kubelet node3} spec.containers{tiller} Normal  Created         (events with common reason combined)
  51m   2m      19      {kubelet node3} spec.containers{tiller} Normal  Killing         (events with common reason combined)
  1h    2m      30      {kubelet node3} spec.containers{tiller} Warning Unhealthy       Readiness probe failed: Get http://18.16.96.2:44135/readiness: dial tcp 18.16.96.2:44135: getsockopt: connection refused
  1h    2m      30      {kubelet node3} spec.containers{tiller} Warning Unhealthy       Liveness probe failed: Get http://18.16.96.2:44135/liveness: dial tcp 18.16.96.2:44135: getsockopt: connection refused
  1h    10s     280     {kubelet node3} spec.containers{tiller} Warning BackOff         Back-off restarting failed docker container
  56m   10s     251     {kubelet node3}                         Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "tiller" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=tiller pod=tiller-deploy-351466555-5rs9v_kube-system(f459154b-a1b2-11e6-a6aa-022e63516e2d)"
```

How can I debug tiller?

**Comment by technosophos** [comment] 2016-11-03 16:31
Can you tell me about your Kubernetes cluster (version, distribution)? We'll look into this.

**Comment by sashgorokhov** [comment] 2016-11-04 15:50
@technosophos I am using kubernetes 1.4.5 from official repo, and created local cluster with vagrant manually. Here is my repo: https://github.com/sashgorokhov/kubernetes-training/tree/systemd-configs

It is worth noting that several addons are working on my cluster, such as DNS, Dashboard, and Heapster. They works just fine. Maybe the problem with my cluster configuration?

Configs: [kubelet (master)](https://github.com/sashgorokhov/kubernetes-training/blob/systemd-configs/puppet/modules/systemd/files/kubelet-master), [kubelet[node]](https://github.com/sashgorokhov/kubernetes-training/blob/systemd-configs/puppet/modules/systemd/files/kubelet-node), [apiserver](https://github.com/sashgorokhov/kubernetes-training/blob/systemd-configs/kubernetes/manifests/master/kube-apiserver.yaml)

**Comment by sputnick** [comment] 2016-11-11 07:46
@technosophos I'm also having issues with rc.2 in a container/pod. Helm init doesn't work - fails on deploying Tiller because it cannot contact k8s api server. If I manually setup a tiller it complains about not being authenticated.  I downgraded to beta.2 and it works again.

**Comment by technosophos** [comment] 2016-11-15 20:31
I've reproduced this in the case where the Kubernetes API server could not be contacted. I've had to doctor my environment, but what I would suggest is trying to `kube exec` into the Tiller pod, and see what address the KUBE_API environment variables are pointed to. Is it the right address for the actually Kubernetes API server?

**Comment by sputnick** [comment] 2016-11-15 23:00
@technosophos I think the only thing to improve in Helm is just the error message to indicate the cluster is wonky. It turned out that what I was hitting was a rather major bug with that version of kube-solo where the cluster got messed up on restart. Fixed now by the great devs at kube-solo :)
https://github.com/TheNewNormal/kube-solo-osx/issues/154

**Closed** 2016-12-05 19:17 UTC
Labels: support
