### ISSUE TITLE
output lists/tables as json/yaml/etc

### ISSUE THREAD

**Issue by helgi** [kubernetes/helm#2504] opened 2017-05-26 03:42 UTC
Would be good to have the ability to output tables (helm ls, dep, release and others) as `json`, potentially `yaml` and other formats. This would greatly simplify automations (especially with `jq`).

**Comment by h0tbird** [comment] 2017-05-29 15:09
Also with `helm get values`. Super useful for me too!

**Comment by philipbjorge** [comment] 2017-06-29 15:57
This would also be very useful to me -- I can write automation in any language I like, rather than go.
I think yaml would be the best format since it's consistent with the kubernetes/helm community at large.

**Comment by bacongobbler** [comment] 2017-10-31 23:41
closing as a duplicate of https://github.com/kubernetes/helm/issues/1534

**Closed by bacongobbler** 2017-10-31 23:41 UTC
Labels: proposal
