### ISSUE TITLE
helm search --regex case sensitivity

### ISSUE THREAD

**Issue by TerraTech** [kubernetes/helm#2865] opened 2017-08-26 10:27 UTC
helm/tiller version 2.5.1

I had added a couple repos:
$ helm repo add helmDevel http://example.com/devel
$ helm repo add helmStable http://example.com/stable

However doing various searches:
```works``` $ helm search helmDevel
```works``` $ helm search helmStable
```works``` $ helm search --regex 'helm'
```fails``` $ helm search --regex 'helmDevel'
```fails``` $ helm search --regex 'helmStable'
```fails``` $ helm search --regex 'helm[DS]'

Since the first three work, that leads me to believe there is a problem with how regex is handling mixed casing.

**Comment by jascott1** [comment] 2017-08-28 21:43
I have confirmed that `helm search --regexp helmUpper` returns no results but `helm search --regexp helm[Uu]pper` and `helm search --regexp helmupper` work as expected.

Marking this as a bug because the UX is confusing. User will see the mixed case repo name but cannot search for it by upper case and regex.

**Comment by rocky-nupt** [comment] 2017-08-31 02:17
I find the man who wrote code here was to ignore all the capital letters and helm search [--regexp] only uses lowercase letters. I upload a PR about case sensitive. Whether to merge is up to you. @jascott1

**Closed** 2017-09-28 10:37 UTC
Labels: bug, question/support
