### ISSUE TITLE
Print diffs when upgrade fails for validation reasons

### ISSUE THREAD

**Issue by unguiculus** [kubernetes/helm#1781] opened 2017-01-04 08:30 UTC
I'm trying out `incubator/mongodb-replicaset`. It works quite nicely so far. I installed it successfully. I then made changes to the ConfigMap containing the `mongod.conf` and tried to upgrade the chart. The result was this:

> Error: UPGRADE FAILED: StatefulSet.apps "mongo-mongodb-replicaset" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' are forbidden.

The only thing that I changed is the ConfigMap. The docs state that Helm only updates things that have changed since the last release. The ConfigMap was actually updated correctly even though the above error was the only output.

**Comment by technosophos** [comment] 2017-01-04 16:37
Looking at the chart, my guess is that the problem is that the deployment manifest is changed on upgrade:

https://github.com/kubernetes/charts/blob/master/incubator/mongodb-replicaset/templates/mongodb-petset.yaml#L58

So even though it's just a changed timestamp in an annotation, it's causing the deployment object to be sent through the update cycle.

(Actually, looks like there may be a few places where the statfulset is changed on upgrade -- mostly timestamp related.)

Is there a corresponding issue in the charts repo?

**Comment by unguiculus** [comment] 2017-01-05 13:17
Ah, thanks. I guess that's causing the issue. Adding the `helm.sh/created` annotation seems to be a quite common practice. I don't see why this would be useful.

The problem aside, I still think Helm's output could be improved. It just printed the error without telling me that the config map was indeed updated.

**Comment by technosophos** [comment] 2017-01-11 16:58
Improving output & logging of commands is something we're continually working on. I think we'll need some sort of way to turn on a more verbose mode for output messages.

Is it okay if I close this issue? Or would you like to change it up to add a specific feature request for an output message?

**Comment by iamzhout** [comment] 2017-01-16 04:18
Maybe one option is to to print out the diff between the new and old in case of any validation error? and also notifying user that although the error message, the configmap has been updated actually.

**Comment by technosophos** [comment] 2017-02-15 00:37
I'm currently thinking that the requirement for this one would be:

`helm upgrade --debug` would output a diff of old-to-new

Adding to the 2.3.0 milestone

**Comment by nanliu** [comment] 2017-03-02 21:00
So essentially: https://github.com/databus23/helm-diff/

**Comment by bacongobbler** [comment] 2017-08-11 22:13
yes, that plugin solves this use case exactly. Closing!

**Closed by bacongobbler** 2017-08-11 22:13 UTC
