### ISSUE TITLE
Helm upgrade stays in PENDING_UPGRADE

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/helm#2956] opened 2017-09-21 20:55 UTC
Some failed upgrades can stick in PENDING_UPGRADE status.  An example is taking the public prometheus chart and setting the version to a `X.X.X-X` which is not supported by kubernetes as it's used as a label in the chart.

The expected behavior would be that the upgrade fails instead of stays pending forever.

https://gist.github.com/sstarcher/e11d234209fe35629502f042f12f51e3

**Comment by MaksymTrykur** [comment] 2017-09-26 15:20
Also experiencing this issue with the latest helm version.

```
helm version
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```
Steps to reproduce:

```
helm install stable/redis

helm history fun-quail
REVISION	UPDATED                 	STATUS         	CHART       	DESCRIPTION      
1       	Tue Sep 26 18:12:44 2017	DEPLOYED     	redis-0.10.1	Install complete

helm upgrade --set persistence.size=10Gi fun-quail stable/redis
Error: UPGRADE FAILED: PersistentVolumeClaim "fun-quail-redis" is invalid: spec: Forbidden: field is immutable after creation

helm history fun-quail
REVISION	UPDATED                 	STATUS         	CHART       	DESCRIPTION      
1       	Tue Sep 26 18:12:44 2017	SUPERSEDED     	redis-0.10.1	Install complete 
2       	Tue Sep 26 18:13:58 2017	PENDING_UPGRADE	redis-0.10.1	Preparing upgrade
```

**Comment by sstarcher** [comment] 2017-10-03 13:47
Seen this again with other failure cases.

**Comment by MaksymTrykur** [comment] 2017-10-03 13:54
Actually it may be stuck in Pending for any failed update.

https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_update.go#L158
Second argument most certainly should be true, because updatedRelease is already created at line 45.

**Comment by redbaron** [comment] 2017-10-03 17:08
will be solved once https://github.com/kubernetes/helm/pull/2960 is merged

**Comment by bacongobbler** [comment] 2017-10-17 21:02
closing since #2960 has now been merged but please re-open if this isn't true. Thanks!

**Closed by bacongobbler** 2017-10-17 21:02 UTC
Labels: question/support

**Comment by valer-cara** [comment] 2018-08-02 15:32
I just hit this and went down to edit the failed release to `DEPLOYED` and go on with the next helm upgrade. Described the process of decoding, editing and updating the configmap here: https://medium.com/@valercara/helm-stuck-in-pending-update-and-how-to-fix-it-13c4b2eaf9f7 (hope it makes sense, not sure if there may be subtleties that may break things, did work in my case)

**Comment by KIVagant** [comment] 2018-08-16 14:53
I got the same today. I don't like the idea to cleanup this manually and don't know how risky to keep it as is.

```
$ helm list  --pending
NAME   	REVISION	UPDATED                 	STATUS         	CHART          	NAMESPACE
myproject	5       	Thu Aug 16 13:43:55 2018	PENDING_UPGRADE	myproject-ed35898	default
```

**Comment by pv93** [comment] 2018-08-30 18:55
Still seeing this with
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Comment by Samusername** [comment] 2019-04-08 10:48
"PENDING_UPGRADE" happened also in following case / way:

Error:* UPGRADE FAILED*: Job failed: DeadlineExceeded 

helm history app01:

```
REVISION        UPDATED                         STATUS          CHART           DESCRIPTION     
 
1               Thu Mar 21 14:49:53 2019        SUPERSEDED      app01-6.4.3      Install complete
2               Tue Apr  2 15:33:20 2019        SUPERSEDED      app01-6.6.0      Upgrade complete
3               Wed Apr  3 11:21:16 2019        DEPLOYED        app01-6.4.3      Rollback to 1   
4               Fri Apr  5 13:56:29 2019        PENDING_UPGRADE app01-6.6.1      Preparing upgrade
```

The problematic job (preinstall hook, etc.?) was stuck. 
Then "DeadlineExceeded" happened. 
And app01 ended up in "PENDING_UPGRADE" state.
helm version: v2.11.0, in my case.

( Root cause regarding the problem is in the job, but helm should not end up in PENDING_UPGRADE still? Or how should it work? )

**Comment by tombh** [comment] 2019-06-25 13:37
I'd just like to offer a different perspective on this, that isn't mentioned elsewhere. Whilst it is frustrating that Helm doesn't offer more help here, I've found that I'm usually able to get myself out of this situation by making a few tweaks myself. Eg; recently an upgrade failed because I had put some secrets in the correct namespace, once I'd corrected that issue Helm eventually sorted itself out.

I think what would help is that Helm gave a bit more feedback on _why_ it's failing, as it's not always clear from the failing pods in the system.
