### ISSUE TITLE
Multiple revisions of same release marked as DEPLOYED

### ISSUE THREAD

**Issue by thoyt** [kubernetes/helm#2941] opened 2017-09-15 18:19 UTC
After installing a chart successfully, I ran a `helm upgrade` with modified values. This caused a `pre-upgrade` hook to fail, since the hook tried to create a job that already existed (since it wasn't deleted before the upgrade).

At that point, `helm ls` would show the first revision as `DEPLOYED`. The second revision would appear only with `helm ls -a`. After deleting the job and rerunning `helm upgrade`, I noticed that there were now two releases of the same chart, both marked as `DEPLOYED` -- the first one, before the `PENDING_UPGRADE` revision, and the most recent.

```
$ helm ls
NAME 	REVISION	UPDATED                 	STATUS  	CHART      	NAMESPACE
comfy	1       	Thu Sep 14 18:24:07 2017	DEPLOYED	comfy-1.0.0	default
comfy	4       	Thu Sep 14 18:47:03 2017	DEPLOYED	comfy-1.0.0	default
```

As expected `helm status` shows the status of the most recent deployed revision. Helm history for the release shows the following:

```
REVISION	UPDATED                 	STATUS         	CHART      	DESCRIPTION
1       	Thu Sep 14 18:24:07 2017	DEPLOYED       	comfy-1.0.0	Install complete
2       	Thu Sep 14 18:46:33 2017	PENDING_UPGRADE	comfy-1.0.0	Preparing upgrade
3       	Thu Sep 14 18:46:52 2017	SUPERSEDED     	comfy-1.0.0	Preparing upgrade
4       	Thu Sep 14 18:47:03 2017	DEPLOYED       	comfy-1.0.0	Upgrade complete
```

This conflicts with my understanding of what `DEPLOYED` means -- I thought that for any release, there could only be one revision that is `DEPLOYED`, corresponding to the kubernetes objects currently in the cluster. Should I be interpreting the meaning of `DEPLOYED` differently or is this behavior not expected?

**Comment by rwillard** [comment] 2017-09-21 18:59
Adding what happened for me as well.
```
51      	Mon Sep 18 13:34:27 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
52      	Mon Sep 18 16:02:49 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
53      	Tue Sep 19 14:27:26 2017	DEPLOYED  	flyrexampleapp-0.1.0	Upgrade complete 
54      	Tue Sep 19 14:35:39 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
55      	Tue Sep 19 14:35:44 2017	SUPERSEDED	flyrexampleapp-0.1.0	Rollback to 53   
56      	Tue Sep 19 14:40:31 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
57      	Tue Sep 19 14:52:03 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
58      	Tue Sep 19 16:19:04 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
59      	Tue Sep 19 16:54:42 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
60      	Tue Sep 19 17:08:06 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
61      	Tue Sep 19 17:08:18 2017	SUPERSEDED	flyrexampleapp-0.1.0	Rollback to 59   
62      	Tue Sep 19 17:44:45 2017	SUPERSEDED	flyrexampleapp-0.1.0	Preparing upgrade
63      	Tue Sep 19 17:50:08 2017	SUPERSEDED	flyrexampleapp-0.1.0	Preparing upgrade
64      	Tue Sep 19 17:53:28 2017	SUPERSEDED	flyrexampleapp-0.1.0	Rollback to 62   
65      	Tue Sep 19 17:53:43 2017	SUPERSEDED	flyrexampleapp-0.1.0	Rollback to 63   
66      	Tue Sep 19 17:53:57 2017	SUPERSEDED	flyrexampleapp-0.1.0	Rollback to 64   
67      	Tue Sep 19 17:54:04 2017	SUPERSEDED	flyrexampleapp-0.1.0	Rollback to 50   
68      	Tue Sep 19 17:54:18 2017	SUPERSEDED	flyrexampleapp-0.1.0	Rollback to 51   
69      	Tue Sep 19 17:58:46 2017	SUPERSEDED	flyrexampleapp-0.1.0	Preparing upgrade
70      	Tue Sep 19 18:02:40 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
71      	Tue Sep 19 18:07:00 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
72      	Tue Sep 19 18:26:02 2017	SUPERSEDED	flyrexampleapp-0.1.0	Upgrade complete 
73      	Thu Sep 21 11:22:40 2017	SUPERSEDED	flyrexampleapp-0.1.0	Preparing upgrade
74      	Thu Sep 21 11:31:08 2017	DEPLOYED  	flyrexampleapp-0.1.0	Upgrade complete 
```
```
NAME              	REVISION	UPDATED                 	STATUS  	CHART               	NAMESPACE
flyrexampleapp-dev	53      	Tue Sep 19 14:27:26 2017	DEPLOYED	flyrexampleapp-0.1.0	dev      
flyrexampleapp-dev	74      	Thu Sep 21 11:31:08 2017	DEPLOYED	flyrexampleapp-0.1.0	dev
```

Before the upgrade that resulted in the duplicate `helm list` entry, `helm list` reported revision 53, but it seems it should have been reporting revision 72 anyway.

**Comment by bacongobbler** [comment] 2017-09-27 17:04
This is definitely unexpected behaviour. Only the most recent release should be in a "DEPLOYED" state.

From another person's deployment I was looking at this morning, this just looks to be a visual/API bug and not a production issue. Kubernetes only has the latest version deployed even if an older release shows in `helm history` as DEPLOYED.

Can the next person that hits this bug please show the output of `kubectl -n kube-system get configmap releasename.v<older_release> -o json`? I want to see if this is something that is actually stored in the config map or of there's a bug in `helm list`/helm history when de-serializing the configmap storing the release information.

**Comment by thoyt** [comment] 2017-09-27 22:53
@bacongobbler, here's the configmap. It looks like it's here as deployed.
```
{
    "apiVersion": "v1",
    "data": {
        "release": [ ... ]},
    "kind": "ConfigMap",
    "metadata": {
        "creationTimestamp": "2017-09-15T01:24:12Z",
        "labels": {
            "MODIFIED_AT": "1505438656",
            "NAME": "comfy",
            "OWNER": "TILLER",
            "STATUS": "DEPLOYED",
            "VERSION": "1"
        },
        "name": "comfy.v1",
        "namespace": "kube-system",
        "resourceVersion": "53022356",
        "selfLink": "/api/v1/namespaces/kube-system/configmaps/comfy.v1",
        "uid": "94e61d9d-99b4-11e7-93e1-06b23930f438"
    }
}
```

**Comment by thoyt** [comment] 2017-09-28 18:40
I'm running into this again today but this time it's a bit worse. We have two revisions marked as deployed, but this time the corresponding deployment objects in kubernetes belong to the old revision. I had to delete the old deployments before the upgrade successfully created the deployments for the new revision.

Just as above, the helm revision metadata in the configmap shows the revision as deployed. Would it make sense to mark this as a bug?

My (naive) take on it: `tiller.release_update` creates a release with `PENDING_UPGRADE` status. Then if a pre-upgrade hook fails, it doesn't clean up the `PENDING_UPGRADE` release. Now the previous `DEPLOYED` release will never be superseded, since `currentRelease` will always be the latest non-deleted revision.

This might be unrelated to the fact that somehow a release was marked as `DEPLOYED` but the kube deployment objects weren't updated, but thought I'd mention that as well.

**Comment by bacongobbler** [comment] 2017-09-28 18:52
Yes this seems more like an actual bug so let's mark it as such.

**Comment by dkellner** [comment] 2017-10-12 08:20
I run into the same issue. Is there a recommended way to recover from this, preferrably without deleting the release?

**Comment by bacongobbler** [comment] 2017-10-12 15:30
You could manually edit the old configmap to be in a SUPERSEDED state... Though fair warning, I haven't done this myself.

**Comment by TimJones** [comment] 2017-10-24 06:36
@bacongobbler @dkellner To confirm, I am also seeing this bug. I made the manual change to the configmap but I still have the multiple revisions in `DEPLOYED` state.

**Comment by dkellner** [comment] 2017-10-24 08:24
@TimJones Thanks for sharing your experience, I did not try it myself yet. I guess I will wait until someone with more knowledge about the inner workings of Helm confirms that this is the way to address this.

**Comment by Starefossen** [comment] 2017-10-27 14:22
We are experiencing the same bug. The release persists even after deleting the release from tiller.

**Comment by fishi0x01** [comment] 2017-11-10 15:41
We are experiencing this bug too. Manual changes to the configmap labels didn't help. Also tried changing the `MODIFIED_AT` label to a current timestamp, hoping that this would maybe trigger tiller to re-read the whole configmaps -> no success ..

Currently the only way to recover for us is to delete the helm managed resources and re-deploy the chart. In production this is not a viable option though ..

**Comment by grillz** [comment] 2017-11-10 20:43
Is there any update on this or anything we can help with? This is easy to fall into if your using readiness probes, and then very difficult to get out of.

**Comment by fishi0x01** [comment] 2017-11-13 16:48
It seems that helm is not using the labels from the release configmaps storage for any operational decisions. To me it looks like helm is also storing status information like `DEPLOYED` via protobuf inside the `release` key of the configmap. This is a cryptic value which cannot be modified easily in a sane way by hand, meaning that manual recovery from this error is out of reach ..

**Comment by fishi0x01** [comment] 2017-11-14 15:46
I just realized that one obvious solution to manually recover is to delete the affected configmaps. I just made some tests and after deleting all configmaps of the old revisions that are falsely marked `DEPLOYED`, everything seemed to work fine again. Of course the big down-side here is that the whole revision is lost then, but apart from that I do not witness any other problems yet.

**Comment by TimJones** [comment] 2017-11-24 09:42
The only way I have found so far is to run a `helm delete --purge` on the release and redeploy. Thankfully, we've only had this bug hit our 'staging' deployments so far, so the loss of service wasn't an issue.

**Comment by Starefossen** [comment] 2017-11-24 21:22
Confirming that `helm delete <release> --purge` worked for this issue. Modifying the ConfigMap and restarting tiller did not.

**Comment by bacongobbler** [comment] 2017-11-24 22:34
@Starefossen did you try removing the ConfigMap?

I agree that this is a big issue, but in the meantime that should be good enough for a workaround until we can nail down the root cause.

Additionally, helm 2.7 introduced the `--history-max` feature flag to `helm init` so tiller will only store a certain number of releases in the ledger, which may further mitigate this issue.

**Comment by egeland** [comment] 2017-12-07 23:43
This affect us, too. We mitigate by deleting the configmaps manually - which is really annoying as we do a lot of deployments... 😅

**Comment by liamawhite** [comment] 2017-12-10 07:28
We were also seeing this. I _think_ its cause by using both <2.7.1 and >2.7.1 to deploy the same release. As mentioned by @Starefossen, a `helm delete <release> --purge` then reinstall seems to fix it.

**Comment by egeland** [comment] 2017-12-11 00:23
Deleting production apps is not really a viable solution 😜

**Comment by Stono** [comment] 2018-01-08 21:39
Ditto

```
❯ helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                           NAMESPACE
elastic         15              Mon Jan  8 21:34:04 2018        DEPLOYED        helm-infra-elasticsearch-0.1.74 default
elastic         16              Mon Jan  8 21:36:22 2018        DEPLOYED        helm-infra-elasticsearch-0.1.76 default
```

**Comment by stealthybox** [comment] 2018-01-16 01:14
Workaround to cleanup `helm list`:
**warning:** loses the revision
```bash
kubectl -n kube-system delete configmap ${release_name}.v${release_number}
```
Be careful not to delete the actual version you have deployed which should be the highest number.

**Comment by TimJones** [comment] 2018-01-16 17:02
I've noticed a pattern with our deployments, and I'm hoping to get confirmation from others suffering from this bug.  
It seems that the duplication is caused when a deployment has `pre-install`/`pre-upgrade` hooks set in annotations, and the hook fails.

**Comment by stealthybox** [comment] 2018-01-16 17:20
^ @TimJones  interesting -- we are using `post-install,post-upgrade`

**Comment by Stono** [comment] 2018-01-16 17:21
We are not.
Correlation isn't causation :p but nice try!

**Comment by thoyt** [comment] 2018-01-16 18:13
We're using a `pre-upgrade` hook as well. I think there are several situations where an upgrade fails but it doesn't clean up properly.

**Comment by burdiyan** [comment] 2018-01-17 21:07
We are not using hooks, but it happens from time to time with clear pattern.

**Comment by sfrique** [comment] 2018-01-29 13:34
I had the same problem.  Not using any hooks for this chart.
```
$ helm list | grep homer                               
homer        	10      	Wed Jan 24 18:21:25 2018	DEPLOYED	homer-0.1.0         	default  
homer        	4       	Wed Jan 24 17:22:03 2018	FAILED  	homer-0.1.0         	default  
```

The problem with the chart was creating a job resource.

I won't delete the configmap because of revision for now. 

Other then showing duplicated, what other erros this can cause?
Or delete the configmap is safer?

I can't just purge it and bring it back because there are persistent storage at that chart.

This is still experimental cluster/helm stuff.
Thanks.

**Comment by sethcleveland** [comment] 2018-01-29 18:39
We saw this too. To the best of our knowledge, we think a pre-install/pre-upgrade job failure caused it. What was insidious was after that failure, all charts were locked at the older revision. We couldn't deploy new charts until deleting/purging the helm release. Real bummer.

**Comment by mikejk8s** [comment] 2018-02-02 23:21
I run into this issue pretty frequently and finally spent the time to track down what it was (on the user end, at least).

1. If you watch tiller you will see it attempt to update multiple releases, mine for instance was trying to update two releases that were significantly different in release date/objects.

```[tiller] 2018/02/02 23:06:35 warning: Upgrade "lanky-squid" failed: no Service with the name "billing-service-db" found
[storage] 2018/02/02 23:06:35 updating release "lanky-squid.v2020"
[storage] 2018/02/02 23:06:35 updating release "lanky-squid.v2060"```

2. After figuring out that I was running into 2 releases being updated, I assume one is missing the new object I added. I then copied out the 2 configmaps to keep them in case I needed them later. I do not want to have to reinstall this release. COPY OUT THESE RELEASE CONFIGMAPS! YOU ARE DELETING THEM ALL IN THE NEXT STEP.

```kubectl get configmap $configmap-v.# -n=kube-system export -o yaml"```

3. I then deleted every single configmap through a forloop. Please be careful with this. There is a label for OWNER and NAME that are very important. If you skip those you may delete releases for every helm app you've deployd
```for configmap in `kubectl get configmaps -l OWNER=TILLER,NAME=$release-name -n kube-system |awk '{ print $1 }'`; do kubectl delete configmap $configmap -n=kube-system; done```

4. If you try to run helm upgrade now you'll get an error that you have no deployed releases. What you need to do now is copy out one of those deployed releases that you saved in step 1, apply it, and if the Status is FAILED mark it as DEPLOYED. This will allow you to run Helm upgrade.

5. Theoretically now that you only have one release file you should be able to successfully push updates through. I just did this and it fixed my issue so I've got no way to test this further. I'm guessing if you used to latest deployed release vs the oldest deployed release (from the 2 configmaps you saved) you may need to go through and verify your docker tag versions, etc. You can do this with the following;

```kubectl get pods --all-namespaces -o jsonpath="{..image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq -c```

Good luck.

**Comment by Stono** [comment] 2018-02-04 14:27
Just to throw in my two cents, this is what happens for us:

```
❯ helm ls
NAME                            REVISION        UPDATED                         STATUS          CHART                                   NAMESPACE
helm-cmp-signals-platform       94              Fri Feb  2 21:57:53 2018        DEPLOYED        helm-cmp-signals-platform-0.1.193       default
helm-cmp-signals-platform       95              Sun Feb  4 14:15:57 2018        FAILED          helm-cmp-signals-platform-0.1.197       default
```
We have a failed deployment, so we rollback...

```
❯ helm rollback helm-cmp-signals-platform 94
Rollback was a success! Happy Helming!
```

This leaves you with two charts in a deployed state...
```
❯ helm ls
NAME                            REVISION        UPDATED                         STATUS          CHART                                   NAMESPACE
helm-cmp-signals-platform       94              Fri Feb  2 21:57:53 2018        DEPLOYED        helm-cmp-signals-platform-0.1.193       default
helm-cmp-signals-platform       96              Sun Feb  4 14:19:58 2018        DEPLOYED        helm-cmp-signals-platform-0.1.193       default
```

And the only way I've found to fix this is to delete the configmaps associated with all except the latest release:
```
❯ kubectl --namespace=kube-system get configmap | grep signals-platform | grep -v "v$(helm ls | grep signals-platform | awk '{print $2}' | tail -n 1)" | awk '{print $1}' | xargs -n 1 kubectl --namespace=kube-system delete configmap
configmap "helm-cmp-signals-platform.v93" deleted
configmap "helm-cmp-signals-platform.v94" deleted
configmap "helm-cmp-signals-platform.v95" deleted
```

**Comment by bacongobbler** [comment] 2018-02-05 01:31
Is this with v2.8.0? Pretty sure we fixed that in master.

**Comment by sethcleveland** [comment] 2018-02-06 16:13
We were using 2.7.2. We'll move to 2.8.0 soon. So, hopefully this is all
fixed up. Thanks for the help.

**Comment by bacongobbler** [comment] 2018-02-06 16:17
@Stono very interesting. I'll see if I can re-create that scenario. We may not be marking rollbacked deploys as SUPERSEDED which is how we can get into a state of more than 1 release being in a DEPLOYED state.

**Comment by Stono** [comment] 2018-02-06 17:25
Cheers @bacongobbler

**Comment by bacongobbler** [comment] 2018-02-06 19:01
Nope, I was not able to reproduce that with v2.8.0, @Stono.

```
><> helm history intentional-whippet
REVISION	UPDATED                 	STATUS    	CHART         	DESCRIPTION
1       	Tue Feb  6 10:57:32 2018	SUPERSEDED	traefik-1.17.1	Install complete
2       	Tue Feb  6 10:57:58 2018	DEPLOYED  	traefik-1.17.1	Upgrade complete
><> helm rollback intentional-whippet 1
Rollback was a success! Happy Helming!
><> helm list
NAME               	REVISION	UPDATED                 	STATUS  	CHART         	NAMESPACE
intentional-whippet	3       	Tue Feb  6 10:58:22 2018	DEPLOYED	traefik-1.17.1	default
><> helm history intentional-whippet
REVISION	UPDATED                 	STATUS    	CHART         	DESCRIPTION
1       	Tue Feb  6 10:57:32 2018	SUPERSEDED	traefik-1.17.1	Install complete
2       	Tue Feb  6 10:57:58 2018	SUPERSEDED	traefik-1.17.1	Upgrade complete
3       	Tue Feb  6 10:58:22 2018	DEPLOYED  	traefik-1.17.1	Rollback to 1
```

Are you using an older version of Tiller, perhaps something prior to v2.7.1? https://github.com/kubernetes/helm/pull/3097 fixed that particular issue.

**Comment by bacongobbler** [comment] 2018-02-06 19:01
Lemme see if I can get a failed deploy out and try that scenario specifically. Could be an edge case around failed deploys.

**Comment by Stono** [comment] 2018-02-06 19:11
@bacongobbler that was 2.7.2 :-) I haven't tried it in 2.8.0 yet!  your test is slightly different though, i was rolling back a failed deployment.

So:

  - Success #1
  - Fail #2
  - Rollback to #1 (creates #3)

I'll try it in 2.8.0 when i get a minute though - just juggling about 15 things right now!

**Comment by Stono** [comment] 2018-02-06 19:27
@bacongobbler just tested it on 2.8.0 and was unable to recreate the issue so i'd say it's resolved in the latest version

**Comment by bacongobbler** [comment] 2018-02-06 19:28
That was a surprisingly easy reproducible test case. I think we've got the issue nailed down. Thanks @stono!

To reproduce, first install a normal release:

```
$ helm install --name t stable/traefik
```

Then, deploy a release that will fail. The easiest way to do this is to change a type from a string to an int in the pod's environment or something that'll fail the spec.

```
><> helm upgrade intentional-whippet ./traefik
Error: UPGRADE FAILED: failed to create patch: failed to get versionedObject: unable to convert unstructured object to extensions/v1beta1, Kind=Deployment: cannot convert int64 to string
```

Then we roll back to v1:

```
><> helm history t
REVISION	UPDATED                 	STATUS    	CHART         	DESCRIPTION
1       	Tue Feb  6 11:22:38 2018	DEPLOYED  	traefik-1.17.1	Install complete
2       	Tue Feb  6 11:22:53 2018	SUPERSEDED	traefik-1.17.1	Upgrade "t" failed: failed to create patch: failed to get...
3       	Tue Feb  6 11:23:04 2018	DEPLOYED  	traefik-1.17.1	Rollback to 1
```

et voila. We have our bug.

**Comment by Stono** [comment] 2018-02-06 19:33
My pleasure.

**Comment by bacongobbler** [comment] 2018-02-06 21:22
I'm getting pulled in other directions for dev summit planning but if anyone wants to write the fix, here's the unit test: https://github.com/bacongobbler/helm/commit/666300268852ac806d7b523269c4ce1d743e56be

**Comment by balboah** [comment] 2018-02-20 10:12
I'm currently taking a look at that unit test

**Comment by balboah** [comment] 2018-02-20 14:56
PR is up for grabs!

**Closed** 2018-02-27 18:25 UTC
Labels: bug

**Comment by ariep** [comment] 2018-09-18 12:10
I'm still running into this with helm 2.10:
```
$ helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE  
altered-sheep   1               Wed Sep 12 13:52:06 2018        DEPLOYED        rocketchat-0.1.4        0.68.5          default    
juiced-crab     4               Thu Sep 13 11:53:01 2018        DEPLOYED        rocketchat-0.1.4        0.68.5          default
$ helm history altered-sheep
REVISION        UPDATED                         STATUS          CHART                   DESCRIPTION      
1               Wed Sep 12 13:52:06 2018        DEPLOYED        rocketchat-0.1.4        Install complete 
2               Wed Sep 12 14:08:59 2018        DELETED         rocketchat-0.1.4        Deletion complete
```
So the `altered-sheep` release is deleted (also according to `helm status altered-sheep`) but lists as deployed in `helm ls`.

**Comment by chenxushuo** [comment] 2018-12-29 12:02
Me too！When i run a erro release;but wo rollback the lastest right realease ,and upgrade again。 Everythinker is OK！

**Comment by mdeknowis** [comment] 2019-05-27 11:17
We have the issue also with 2.11.0:

```txt
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

and then we got that issue:
```txt
 helm history my-release
REVISION        UPDATED                         STATUS          CHART           DESCRIPTION
80              Fri May 17 15:08:32 2019        SUPERSEDED      my-chart-3260  Upgrade complete
81              Fri May 17 15:14:07 2019        SUPERSEDED      my-chart-3260  Upgrade complete
82              Fri May 17 15:38:46 2019        SUPERSEDED      my-chart-3260  Upgrade complete
83              Fri May 17 15:48:50 2019        SUPERSEDED      my-chart-3260  Upgrade complete
84              Tue May 21 13:33:40 2019        DEPLOYED        my-chart-3260  Upgrade complete
85              Thu May 23 17:12:10 2019        DEPLOYED        my-chart-3293  Upgrade complete
86              Mon May 27 10:57:19 2019        FAILED          my-chart-3293  Upgrade "my-config-map" failed: no ConfigMap...
87              Mon May 27 11:07:35 2019        FAILED          my-chart-3293  Upgrade "my-config-map" failed: no ConfigMap...
88              Mon May 27 11:17:10 2019        FAILED          my-chart-3293  Upgrade "my-config-map" failed: no ConfigMap...
89              Mon May 27 12:39:38 2019        FAILED          my-chart-3293  Upgrade "my-config-map" failed: no ConfigMap...
```

**Comment by marcelmeulemans** [comment] 2019-07-10 13:14
We are also still seeing multiple releases marked as DEPLOYED with 2.14.0. We have a build cluster doing the deployments and sometimes multiple deployment jobs to the same cluster are running at the same time from different machines (i.e. so multiple `helm upgrade some-chart` calls). Could it be a race condition? I will try to verify my hunch in the coming days.

**Comment by novas0x2a** [comment] 2019-10-05 19:03
We just saw this with tiller 2.14.1:
```
$ helm history my-cool-service
REVISION        UPDATED                         STATUS          CHART                   DESCRIPTION
2               Tue Aug 20 15:54:33 2019        SUPERSEDED      my-cool-service-2.5.0 Upgrade complete
3               Thu Sep  5 11:48:45 2019        SUPERSEDED      my-cool-service-2.5.1 Upgrade complete
4               Sat Oct  5 09:35:06 2019        SUPERSEDED      my-cool-service-2.6.1 Upgrade complete
5               Sat Oct  5 10:32:52 2019        DEPLOYED        my-cool-service-2.5.1 Rollback to 3
6               Sat Oct  5 11:00:30 2019        DEPLOYED        my-cool-service-2.6.1 Upgrade complete
```

The sequence of events was
1) rev 3 was running
2) deploy for rev 4 started (with --wait)
3) deploy for rev 4 hit timeout and triggered an auto-rollback (with no wait) creating rev 5
4) attempted to deploy 2.6.1 again, creating rev 6; rev 5 was not marked superseded
5) we noticed that live state did not match 2.6.1, but subsequent diffs were calculated against rev 6
6) using `helm get manifest my-cool-service  --revision X | kubectl -n my-cool-namespace diff -f -` detected which rev matched live state (it was rev 5)
7) issued a `helm rollback my-cool-service 5` to sync helm's state back to the live cluster state
8) started the 2.6.1 deploy again, this time, it succeeded

it appears this bug is still present. the fix that closed this ticket (https://github.com/helm/helm/pull/3539) allows us to recover from it relatively easily with direct operator intervention (thanks!), but the race that causes multiple revisions to be in deployed state still exists.
￼

**Comment by sjmiller609** [comment] 2020-01-21 18:03
We are still seeing this issue in 2.16.1. Using rollback does clear up the helm history, I expect taken care of by this PR https://github.com/helm/helm/pull/3539

**Comment by LudoNieuw** [comment] 2020-02-26 15:32
I'm a bit confused: 
The mentioned PR took care of rollback marking all other 'Deployed'-status chart versions as 'Superseded'. However, this does not fix the issue arising again. Can someone comment on the progress on this last part? I am using helm v 2.11 currently and want to update to 2.16 soon if this will guard against the above-mentioned version-mixup.

**Comment by jimethn** [comment] 2020-09-30 05:12
Can we reopen this? #3539 is a workaround, not a fix. We can still get into a state with two DEPLOYED releases.

**Comment by bacongobbler** [comment] 2020-09-30 13:56
Please demonstrate how two releases can enter a deployed state.

**Comment by jimethn** [comment] 2020-10-02 20:34
I was able to repro using novas0x2a's steps above. Simplified version:

1. `helm create repro && cd repro` this will get you a basic nginx chart
2. Open two terminals in that repro folder with KUBECONFIG to the same cluster
3. `helm install . --name repro` to just get it set up
4. Edit the values.yaml, change .image.tag to something invalid e.g. "  tag: faketag"
5. In the first terminal `helm upgrade repro . --wait --timeout 30`
6. While that's running, in the second terminal edit the tag back to stable and `helm upgrade repro . --wait`
7. You now have two deployed releases:

```
cluster-test> helm history repro
REVISION	UPDATED                 	STATUS    	CHART      	DESCRIPTION     
1       	Fri Oct  2 16:18:11 2020	SUPERSEDED	repro-0.1.0	Install complete
2       	Fri Oct  2 16:19:01 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
3       	Fri Oct  2 16:20:22 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
4       	Fri Oct  2 16:21:51 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
5       	Fri Oct  2 16:22:09 2020	DEPLOYED  	repro-0.1.0	Upgrade complete
6       	Fri Oct  2 16:22:29 2020	DEPLOYED  	repro-0.1.0	Upgrade complete
```

Any kind of deployment failure can cause this (helm hooks, initConainers, failing health checks). Picking an invalid image is just the easiest way to fail a deployment.

Once you're in this state, you'll stay this way for subsequent deployments.

```
cluster-test> vi values.yaml 
cluster-test> helm upgrade repro . --wait --timeout 30
Release "repro" has been upgraded.
LAST DEPLOYED: Fri Oct  2 16:28:40 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME   READY  UP-TO-DATE  AVAILABLE  AGE
repro  1/1    1           1          10m

==> v1/Pod(related)
NAME                    READY  STATUS       RESTARTS  AGE
repro-5fc4b9c764-n4ns7  1/1    Running      0         13s
repro-ffdc7f484-cq5nf   0/1    Terminating  0         6m24s

==> v1/Service
NAME   TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)  AGE
repro  ClusterIP  10.43.102.80  <none>       80/TCP   10m


NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=repro,app.kubernetes.io/instance=repro" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

cluster-test> helm history repro                      
REVISION	UPDATED                 	STATUS    	CHART      	DESCRIPTION     
1       	Fri Oct  2 16:18:11 2020	SUPERSEDED	repro-0.1.0	Install complete
2       	Fri Oct  2 16:19:01 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
3       	Fri Oct  2 16:20:22 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
4       	Fri Oct  2 16:21:51 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
5       	Fri Oct  2 16:22:09 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
6       	Fri Oct  2 16:22:29 2020	DEPLOYED  	repro-0.1.0	Upgrade complete
7       	Fri Oct  2 16:28:40 2020	DEPLOYED  	repro-0.1.0	Upgrade complete
```

It can easily be fixed by rolling back to the version you're already on though (thanks to #3539 I'm guessing).

```
cluster-test> helm rollback repro 7
Rollback was a success.
cluster-test> helm history repro   
REVISION	UPDATED                 	STATUS    	CHART      	DESCRIPTION     
1       	Fri Oct  2 16:18:11 2020	SUPERSEDED	repro-0.1.0	Install complete
2       	Fri Oct  2 16:19:01 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
3       	Fri Oct  2 16:20:22 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
4       	Fri Oct  2 16:21:51 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
5       	Fri Oct  2 16:22:09 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
6       	Fri Oct  2 16:22:29 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
7       	Fri Oct  2 16:28:40 2020	SUPERSEDED	repro-0.1.0	Upgrade complete
8       	Fri Oct  2 16:33:43 2020	DEPLOYED  	repro-0.1.0	Rollback to 7   
```

**Comment by jimethn** [comment] 2020-10-09 16:09
Actually I realized those steps are superfluous. You don't need to create a failure. This can easily be reproduced by just running `helm upgrade RELEASE` twice in rapid succession.
