### ISSUE TITLE
"No release found" when first time installation fails

### ISSUE THREAD

**Issue by Ahmadposten** [kubernetes/helm#3429] opened 2018-01-31 17:29 UTC
When first time installation fails even though most of the objects have been successfully installed, any upcoming upgrade will fail claiming that there is no release found.

This becomes really annoying and needs manual purging of the release for things to start working again.

**Comment by jascott1** [comment] 2018-01-31 17:40
Can you share a chart that reproduces the problem and describe your workflow for installation? Releases should be upgradable even after failures.

**Comment by bacongobbler** [comment] 2018-01-31 18:12
I’ll put a shiny nickel on the fact it’s due to RBAC being enabled but tiller has not been configured to use RBAC.

**Comment by bmperrea** [comment] 2018-02-02 01:37
I think this is a duplicate of #3353

**Comment by bacongobbler** [comment] 2018-02-02 01:41
ah @bmperrea you might be right. I assumed from the OP that "no release found" was more indicative of misconfigured RBAC but I can see how "has no deployed releases" can translate to the user as "no release found".

@Ahmadposten can you elaborate more on the problem as @jascott1 requested, with chart examples or terminal logs/steps to reproduce?

**Closed** 2018-02-02 06:57 UTC
Labels: question/support
