### ISSUE TITLE
Helm is converting my git tag to exponential form

### ISSUE THREAD

**Issue by owenmorgan** [kubernetes/helm#2357] opened 2017-04-29 17:31 UTC
Using the git hash in my charts, and passing it as a cli argument, its messing up my tag in the rendered template.

Helm v2.3.0

Deployment.yml
```
..
containers:
        - name: "{{.Values.image.name}}"
          image: "{{.Values.image.registry}}/{{.Values.image.name}}:{{.Values.image.tag}}"
```

CLI
`helm upgrade --dry-run --debug --install --wait test --values values-UAT.yaml --set image.tag=9765483 .`

USER-SUPPLIED VALUES:
```
image:
     tag: 9765483
```

COMPUTED VALUES:
```
image:
  tag: 9.765483e+06
```

**Comment by yuvipanda** [comment] 2017-05-01 19:53
When I ran into this (I was specifying values inside a yaml file), putting quotes around them solved it for me.

**Comment by owenmorgan** [comment] 2017-05-01 20:59
thanks. tried quotes in the command line and still see the issue.

`helm upgrade --dry-run --debug --install --wait test --values values-UAT.yaml --set image.tag="9765483" .`

```
COMPUTED VALUES:
   tag: 9.765483e+06
```

**Comment by databus23** [comment] 2017-05-02 12:38
Duplicate of https://github.com/kubernetes/helm/issues/1707

**Comment by michelleN** [comment] 2017-05-03 15:05
yeah that's strange. we'll need to look into this.

**Comment by wieslaw-gat** [comment] 2017-05-04 15:39
Also experiencing this & no workaround from the related issues seems to work.

**Comment by owenmorgan** [comment] 2017-09-19 10:33
hello, any update on this?

**Comment by bacongobbler** [comment] 2017-09-19 15:12
Can you try `--set image.tag=\"9765483\"`? The --set parser takes quoted values as the value, so you might need to escape it in order to quote them on the command line.

Seems to work for me:

```
><> helm template chart/draftd/ --set image.tag=\"8675309\" | grep 675
        image: "microsoft/draft:"8675309""
><> helm template chart/draftd/ --set image.tag="8675309" | grep 675
        image: "microsoft/draft:8.675309e+06"
```

**Comment by bacongobbler** [comment] 2018-02-09 18:52
closing as a duplicate of #1707 as previously pointed out.

**Closed by bacongobbler** 2018-02-09 18:52 UTC
Labels: bug, lifecycle/rotten
