### ISSUE TITLE
After adding deployment to a chart helm upgrade ... --reuse-values=true fails

### ISSUE THREAD

**Issue by tiukhtinvladimir** [kubernetes/helm#3775] opened 2018-03-28 11:38 UTC
Hello. I created a chart, deployed the chart, adjusted the chart with an additional deployment and appropriate values, but when I am doing ```helm upgrade --reuse-values=true```it fails, because this new variables were not defined in previous deployment. In my vision it must take defaults from chart for all variables not defined it --reuse-values=true

Output of `helm version`:
```
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bacongobbler** [comment] 2018-04-11 21:37
closing as a duplicate of https://github.com/kubernetes/helm/issues/3655.

**Closed by bacongobbler** 2018-04-11 21:37 UTC
Labels: question/support
