### ISSUE TITLE
Listing the appVersion for a deployed Release

### ISSUE THREAD

**Issue by derekbassett** [kubernetes/helm#3727] opened 2018-03-21 20:19 UTC
We are using helm to deploy our custom application.  We would also like to use the appVersion tag to specify an "appVersion".  When running the `helm list` command we would like to be able to see what version of the release.  This is similar to what `helm search` command prints out as well.

**Comment by bacongobbler** [comment] 2018-03-21 20:36
dupe of https://github.com/kubernetes/helm/issues/3592

**Closed by bacongobbler** 2018-03-21 20:36 UTC
