### ISSUE TITLE
Provide command consistency between Kubernetes and Helm

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/helm#594] opened 2016-04-08 23:18 UTC
kubectl verb pluralized-noun
    kubectl get pods

But

    helm singular-noun verb
    helm deployment list

Propose 

    helm verb pluralized-noun
    helm get deployments

**Comment by runseb** [comment] 2016-04-09 08:45
@DazWilkin can we close this as duplicate of #555 ?

**Comment by DazWilkin** [comment] 2016-04-09 16:31
Sure

**Comment by jackgr** [comment] 2016-04-11 17:11
Closing as duplicate.

**Closed by jackgr** 2016-04-11 17:11 UTC
Labels: duplicate
