### ISSUE TITLE
helm install --wait does not wait for deployment pod readiness properly

### ISSUE THREAD

**Issue by jgiles** [kubernetes/helm#3173] opened 2017-11-20 16:24 UTC
I recently discovered and started using `--wait`:
```
--wait                   if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment are in a ready state before marking the release as successful. It will wait for as long as --timeout
```
It's great!

However, when I run `helm install --wait`, the command exits successfully before the pods in my deployments pass their configured readiness probe.

I did a little spelunking to confirm that my expectations were correct, and found this suspicious-looking code attempting to do the deployment readiness check:
```go
func (c *Client) deploymentsReady(deployments []deployment) bool {
	for _, v := range deployments {
		if !(v.replicaSets.Status.ReadyReplicas >= *v.deployment.Spec.Replicas-deploymentutil.MaxUnavailable(*v.deployment)) {
			c.Log("Deployment is not ready: %s/%s", v.deployment.GetNamespace(), v.deployment.GetName())
			return false
		}
	}
	return true
}
```
permalink: https://github.com/kubernetes/helm/blob/d790f7d843182f1c126cfa64989ffdd4e9583747/pkg/kube/wait.go#L174

I'm happy to send a PR to fix the if-check, but might need some advice on testing the fix.

**Comment by cueBall123** [comment] 2018-01-02 17:20
I just ran into this issue. Is there a work around for this until the fix is in place.

**Comment by paolomainardi** [comment] 2018-01-24 19:50
A reproducible test case can be found here: https://github.com/paolomainardi/helm-wait-test
You can find here the recorded terminal session: https://asciinema.org/a/RdnLJpALOik8MLlzlFSUqCxOc

Helm version:

```
 ❯ helm version --tiller-namespace test                                                                                                                                
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```
The same behaviour is present also using helm < 2.8.0
If you need more info, please don't hesitate to ask me.

**Comment by paolomainardi** [comment] 2018-01-25 10:14
ping @jgiles @cueBall123

**Comment by paolomainardi** [comment] 2018-01-25 14:18
I tried several things:

* adding `maxUnavailable: 0`  
* trying to add `replicaCount : 4`

But nothing change:

```
test git:master ❯ helm upgrade --timeout 600 --install test --wait --tiller-namespace test .                                                                                           
Release "test" does not exist. Installing it now.
NAME:   test
LAST DEPLOYED: Thu Jan 25 15:18:30 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME  TYPE       CLUSTER-IP   EXTERNAL-IP  PORT(S)  AGE
test  ClusterIP  10.3.242.21  <none>       80/TCP   2s

==> v1beta2/Deployment
NAME  DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
test  4        4        4           0          2s


NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app=test,release=test" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

test git:master ❯ kubectl get pod -ntest                                                                                                                                               ✹
NAME                            READY     STATUS    RESTARTS   AGE
test-64d4979f9f-7mrxg           0/1       Running   0          5s
test-64d4979f9f-fk4b9           0/1       Running   0          5s
test-64d4979f9f-vxkkk           0/1       Running   0          5s
test-64d4979f9f-zxpns           0/1       Running   0          5s
tiller-deploy-566ff67bd-c2nv4   1/1       Running   0          43s
```

**Comment by paolomainardi** [comment] 2018-01-26 23:28
Just an update to this issue, it seems to be related to the `apiVersion` used on the deployment manifest.

Testing on:

```
kubectl version                                                                                                                                                     

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Helm: 

```
test git:master ❯ helm version --tiller-namespace test                                                                                                                                
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"dirty"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

Test cases:

* apps/v1beta2: https://github.com/paolomainardi/helm-wait-test/tree/master 
* apps/v1beta1: https://github.com/paolomainardi/helm-wait-test/blob/paolomainardi-apiv1beta1/templates/deployment.yaml
* extensions/v1beta1: https://github.com/paolomainardi/helm-wait-test/blob/paolomainardi-extensions-v1beta1/templates/deployment.yaml

`--wait` is working just when `extensions/v1beta1` is used, all the other scenarios are broken

**Comment by thomastaylor312** [comment] 2018-01-26 23:30
I think `apps/v1` should work too, although I haven't tested it

**Comment by paolomainardi** [comment] 2018-01-26 23:32
@thomastaylor312 i can't test it, because (i guess) that apiVersion is not available since 1.9.0

**Comment by ljnelson** [comment] 2018-01-26 23:36
@thomastaylor312 My contention would be that at least in the case of `Deployment`s, `apps/v1` would work, yes, because the [two case blocks](https://github.com/kubernetes/helm/blob/v2.8.0/pkg/kube/wait.go#L76-L105) are exact copies of each other (maybe Go doesn't allow fallthrough?).

**Comment by unguiculus** [comment] 2018-01-27 10:28
#3372 is similar in that only certain API versions were considered. I fixed it by adding the missing ones. I wonder if we should try and find a more generic solution using reflection. Right now the code would break as soon as new API versions are added.

**Comment by paolomainardi** [comment] 2018-01-27 10:50
The simplest fix: https://github.com/kubernetes/helm/pull/3407

**Comment by mattfarina** [comment] 2018-01-31 20:55
With #3407 being merged I believe this is fixed. Please re-open if the issue persists. It was tagged for the next patch release so it should be in that release.

**Closed by mattfarina** 2018-01-31 20:55 UTC
Labels: bug

**Comment by davidchua** [comment] 2018-03-09 05:26
I'm actually having this issue on `helm v2.7.2` but on `extensions/v1beta1`

```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

```
$ helm upgrade --install k8s-readiness-test ./repo --debug --namespace=k8s-readiness-test --values repo/values-dev.yaml --set imageTag=k8s-readiness-test-0d984aaa7732b603fcca5f3c3338e3f83e61c718 --wait --timeout 600

NAMESPACE: k8s-readiness-test
STATUS: DEPLOYED
<< ... truncated ... >>
==> v1beta1/Deployment
NAME                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
somecool-service  1        1        1           0          1m
```

**Comment by bacongobbler** [comment] 2018-03-09 05:29
@davidchua this was fixed in 2.8.1

**Comment by davidchua** [comment] 2018-03-09 06:17
@bacongobbler I'm going through the code but the major changes I see from `2.7.2` and `2.8.1` on `pkg/kube/wait.go` for `extensions/v1beta1` that may be relevant to the issue would just be the move from `kcs.Core().Pods` to `kcs.CoreV1().Pods` and `kcs.Extensions().Deployments` to `kcs.ExtensionsV1beta1().Deployments`.

Why would this affect the way the `--wait` deal with this scenario?

Please pardon my ignorance. My concern is also trying to avoid having to upgrade `helm` at least for the moment.

**Comment by davidchua** [comment] 2018-03-09 09:08
I have upgraded `helm` to `2.8.1`, with the same issue, the pod is crashing, but `helm upgrade --install --wait --timeout 600` still passes.

**Comment by samchenraising** [comment] 2018-04-25 22:01
#3296 seems like the same issue. I'm using extensions/v1beta1. Helm v2.8.2, tested with k8s v1.7.12 and 1.8.0

**Comment by thomastaylor312** [comment] 2018-05-04 19:54
@samchenraising Yes it is. Let's use that as the issue to follow

**Comment by sta-szek** [comment] 2018-05-08 06:02
Hi I have the same issue with helm 2.8.2.
I always deploy 2 pods using RollingUpdate 25%, 25%, always different docker image tag.

Helm seems to be waiting as described:
```--wait                   if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment are in a ready state before marking the release as successful. It will wait for as long as --timeout```

but after first pod is ready, it exits -- it does not wait for second pod!

I think problem is somewhere here: ` will wait until ... minimum number of Pods of a Deployment are in a ready state ...`

I have two pods ready, but one from old release and one from new release.

**Comment by mbelang** [comment] 2018-05-18 12:32
Is there somebody that had a combination of Helm version + + k8s version + k8s api version that actually work with the helm --wait?

**Comment by thomastaylor312** [comment] 2018-05-18 20:03
@mbelang It works for me with `apps/v1` on k8s 1.10 and Helm 2.9

**Comment by mbelang** [comment] 2018-05-18 20:19
@thomastaylor312 This is good news. Now we need to figure if it will work with `apps/v1beta2`. According to this it should: https://github.com/kubernetes/helm/pull/3407

**Comment by cforce** [comment] 2019-03-27 06:51
https://github.com/helm/helm/issues/4210

**Comment by staticdev** [comment] 2019-05-23 20:24
Please reopen the issue @Crazybus. I am having this problem with 2.14 version of Helm.

To reproduce just try the script:
```sh
helm repo add storageos https://charts.storageos.com
helm install storageos/storageos-operator --namespace storageos-operator --wait
kubectl patch storageclass fast -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

**Comment by vrobinho** [comment] 2019-06-21 14:44
According to the documentation, the `--wait` has a limited scope:

> Waits until all Pods are in a ready state, PVCs are bound, Deployments have minimum (Desired minus maxUnavailable) Pods in ready state and Services have an IP address (and Ingress if a LoadBalancer) before marking the release as successful

I might had overlooked it but I don't find the definition of the storage in the chart. Does it get created by the operator? 

If yes, I don't see any readiness probe defined in the Deployment (/pod). A readiness probe based on the availability of the created artifacts could be handy here?

**Comment by staticdev** [comment] 2019-06-30 14:55
@vrobinho You are right, I created a separate issue to address the storageclass scope for --wait:
https://github.com/helm/helm/issues/5958

**Comment by fredgate** [comment] 2019-08-07 12:47
helm (version 2.14.3) does not seem to wait that a deployment with one replica be ready.
The condition seems suspect :
```
func (c *Client) deploymentsReady(deployments []deployment) bool {
	for _, v := range deployments {
		if !(v.replicaSets.Status.ReadyReplicas >= *v.deployment.Spec.Replicas-deploymentutil.MaxUnavailable(*v.deployment)) {
			c.Log("Deployment is not ready: %s/%s", v.deployment.GetNamespace(), v.deployment.GetName())
			return false
		}
	}
	return true
}
```
With one replica, and a default maximum unavailability of 25% down rounded (i.e. one), the condition is always true, so helm does not wait for this deployment. There should be at least one replica that is ready.

**Comment by thomastaylor312** [comment] 2019-08-07 16:10
@fredgate It looks like it works just fine with Helm 3 right now, I haven't had chance to look at it for Helm 2. Would you mind opening an issue with the steps you used to reproduce?

**Comment by vkahawala** [comment] 2019-09-06 02:33
It works with v2.14.3, current stable.
We have added the rolling update strategy since we only have one replica.
```
    strategy:
      type: RollingUpdate
      rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
```

**Comment by zffocussss** [comment] 2020-01-14 10:48
same here.I have this issues. I have a readness probe in the deployment file.

- Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
- Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
- apiVersion: apps/v1beta1
- AKS  v1.14.6

**Comment by fredgate** [comment] 2020-03-09 10:55
I still have the problem with Helm 3.
I install a Helm chart (service catalog for example, but this is not important) with the flag `--wait` and helm terminates before pods are ready. The chart contains one deployment of one pod. The update strategy is set to type `RollingUpdate`.
The problem seems to be in function `deploymentReady` :
https://github.com/helm/helm/blob/ec1d1a3d3eb672232f896f9d3b3d0797e4f519e3/pkg/kube/wait.go#L221-L228
The deployment does not provide configuration for the rolling update so some default values are used. A `kubectl describe` show these values :
```
replicas: 1
strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```
The calculation of `expectedReady` variable in `deploymentReady` function gives a value of 0 as `replica` is 1 and `maxUnavailable` is also 1. So the condition `rs.Status.ReadyReplicas >= expectedReady` is always true, even when no pod are started yet.
I think that the variable `expectedReady` should have a minimum value of 1 if it is equal to 0.

**Comment by jcamu** [comment] 2021-01-15 10:00
Hello @thomastaylor312

I understand this issue is close but i have few interrogation about, maybe some misunderstanding  on my side

The wait option wait until the pods are ready according to rule Status.ReadyReplicas >= expectedReady
But how can we seperate the behaviour during the deployment and the expected final state.
For instance with a strategy like below

replicas: 2
strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

We accept to have a pod unavailable during deployment as one of another they will be restarted( for a zero downtime scenario) but we would like the deployment to be considered finished and ok only when all pods are up and ready.
If the two are not restarted correctly, the deployment should not be considered ok.

For now, we use 'kubectl rollous status' as it will wait until all pods are ready and if not the deployment will be rollback.

This behaviour is possible, planned ?

**Comment by dennis-yemelyanov** [comment] 2021-01-16 00:59
Also ran into the same issue, which took a few hours to debug. This was not intuitive at all since other services that had almost identical deployment pipeline worked great, the only difference was that they had replicas set to 2 instead of 1.

Is this issue closed as by design?

Is there any config to override this behavior and wait for at least one pod to be ready?

**Comment by haljin** [comment] 2021-08-25 12:59
It seems we have just run into this. A StatefulSet with just one replica and `podManagementPolicy: Parallel` doesn't wait and just moves on on version 3.6.3, but works and waits correctly 3.2.4. We can downgrade helm for now, but is there any open issue on this?

**Comment by haljin** [comment] 2021-08-25 13:44
Instead of necromancy I have made #10061

**Comment by grazius** [comment] 2021-09-09 07:35
with helm 3.4.2
i don't understand why helm still broken with this scenario ... maybe someone can explain ?

**First deployment with one replica**

```
  replicaCount: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```

**Second deployment with two replica**

```
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```

`wait.go:225: [debug] Deployment is not ready: ns/app. 0 out of 2 expected pods are ready
`

the upgrade stay in this state and the upgrade fail.

**with this another strategy no problem ... why ?**

```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
```
