### ISSUE TITLE
There are several warnings from golint during build

### ISSUE THREAD

**Issue by adshmh** [kubernetes/helm#3757] opened 2018-03-24 10:47 UTC
golint generates multiple warnings during build:

```
pkg/chartutil/chartfile.go:34:7:warning: const ApiVersionV1 should be APIVersionV1 (golint)
pkg/chartutil/files.go:214:6:warning: func ToJson should be ToJSON (golint)
pkg/chartutil/files.go:229:6:warning: func FromJson should be FromJSON (golint)
pkg/getter/httpgetter.go:30:1:warning: comment on exported type HttpGetter should be of the form "HttpGetter ..." (with optional leading article) (golint)
pkg/getter/httpgetter.go:31:6:warning: type HttpGetter should be HTTPGetter (golint)
pkg/getter/httpgetter.go:37:1:warning: exported method HttpGetter.SetCredentials should have comment or be unexported (golint)
pkg/repo/chartrepo.go:199:1:warning: comment on exported function FindChartInAuthRepoURL should be of the form "FindChartInAuthRepoURL ..." (golint)
pkg/repo/repo.go:34:6:warning: type name will be used as repo.RepoFile by other packages, and that stutters; consider calling this File (golint)
pkg/strvals/parser.go:53:1:warning: comment on exported function ParseString should be of the form "ParseString ..." (golint)
```

Two of the above (`ToJson` and `FromJson`) are already being addressed by PR #3753 .

**Comment by jascott1** [comment] 2018-03-26 20:41
Partial duplicate of #3747

**Comment by RyanHartje** [comment] 2018-03-26 21:54
A few of these are covered in #3747

**Comment by bacongobbler** [comment] 2018-03-27 20:08
re-opening until #3753 is merged, as not all the golint warnings have been removed yet :)

**Comment by bacongobbler** [comment] 2018-03-27 20:08
oh wait actually we can follow up with those in #3747. My bad!

**Closed by bacongobbler** 2018-03-27 20:08 UTC
Labels: bug
