### ISSUE TITLE
Helm dep up still not work for me in version 2.2.2

### ISSUE THREAD

**Issue by gaukler2** [kubernetes/helm#2125] opened 2017-03-16 13:21 UTC
I have seen also some other problems: 

**helm version**
E0316 15:30:30.778123   15702 portforward.go:209] Unable to create listener: Error listen tcp6 [::1]:35250: bind: cannot assign requested address
Client: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}

**helm serve**
Regenerating index. This may take a moment.
Now serving you on 127.0.0.1:8879

**helm dep up xyz**
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
Writing to /root/.helm/repository/cache/openstack-helm-index.yaml
...Successfully got an update from the "openstack-helm" chart repository
Writing to /root/.helm/repository/cache/stable-index.yaml
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts

Could you help ? 

BUT if i do **Helm serve** and open a new Putty window to the server and run **helm dep up xyz**  then it works. 
Maybe i do something wrong or i just missunderstand how it works.

**Comment by technosophos** [comment] 2017-03-16 18:52
Where are you running `helm serve` and where are you running `helm dep up`?

**Comment by gaukler2** [comment] 2017-03-16 20:11
i created a video 
http://www.rache.ch/helm/helm.mp4
It's everything on the same box

**Comment by bacongobbler** [comment] 2017-03-16 20:55
So the problem is that without the local repo running, you can't fetch updates? Does the `notesv01` chart rely on being fetched from the local repository server? Hoe does your requirements.yaml look?

**Comment by gaukler2** [comment] 2017-03-16 22:07
Yes from local. 
can i start the local repo as a service ?

**Comment by technosophos** [comment] 2017-03-17 19:44
Yes, you can start it as a service. Or you can just create your own repo.
https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md

**Comment by bacongobbler** [comment] 2017-03-17 19:48
So in terms of actionable items, this sounds like it's working as intended. Your chart relies on the local chart server to be running, and it fails to update when it's down.

Is there some documentation that we can include that can help make this clearer, or does the doc @technosophos pointed out clear things up for you? If so I think we can close this.

**Comment by bacongobbler** [comment] 2017-10-31 20:43
closing as inactive.

**Closed** 2017-10-31 20:43 UTC
Labels: question/support
