### ISSUE TITLE
Cannot detect VCS

### ISSUE THREAD

**Issue by fedya** [kubernetes/helm#2466] opened 2017-05-18 10:18 UTC
trying to build helm from source

1. wget https://github.com/kubernetes/helm/archive/v2.4.2.zip
2. unzip v2.4.2.zip
3. cd helm-2.4.2/
4. make bootstrap build

```
[WARN]  The name listed in the config file (k8s.io/helm) does not match the current location (.)
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Found desired version locally bitbucket.org/ww/goautoneg 75cd24fc2f2c2a2088577d12123ddee5f54e0675!
[INFO]  --> Found desired version locally cloud.google.com/go 3b1ae45394a234c385be014e9a488f2bb6eef821!
[INFO]  --> Found desired version locally github.com/aokoli/goutils 9c37978a95bd5c709a15883b6242714ea6709e64!
[INFO]  --> Found desired version locally github.com/asaskevich/govalidator 7664702784775e51966f0885f5cd27435916517b!
[INFO]  --> Found desired version locally github.com/Azure/go-ansiterm 70b2c90b260171e829f1ebd7c17f600c11858dbe!
[INFO]  --> Found desired version locally github.com/beorn7/perks 3ac7bf7a47d159a033b107610db8a1b6575507a4!
[INFO]  --> Found desired version locally github.com/BurntSushi/toml b26d9c308763d68093482582cea63d69be07a0f0!
[INFO]  --> Found desired version locally github.com/chai2010/gettext-go bf70f2a70fb1b1f36d90d671a72795984eab0fcb!
[INFO]  --> Found desired version locally github.com/coreos/go-oidc be73733bb8cc830d0205609b95d125215f8e9c70!
[INFO]  --> Found desired version locally github.com/coreos/pkg fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8!
[INFO]  --> Found desired version locally github.com/cpuguy83/go-md2man a65d4d2de4d5f7c74868dfa9b202a3c8be315aaa!
[INFO]  --> Found desired version locally github.com/davecgh/go-spew 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d!
[INFO]  --> Found desired version locally github.com/dgrijalva/jwt-go 01aeca54ebda6e0fbfafd0a524d234159c05ec20!
[INFO]  --> Found desired version locally github.com/docker/distribution cd27f179f2c10c5d300e6d09025b538c475b0d51!
[INFO]  --> Found desired version locally github.com/docker/docker b9f10c951893f9a00865890a5232e85d770c1087!
[INFO]  --> Found desired version locally github.com/docker/engine-api dea108d3aa0c67d7162a3fd8aa65f38a430019fd!
[INFO]  --> Found desired version locally github.com/docker/go-connections f549a9393d05688dff0992ef3efd8bbe6c628aeb!
[INFO]  --> Found desired version locally github.com/docker/go-units e30f1e79f3cd72542f2026ceec18d3bd67ab859c!
[INFO]  --> Found desired version locally github.com/docker/spdystream 449fdfce4d962303d702fec724ef0ad181c92528!
[INFO]  --> Found desired version locally github.com/emicklei/go-restful 09691a3b6378b740595c1002f40c34dd5f218a22!
[INFO]  --> Found desired version locally github.com/evanphx/json-patch ba18e35c5c1b36ef6334cad706eb681153d2d379!
[INFO]  --> Found desired version locally github.com/exponent-io/jsonpath d6023ce2651d8eafb5c75bb0c7167536102ec9f5!
[INFO]  --> Found desired version locally github.com/facebookgo/symwalk 42004b9f322246749dd73ad71008b1f3160c0052!
[INFO]  --> Found desired version locally github.com/ghodss/yaml 73d445a93680fa1a78ae23a5839bad48f32ba1ee!
[INFO]  --> Found desired version locally github.com/go-openapi/jsonpointer 46af16f9f7b149af66e5d1bd010e3574dc06de98!
[INFO]  --> Found desired version locally github.com/go-openapi/jsonreference 13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272!
[INFO]  --> Found desired version locally github.com/go-openapi/spec 6aced65f8501fe1217321abf0749d354824ba2ff!
[INFO]  --> Found desired version locally github.com/go-openapi/swag 1d0bd113de87027671077d3c71eb3ac5d7dbba72!
[INFO]  --> Found desired version locally github.com/gobwas/glob bea32b9cd2d6f55753d94a28e959b13f0244797a!
[INFO]  --> Found desired version locally github.com/gogo/protobuf c0656edd0d9eab7c66d1eb0c568f9039345796f7!
[INFO]  --> Found desired version locally github.com/golang/glog 44145f04b68cf362d9c4df2182967c2275eaefed!
[INFO]  --> Found desired version locally github.com/golang/groupcache 02826c3e79038b59d737d3b1c0a1d937f71a4433!
[INFO]  --> Found desired version locally github.com/golang/protobuf 2bba0603135d7d7f5cb73b2125beeda19c09f4ef!
[INFO]  --> Found desired version locally github.com/google/gofuzz 44d81051d367757e1c7c6a5a86423ece9afcf63c!
[INFO]  --> Found desired version locally github.com/gosuri/uitable 36ee7e946282a3fb1cfecd476ddc9b35d8847e42!
[INFO]  --> Found desired version locally github.com/grpc-ecosystem/go-grpc-prometheus 34abd90a014618f61222a1b0a7b7eb834a2d0dc3!
[INFO]  --> Found desired version locally github.com/howeyc/gopass 3ca23474a7c7203e0a0a070fd33508f6efdb9b3d!
[INFO]  --> Found desired version locally github.com/imdario/mergo 6633656539c1639d9d78127b7d47c622b5d7b6dc!
[INFO]  --> Found desired version locally github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75!
[INFO]  --> Found desired version locally github.com/jonboulle/clockwork 72f9bd7c4e0c2a40055ab3d0f09654f730cce982!
[INFO]  --> Found desired version locally github.com/juju/ratelimit 77ed1c8a01217656d2080ad51981f6e99adaa177!
[INFO]  --> Found desired version locally github.com/mailru/easyjson d5b7844b561a7bc640052f1b935f7b800330d7e0!
[INFO]  --> Found desired version locally github.com/Masterminds/semver 3f0ab6d4ab4bed1c61caf056b63a6e62190c7801!
[INFO]  --> Found desired version locally github.com/Masterminds/sprig 9526be0327b26ad31aa70296a7b10704883976d5!
[INFO]  --> Found desired version locally github.com/Masterminds/vcs 3084677c2c188840777bff30054f2b553729d329!
[INFO]  --> Found desired version locally github.com/mattn/go-runewidth d6bea18f789704b5f83375793155289da36a3c7f!
[INFO]  --> Found desired version locally github.com/matttproud/golang_protobuf_extensions fc2b8d3a73c4867e51861bbdd5ae3c1f0869dd6a!
[INFO]  --> Found desired version locally github.com/mitchellh/go-wordwrap ad45545899c7b13c020ea92b2072220eefad42b8!
[INFO]  --> Found desired version locally github.com/naoina/go-stringutil 6b638e95a32d0c1131db0e7fe83775cbea4a0d0b!
[INFO]  --> Found desired version locally github.com/pborman/uuid ca53cad383cad2479bbba7f7a1a05797ec1386e4!
[INFO]  --> Found desired version locally github.com/prometheus/client_golang c5b7fccd204277076155f10851dad72b76a49317!
[INFO]  --> Found desired version locally github.com/prometheus/client_model fa8ad6fec33561be4280a8f0514318c79d7f6cb6!
[INFO]  --> Found desired version locally github.com/prometheus/common ffe929a3f4c4faeaa10f2b9535c2b1be3ad15650!
[INFO]  --> Found desired version locally github.com/prometheus/procfs 454a56f35412459b5e684fd5ec0f9211b94f002a!
[INFO]  --> Found desired version locally github.com/PuerkitoBio/purell 8a290539e2e8629dbc4e6bad948158f790ec31f4!
[INFO]  --> Found desired version locally github.com/PuerkitoBio/urlesc 5bd2802263f21d8788851d5305584c82a5c75d7e!
[INFO]  --> Found desired version locally github.com/russross/blackfriday 300106c228d52c8941d4b3de6054a6062a86dda3!
[INFO]  --> Found desired version locally github.com/satori/go.uuid 879c5887cd475cd7864858769793b2ceb0d44feb!
[INFO]  --> Found desired version locally github.com/shurcooL/sanitized_anchor_name 10ef21a441db47d8b13ebcc5fd2310f636973c77!
[INFO]  --> Found desired version locally github.com/Sirupsen/logrus 51fe59aca108dc5680109e7b2051cbdcfa5a253c!
[INFO]  --> Found desired version locally github.com/spf13/cobra f62e98d28ab7ad31d707ba837a966378465c7b57!
[INFO]  --> Found desired version locally github.com/spf13/pflag 9ff6c6923cfffbcd502984b8e0c80539a94968b7!
[INFO]  --> Found desired version locally github.com/technosophos/moniker 9f956786b91d9786ca11aa5be6104542fa911546!
[INFO]  --> Found desired version locally github.com/ugorji/go ded73eae5db7e7a0ef6f55aace87a2873c5d2b74!
[INFO]  --> Found desired version locally golang.org/x/crypto d172538b2cfce0c13cee31e647d0367aa8cd2486!
[INFO]  --> Found desired version locally golang.org/x/net e90d6d0afc4c315a0d87a568ae68577cc15149a0!
[INFO]  --> Found desired version locally golang.org/x/oauth2 3c3a985cb79f52a3190fbc056984415ca6763d01!
[INFO]  --> Found desired version locally golang.org/x/sys 8f0908ab3b2457e2e15403d3697c9ef5cb4b57a9!
[INFO]  --> Found desired version locally golang.org/x/text 2910a502d2bf9e43193af9d68ca516529614eed3!
[INFO]  --> Found desired version locally google.golang.org/appengine 4f7eeb5305a4ba1966344836ba4af9996b7b4e05!
[INFO]  --> Found desired version locally google.golang.org/grpc 8050b9cbc271307e5a716a9d782803d09b0d6f2d!
[INFO]  --> Found desired version locally gopkg.in/inf.v0 3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4!
[INFO]  --> Found desired version locally gopkg.in/yaml.v2 53feefa2559fb8dfa8d81baad31be332c97d6c77!
[INFO]  --> Found desired version locally k8s.io/apimachinery fbd6803372f831e58b86c78d07421637a64ad768!
[INFO]  --> Found desired version locally k8s.io/apiserver 2308857ad3b8b18abf74ff734853973eda9da94d!
[INFO]  --> Found desired version locally k8s.io/client-go 5b0e11b577b35539f05523c47e94ed96a17f992b!
[INFO]  --> Found desired version locally k8s.io/kubernetes 0480917b552be33e2dba47386e51decb1a211df6!
[INFO]  --> Fetching vbom.ml/util.
[INFO]  --> Fetching github.com/huandu/xstrings.
[WARN]  Unable to checkout vbom.ml/util
[ERROR] Update failed for vbom.ml/util: Cannot detect VCS
[ERROR] Failed to install: Cannot detect VCS
```

**Comment by technosophos** [comment] 2017-05-18 16:27
Ugh... I should have cherry-picked the fix for that.

Here's the change you need to make to `glide.yaml`. Then do `glide up && make bootstrap`:

https://github.com/kubernetes/helm/blob/master/glide.yaml#L53-L55

**Comment by bacongobbler** [comment] 2017-05-18 17:14
Since this has been fixed in master I think this is good to close, eh?

**Comment by bacongobbler** [comment] 2017-10-31 23:28
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Closed** 2017-10-31 23:28 UTC
Labels: question/support

**Comment by subbu05** [comment] 2018-06-06 18:16
Resolved the issue. After going though the Glide code understood the root cause. Its not the glide issue. Glide must have flag to ignore server certificates.
Solution: Get Common CA certificates
Ubuntu - https://launchpad.net/ubuntu/xenial/+package/ca-certificates
Similarly search for other OS and install and try.

**Comment by bacongobbler** [comment] 2018-08-13 14:29
@iamsharife can you share more details on the issue you're describing? Thanks!

**Comment by jchauncey** [comment] 2020-09-11 15:30
Trying to build v2.16.10 and I am seeing this same issue and other issues running `make boostrap`

**Comment by bridgetkromhout** [comment] 2020-09-11 15:56
Hi, @jchauncey - as Helm v2 is no longer being updated and will soon be out of support entirely, we suggest you use Helm v3: https://helm.sh/blog/helm-v2-deprecation-timeline/ - we will not be making any bugfixes to v2.

If you see a problem with Helm v3, please do open a new issue. Thanks!
