### ISSUE TITLE
Upgrade fails when adding a new label

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#2493] opened 2017-05-25 09:39 UTC
**Helm Versions**

```
kviberg $ helm version
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
```

**Output**

```
kviberg $ helm upgrade --install efritin tmp/charts/staging/efritin --kube-context af.k8s.saltside.net -f secrets.yaml --namespace production
Error: UPGRADE FAILED: Deployment.extensions "efritin-efritin-core-service-thrift" is invalid: spec.template.metadata.labels: Invalid value: {"app":"efritin-efritin","chart":"efritin-0.1.0-rc6-production.g4b59386","component":"core_service","market":"efritin","release":"efritin","source":"kviberg","stage":"production","tier":"thrift"}: `selector` does not match template `labels`
```

(note some of the output is snipped since the same error repeats for ~10 deployments).

**Notes**

We've gotten this same error for a few reasons, but I'm not entirely sure _why_ it occurs. We added a new label to everything in the chart (for metric collection purposes) then this happened.

**Comment by adamreese** [comment] 2017-05-25 16:31
Looks like it could be related to this upstream discussion https://github.com/kubernetes/kubernetes/issues/26202

**Comment by seh** [comment] 2017-05-25 17:02
This sounds related to #2494—in particular, [my comment there](https://github.com/kubernetes/helm/issues/2494#issuecomment-304058863).

**Comment by acondrat** [comment] 2017-06-01 11:40
Run into the same issue. Is there a workaround other then re-installing the release?

**Comment by bacongobbler** [comment] 2017-10-31 23:49
There is no way to workaround other than delete/reinstall, sadly. upstream doesn't want you to change label selectors after the initial release, and we have no control over that. We're going to have to close this as "working as intended", unfortunately. Sorry!

**Closed by bacongobbler** 2017-10-31 23:49 UTC
Labels: question/support
