### ISSUE TITLE
error: group map[...] is already registered

### ISSUE THREAD

**Issue by janwillies** [kubernetes/helm#1589] opened 2016-11-25 13:13 UTC
When trying to install a chart, tiller dies with the following error:
```
$ helm install --namespace=infra infra/charts/ingress/ --name nginx-ingress

Tiller is listening on :44134
Probes server is listening on :44135
Storage driver is ConfigMap
2016-11-25 13:04:46.387816 I | storage.go:94: Listing all releases with filter
2016-11-25 13:04:54.636425 I | storage.go:133: Getting release history for 'nginx-ingress'
2016-11-25 13:04:54.646510 I | release_server.go:862: Executing pre-install hooks for nginx-ingress
2016-11-25 13:04:54.646533 I | release_server.go:889: Hooks complete for pre-install nginx-ingress
2016-11-25 13:04:54.646539 I | storage.go:133: Getting release history for 'nginx-ingress'
error: group map[certificates.k8s.io:0xc420448380 rbac.authorization.k8s.io:0xc4203aa150 storage.k8s.io:0xc4203aa1c0 federation:0xc4203aa380 apps:0xc4203abf10 autoscaling:0xc420448150 batch:0xc420448310 componentconfig:0xc4204483f0 extensions:0xc4203aa070 policy:0xc4203aa0e0 :0xc4203abea0 authentication.k8s.io:0xc4203abf80 authorization.k8s.io:0xc4204480e0] is already registered
```

`helm ls` works, but returns nothing obviously. `helm version` also works.

I'm running `kubernetes-1.5.0-beta.2` in `ABAC` mode. The kube-system namespace has the following permissions:

```
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"system:serviceaccount:kube-system:default","namespace":"*","resource":"*","apiGroup":"*"}}
```

**Comment by intlabs** [comment] 2016-11-25 16:09
I'm also seeing the same issue with kubernetes-1.5.0-beta.1

**Comment by technosophos** [comment] 2016-11-29 18:13
@intlabs are you also using ABAC?

**Comment by janwillies** [comment] 2016-11-30 09:34
I've been using the same ABAC setup with `kube-1.3` and tiller worked fine. Just not on 1.5

**Comment by intlabs** [comment] 2016-11-30 18:43
@technosophos, actually no sorry - I should have been clearer.

We are deploying kube via kubectl with the standard configuration. It would be great to get to to the bottom of this though, as I am building the development environment for Kolla-Kubernetes Helm implementation and we need to use k8s 1.5 for dynamic Ceph PVC's and StatefullSet support.

**Comment by janwillies** [comment] 2016-12-01 12:02
@technosophos any pointers where to start looking?

**Comment by v1k0d3n** [comment] 2016-12-01 15:18
@technosophos this relates to the issue i brought up over slack. if it helps, the repo we've been using (that exposed this issue for us) is https://github.com/att-comdev/halcyon-vagrant-kubernetes.

you can use that as a testbed, since all the versioning is optionally configurable. i know you mentioned that you couldn't reproduce...maybe this would help?

**Comment by technosophos** [comment] 2016-12-01 23:54
I think we're going to have to test out switching the Kubernetes library we use from 1.4.x o 1.5.0-beta and try it. We seem to be hitting some sort of version mismatch.

**Comment by enisoc** [comment] 2016-12-02 19:27
This looks similar to https://github.com/kubernetes/kubernetes/issues/35791.

**Comment by technosophos** [comment] 2016-12-05 18:51
We are now working through several issues with the K8s 1.5 release, but I think that switch will fix this error.

**Comment by intlabs** [comment] 2016-12-05 19:36
@technosophos, brilliant - thanks for keeping us updated with your progress :)

**Comment by adamreese** [comment] 2016-12-14 00:36
1.5 support in now merged

**Closed by adamreese** 2016-12-14 00:36 UTC
Labels: support
