### ISSUE TITLE
Helm 2.9.0 will not install charts on Minikube

### ISSUE THREAD

**Issue by jim-barber-he** [kubernetes/helm#4000] opened 2018-05-01 02:47 UTC
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

`minikube version: v0.26.1`

If I bring up a fresh copy of minikube and run `helm init --wait` all seems to be fine.
But then if I go to install a chart it fails.
Here is an example of trying to install the stable Memcached chart via the upgrade command and with debug turned on:

```
$ helm --debug upgrade -i heweb-cache stable/memcached --version 2.0.4 --namespace default --set pdbMinAvailable=1,replicaCount=1 --kube-context minikube
[debug] Created tunnel using local port: '41101'

[debug] SERVER: "127.0.0.1:41101"

[debug] Fetched stable/memcached to /home/jim/.helm/cache/archive/memcached-2.0.4.tgz

Error: UPGRADE FAILED: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)heweb-cache%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 127.0.0.1:8080: connect: connection refused
```

And here is an example of just using the install command with debug:

```
$ helm --debug install -n heweb-cache stable/memcached --version 2.0.4 --namespace default --set pdbMinAvailable=1,replicaCount=1 --kube-context minikube
[debug] Created tunnel using local port: '36935'

[debug] SERVER: "127.0.0.1:36935"

[debug] Original chart version: "2.0.4"
[debug] Fetched stable/memcached to /home/jim/.helm/cache/archive/memcached-2.0.4.tgz

[debug] CHART PATH: /home/jim/.helm/cache/archive/memcached-2.0.4.tgz

Error: Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: connect: connection refused
```

The above works with no error when using helm version 2.8.2.
I'm running on a Debian Linux system with the virtualbox package installed (in case any of that matters).

**Comment by bacongobbler** [comment] 2018-05-01 13:40
Dupe of #3985.

**Closed by bacongobbler** 2018-05-01 13:40 UTC
