### ISSUE TITLE
Error running helm install 

### ISSUE THREAD

**Issue by moshe0076** [kubernetes/helm#1591] opened 2016-11-26 16:09 UTC
helm version
Client: &version.Version{SemVer:"v2.0.0", GitCommit:"51bdad42756dfaf3234f53ef3d3cb6bcd94144c2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0", GitCommit:"51bdad42756dfaf3234f53ef3d3cb6bcd94144c2", GitTreeState:"clean"}

when running helm install stable/redis
I get:
Fetched stable/redis to redis-0.4.1.tgz
Error: transport is closing

And in the pod logs:
2016-11-26T16:06:35.059875388Z Tiller is listening on :44134
2016-11-26T16:06:35.059904266Z Probes server is listening on :44135
2016-11-26T16:06:35.059909117Z Storage driver is ConfigMap
2016-11-26T16:07:01.332974355Z Cannot initialize Kubernetes connection: Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refused2016-11-26 16:07:01.332867 I | storage.go:37: Getting release "operatic-jellyfish" (v1) from storage
2016-11-26T16:07:01.336020866Z panic: runtime error: invalid memory address or nil pointer dereference
2016-11-26T16:07:01.336034627Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8053d5]
2016-11-26T16:07:01.336038393Z 
2016-11-26T16:07:01.336042658Z goroutine 44 [running]:
2016-11-26T16:07:01.336045471Z panic(0x1abbfc0, 0xc42000a030)
2016-11-26T16:07:01.336048347Z 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2016-11-26T16:07:01.336051815Z k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/unversioned.(*ConfigMaps).Get(0xc420012ac0, 0xc4200c9080, 0x15, 0x1ca7431, 0x6, 0xc4202cd6a0)
2016-11-26T16:07:01.336055337Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/client/unversioned/configmap.go:58 +0x75
2016-11-26T16:07:01.336058584Z k8s.io/helm/pkg/storage/driver.(*ConfigMaps).Get(0xc42029c9a0, 0xc4200c9080, 0x15, 0xc4200c9080, 0x15, 0xc4200c9040)
2016-11-26T16:07:01.336061815Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/driver/cfgmaps.go:69 +0x62
2016-11-26T16:07:01.336065023Z k8s.io/helm/pkg/storage.(*Storage).Get(0xc42029c9b0, 0xc4200c9040, 0x12, 0xc400000001, 0x12, 0x0, 0xc42029b880)
2016-11-26T16:07:01.336067947Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:38 +0x160
2016-11-26T16:07:01.336070908Z k8s.io/helm/pkg/tiller.(*ReleaseServer).uniqName(0xc4200223a0, 0x0, 0x0, 0xc4202cd800, 0xd66a13, 0xc420151d80, 0xc420197310, 0xc4202cf101)
2016-11-26T16:07:01.336073854Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:577 +0xd7
2016-11-26T16:07:01.336076794Z k8s.io/helm/pkg/tiller.(*ReleaseServer).prepareRelease(0xc4200223a0, 0xc420196c30, 0xc42006ef01, 0xc4200d91d0, 0xc4202b2000)
2016-11-26T16:07:01.336079805Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:630 +0x71
2016-11-26T16:07:01.336082754Z k8s.io/helm/pkg/tiller.(*ReleaseServer).InstallRelease(0xc4200223a0, 0x7fcf598f3768, 0xc4202b0930, 0xc420196c30, 0x0, 0x22b6, 0x22b6)
2016-11-26T16:07:01.336085587Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:604 +0x78
2016-11-26T16:07:01.336088906Z k8s.io/helm/pkg/proto/hapi/services._ReleaseService_InstallRelease_Handler(0x1c51f80, 0xc4200223a0, 0x7fcf598f3768, 0xc4202b0930, 0xc420196be0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016-11-26T16:07:01.336091894Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:747 +0x27d
2016-11-26T16:07:01.336094790Z k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4202b2000, 0x28610a0, 0xc42006efc0, 0xc4200d91d0, 0xc42014cf00, 0x288cbe8, 0xc4202b0900, 0x0, 0x0)
2016-11-26T16:07:01.336097882Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:608 +0xc50
2016-11-26T16:07:01.336109334Z k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4202b2000, 0x28610a0, 0xc42006efc0, 0xc4200d91d0, 0xc4202b0900)
2016-11-26T16:07:01.336112580Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:766 +0x6b0
2016-11-26T16:07:01.336115593Z k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4202cedc0, 0xc4202b2000, 0x28610a0, 0xc42006efc0, 0xc4200d91d0)
2016-11-26T16:07:01.336118455Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:419 +0xab
2016-11-26T16:07:01.336123430Z created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2016-11-26T16:07:01.336126315Z 	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:420 +0xa3

**Comment by technosophos** [comment] 2016-11-29 18:09
This almost always means that Tiller cannot access the Kubernetes API server. What can you tell us about the Kubernetes configuration? (minikube? GKS?) Do other operations (like `helm ls`) work?

**Comment by moshe0076** [comment] 2016-11-30 20:07
Hi,

The installation is a custom one running as a single node for dev purpose on an EC2 instance. 
What is strange it that helm init works and deploys Tiller on the cluster. But when running:
```
# helm ls --debug
Created tunnel using local port: '42570'
SERVER: ":42570"
Error: transport is closing
 
```
And the container crushes with the error I wrote before.
Is there a way to configure the API server?

Thanks!!!

**Comment by technosophos** [comment] 2016-12-01 23:58
So this is the root of the error:

```
2016-11-26T16:07:01.332974355Z Cannot initialize Kubernetes connection: Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refused2016-11-26 
```

What's happening is that Tiller cannot connect to the Kubernetes API server. This may be that the pod's environment variables are not correct, or that there is a problem inside of the networking setup for Kubernetes, or that there is a security rule preventing Tiller's pod from contacting the API server.

One way to do some manual testing is to use `kubectl exec` to start an interactive shell on the Tiller pod, then get `kubectl` installed there and see if you can connect to Kube API with `kubectl`. Actually, for that you can also use curl.

You can also inspect the environment variables and see whether the KUBE_ server and port variables are being set correctly.

**Comment by moshe0076** [comment] 2016-12-04 07:24
Hi,
The environment variables I get are:
"Env": [
                "KUBERNETES_DASHBOARD_PORT_80_TCP_PROTO=tcp",
                "KUBERNETES_SERVICE_PORT=443",
                "KUBERNETES_SERVICE_PORT_HTTPS=443",
                "KUBERNETES_PORT=tcp://192.168.0.1:443",
                "KUBERNETES_PORT_443_TCP_ADDR=192.168.0.1",
                "KUBERNETES_DASHBOARD_PORT=tcp://192.168.221.41:80",
                "KUBERNETES_DASHBOARD_PORT_80_TCP=tcp://192.168.221.41:80",
                "KUBERNETES_DASHBOARD_PORT_80_TCP_ADDR=192.168.221.41",
                "KUBERNETES_SERVICE_HOST=192.168.0.1",
                "KUBERNETES_DASHBOARD_SERVICE_HOST=192.168.221.41",
                "KUBERNETES_DASHBOARD_SERVICE_PORT=80",
                "KUBERNETES_DASHBOARD_PORT_80_TCP_PORT=80",
                "KUBERNETES_PORT_443_TCP_PROTO=tcp",
                "KUBERNETES_PORT_443_TCP_PORT=443",
                "KUBERNETES_PORT_443_TCP=tcp://192.168.0.1:443",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
I think I need to pass the KUBE_MASTER somehow to the pod. What is the environment variable that set the Kubernetes api url and port so it will overwrite the  http://localhost:8080/api that I get by default?
How can I pass it to the Pod when I do helm init?

Thanks!!

**Comment by technosophos** [comment] 2016-12-05 18:48
I believe it _should_ be using `https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT_HTTPS` to contact the API. So you shouldn't have to do anything.

Have you tried hitting that endpoint with either `kubectl` or `curl` from the Tiller pod?

**Comment by bacongobbler** [comment] 2016-12-13 19:50
Hmm, I have been trying at least three times to get helm working with v1.5.0. All fail with this:

```
><> helm install deis/workflow --namespace deis
Fetched deis/workflow to workflow-v2.9.0.tgz
Error: transport is closing
```

I'll see what I can find inside the tiller pod.

**Comment by bacongobbler** [comment] 2016-12-13 19:55
Not entirely sure if this is relevant, but there seems to be an error from the previous pod:

```
><> k --namespace=kube-system logs tiller-deploy-2516972252-s8cr4 -p
Tiller is listening on :44134
Probes server is listening on :44135
Storage driver is ConfigMap
2016-12-13 19:47:51.146249 I | storage.go:37: Getting release "idolized-vulture" (v1) from storage
2016-12-13 19:47:53.568440 I | hooks.go:118: info: manifest "workflow/charts/registry-token-refresher/templates/registry-secret.yaml" is empty. Skipping.
2016-12-13 19:47:53.572001 I | hooks.go:118: info: manifest "workflow/charts/registry-token-refresher/templates/registry-token-refresher-deployment.yaml" is empty. Skipping.
2016-12-13 19:47:53.575793 I | hooks.go:118: info: manifest "workflow/charts/monitor/charts/influxdb/templates/monitor-influxdb-creds-secret.yaml" is empty. Skipping.
2016-12-13 19:47:53.577372 I | release_server.go:873: Executing pre-install hooks for idolized-vulture
error: group map[apps:0xc4203b9f10 authentication.k8s.io:0xc4203b9f80 authorization.k8s.io:0xc4204540e0 autoscaling:0xc420454150 batch:0xc420454310 certificates.k8s.io:0xc420454380 componentconfig:0xc4204543f0 :0xc4203b9ea0 storage.k8s.io:0xc4203b81c0 federation:0xc4203b8380 policy:0xc4203b80e0 rbac.authorization.k8s.io:0xc4203b8150 extensions:0xc4203b8070] is already registered
><> k --namespace=kube-system get po
NAME                                    READY     STATUS    RESTARTS   AGE
heapster-v1.2.0-4001981223-km432        4/4       Running   0          54m
kube-dns-4101612645-35hhb               4/4       Running   0          1h
kube-proxy-kubernetes-node-1            1/1       Running   0          55m
kubernetes-dashboard-3543765157-kwj20   1/1       Running   0          1h
monitoring-influxdb-grafana-v4-396fs    2/2       Running   0          1h
tiller-deploy-2516972252-s8cr4          1/1       Running   1          5m
```

If I try `helm install deis/workflow --namespace deis` again, tiller crashes again with the same error. The current pod's logs look like

```
><> k --namespace=kube-system logs tiller-deploy-2516972252-s8cr4
Tiller is listening on :44134
Probes server is listening on :44135
Storage driver is ConfigMap
2016-12-13 19:54:31.801420 I | storage.go:94: Listing all releases with filter
```

and no release exists in tiller when I run `helm list`.

**Comment by bacongobbler** [comment] 2016-12-13 20:02
FYI this also failed in the exact same way with the `stable/jenkins` chart, so it doesn't seem to be specific to the chart. I'll see if I can reproduce on k8s v1.4.6.

**Comment by bacongobbler** [comment] 2016-12-14 06:01
I can confirm that everything works for me with kubernetes v1.5.1 and helm v2.1.0. Nicely done team :)

**Comment by ahawkins** [comment] 2016-12-14 07:38
@technosophos you can close this :bow:

**Comment by technosophos** [comment] 2016-12-19 21:21
Thanks

**Closed by technosophos** 2016-12-19 21:21 UTC
Labels: support
