### ISSUE TITLE
Errors about missing CustomResourceDefinition that exists?

### ISSUE THREAD

**Issue by jeffutter** [kubernetes/helm#3483] opened 2018-02-09 15:51 UTC
I'm running into some strange error where I can no longer upgrade my deployment. When I try to `helm upgrade` it says that certain resource definition doesn't exist. But you can clearly see when I use `kubectl` it does.

```
❯❯❯ helm upgrade "master-ingress" master-ingress -i --timeout 600 --set "ingress.domain=myapp-dev.com" --set "ingress.target=blue"
Error: UPGRADE FAILED: no CustomResourceDefinition with the name "certificates.certmanager.k8s.io" found
❯❯❯ kubectl get customresourcedefinition
NAME                                AGE
certificates.certmanager.k8s.io     1d
clusterissuers.certmanager.k8s.io   1d
issuers.certmanager.k8s.io          1d
```

This is a chart that has `cert-manager` as a requirement.

Any ideas or suggestions on what information to collect to debug further?

**Comment by bacongobbler** [comment] 2018-02-09 16:44
closing as s duplicate of https://github.com/kubernetes/helm/issues/3275.

**Closed by bacongobbler** 2018-02-09 16:44 UTC

**Comment by jeffutter** [comment] 2018-02-09 16:46
@bacongobbler Thanks for finding that issue! I'll watch over there
