### ISSUE TITLE
[Question]Tiller connect to localhost for kubernetes API

### ISSUE THREAD

**Issue by JakimLi** [kubernetes/helm#2872] opened 2017-08-29 01:48 UTC
After `helm init`, I can see tiller pod is running, I can do `helm version` but I cannot do `helm ls`.

```
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
```

the error message which also shows in tiller pod's log:
```
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

Seems that it's trying to connect to 127.0.0.1, but the tiller pod is running in one of my node, it will never access kubernetes api at 127.0.0.1, even if it runs on master, it will be in a pod, I don't think 127.0.0.1 will be the place to query config maps.

So the question is why tiller/helm try to connect 127.0.0.1, what can I do for it?

**Comment by jascott1** [comment] 2017-08-29 20:45
@JakimLi I would try to land it on master and see if it works first. 

@bacongobbler Do you remember the solution for this? I hit it way back but think I just landed Tiller on master...

**Comment by bacongobbler** [comment] 2017-08-29 21:20
I believe client-go connects to the kubernetes API through KUBERNETES_SERVICE_HOST within the container, if I recall correctly. Usually this is due to a misconfigured Kubernetes cluster. Let me see if I can pull up client-go's source code.

**Comment by bacongobbler** [comment] 2017-08-29 21:21
yup. https://github.com/kubernetes/client-go/blob/9675d048204baf818bb24f7c74d0e64f6254902e/rest/config.go#L306-L311

@JakimLi how did you set up your cluster?

**Comment by JakimLi** [comment] 2017-08-30 04:46
@bacongobbler the cluster is built from scratch on CentOS.
```
>>> kubectl get services | grep kubernetes                       
kubernetes                   172.16.0.1       <none>        443/TCP           7d
```

And when sh into tiller pod, I can see:
```
››› kubectl exec tiller-deploy-757398655-9nrnz -it sh  --namespace kube-system
...
export KUBERNETES_SERVICE_HOST='172.16.0.1'
export KUBERNETES_SERVICE_PORT='443'
...
```

I also setup kubernetes dashboard which also uses the apiserver I think, and it works fine. I will try to land the tiller pod on master as @jascott1 suggested.

**Comment by JakimLi** [comment] 2017-08-31 02:00
tried to land the tiller pod on master, same error, any help will be appreciated.

**Comment by bacongobbler** [comment] 2017-08-31 04:43
> ››› kubectl exec tiller-deploy-757398655-9nrnz -it sh  --namespace kube-system
> ...
> export KUBERNETES_SERVICE_HOST='172.16.0.1'
> export KUBERNETES_SERVICE_PORT='443'
> ...

Curious, but where/how did you get these `export` statements? If you can provide instructions on what instructions you were using to set up your cluster as well as the commands you ran inside the tiller container to get those `export` statements, that might help.

For what it's worth, here's what I have in my tiller environment along with logs. See if anything jumps out at you when comparing against your tiller pod's environment.

I would also suggest running `env` directly instead of looting around the container. It gives you a more accurate representation of what envvars were present when tiller was booted.

```
><> kk exec tiller-deploy-3864618634-hwsgt env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=tiller-deploy-3864618634-hwsgt
TILLER_NAMESPACE=kube-system
REGISTRY_SERVICE_PORT=80
REGISTRY_PORT_80_TCP_ADDR=10.0.0.206
TILLER_DEPLOY_PORT_44134_TCP=tcp://10.0.0.238:44134
KUBERNETES_SERVICE_HOST=10.0.0.1
KUBERNETES_DASHBOARD_PORT_80_TCP_PORT=80
KUBE_DNS_SERVICE_PORT_DNS=53
KUBE_DNS_PORT_53_UDP_PORT=53
TILLER_DEPLOY_PORT_44134_TCP_ADDR=10.0.0.238
DEFAULT_HTTP_BACKEND_PORT_80_TCP_PROTO=tcp
KUBE_DNS_PORT=udp://10.0.0.10:53
TILLER_DEPLOY_SERVICE_HOST=10.0.0.238
TILLER_DEPLOY_PORT=tcp://10.0.0.238:44134
DEFAULT_HTTP_BACKEND_PORT=tcp://10.0.0.245:80
DEFAULT_HTTP_BACKEND_PORT_80_TCP=tcp://10.0.0.245:80
KUBE_DNS_PORT_53_UDP_PROTO=udp
KUBE_DNS_PORT_53_TCP=tcp://10.0.0.10:53
KUBERNETES_SERVICE_PORT=443
KUBERNETES_DASHBOARD_SERVICE_HOST=10.0.0.29
KUBERNETES_DASHBOARD_SERVICE_PORT=80
KUBERNETES_DASHBOARD_PORT_80_TCP_ADDR=10.0.0.29
REGISTRY_PORT_80_TCP=tcp://10.0.0.206:80
KUBE_DNS_PORT_53_UDP_ADDR=10.0.0.10
KUBE_DNS_PORT_53_TCP_ADDR=10.0.0.10
REGISTRY_SERVICE_HOST=10.0.0.206
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT=tcp://10.0.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443
DEFAULT_HTTP_BACKEND_SERVICE_HOST=10.0.0.245
KUBE_DNS_PORT_53_UDP=udp://10.0.0.10:53
REGISTRY_PORT_80_TCP_PROTO=tcp
TILLER_DEPLOY_PORT_44134_TCP_PORT=44134
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1
KUBERNETES_DASHBOARD_PORT_80_TCP=tcp://10.0.0.29:80
DEFAULT_HTTP_BACKEND_PORT_80_TCP_PORT=80
REGISTRY_PORT=tcp://10.0.0.206:80
KUBERNETES_PORT_443_TCP_PORT=443
KUBE_DNS_SERVICE_PORT_DNS_TCP=53
KUBE_DNS_PORT_53_TCP_PROTO=tcp
KUBE_DNS_PORT_53_TCP_PORT=53
REGISTRY_PORT_80_TCP_PORT=80
TILLER_DEPLOY_SERVICE_PORT=44134
TILLER_DEPLOY_PORT_44134_TCP_PROTO=tcp
KUBERNETES_DASHBOARD_PORT=tcp://10.0.0.29:80
DEFAULT_HTTP_BACKEND_SERVICE_PORT=80
DEFAULT_HTTP_BACKEND_PORT_80_TCP_ADDR=10.0.0.245
KUBE_DNS_SERVICE_PORT=53
KUBERNETES_DASHBOARD_PORT_80_TCP_PROTO=tcp
KUBE_DNS_SERVICE_HOST=10.0.0.10
TILLER_DEPLOY_SERVICE_PORT_TILLER=44134
HOME=/tmp
```

**Comment by bacongobbler** [comment] 2017-11-01 20:24
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Closed by bacongobbler** 2017-11-01 20:24 UTC
Labels: question/support

**Comment by xixuejia** [comment] 2017-11-21 01:32
Hello, we encountered the same problem here. I would really appreciate your help and suggestions.

I deployed Tiller manually in k8s cluster and could use helm to get version of both the client and server
```bash
jiaxixues-mbp:.kube xixuejia$ helm version --host nodeIP:nodePort
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```
But when I issue command `helm ls --host nodeIP:nodePort`, I got the same error below
```bash
jiaxixues-mbp:.kube xixuejia$ helm ls --host nodeIP:nodePort
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```
```bash
root@k8scluster-6-k8s-node-node1:~# docker logs 046
[main] 2017/11/21 00:43:03 Starting Tiller v2.7.2 (tls=false)
[main] 2017/11/21 00:43:03 GRPC listening on :44134
[main] 2017/11/21 00:43:03 Probes listening on :44135
[main] 2017/11/21 00:43:03 Storage driver is ConfigMap
[main] 2017/11/21 00:43:03 Max history per release is 0
[storage] 2017/11/21 00:43:59 listing all releases with filter
[storage/driver] 2017/11/21 00:43:59 list: failed to list: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 127.0.0.1:8080: getsockopt: connection refused
[storage] 2017/11/21 00:44:20 listing all releases with filter
[storage/driver] 2017/11/21 00:44:20 list: failed to list: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```
Here are the tiller docker container env. variables from `docker inspect`
```
"Env": [
                "TILLER_NAMESPACE=kube-system",
                "TILLER_HISTORY_MAX=0",
                "TILLER_DEPLOY_PORT_44134_TCP_PROTO=tcp",
                "TILLER_DEPLOY_PORT_44134_TCP_PORT=44134",
                "KUBERNETES_SERVICE_PORT=443",
                "KUBE_DNS_SERVICE_HOST=10.6.2.250",
                "KUBE_DNS_PORT_53_UDP_ADDR=10.6.2.250",
                "KUBERNETES_DASHBOARD_PORT_80_TCP=tcp://10.6.244.33:80",
                "TILLER_DEPLOY_SERVICE_HOST=10.6.206.174",
                "TILLER_DEPLOY_PORT_44134_TCP_ADDR=10.6.206.174",
                "KUBE_DNS_PORT_53_TCP_PROTO=tcp",
                "KUBERNETES_DASHBOARD_PORT_80_TCP_PROTO=tcp",
                "TILLER_DEPLOY_SERVICE_PORT_TILLER=44134",
                "KUBE_DNS_SERVICE_PORT_DNS=53",
                "KUBE_DNS_PORT_53_UDP=udp://10.6.2.250:53",
                "KUBERNETES_DASHBOARD_PORT=tcp://10.6.244.33:80",
                "TILLER_DEPLOY_SERVICE_PORT=44134",
                "KUBE_DNS_SERVICE_PORT_DNS_TCP=53",
                "KUBE_DNS_PORT_53_TCP=tcp://10.6.2.250:53",
                "KUBE_DNS_PORT_53_TCP_PORT=53",
                "KUBERNETES_PORT_443_TCP_PORT=443",
                "KUBERNETES_PORT_443_TCP_PROTO=tcp",
                "KUBERNETES_PORT_443_TCP_ADDR=10.6.0.1",
                "KUBE_DNS_PORT_53_UDP_PROTO=udp",
                "KUBE_DNS_PORT_53_TCP_ADDR=10.6.2.250",
                "KUBERNETES_DASHBOARD_SERVICE_PORT=80",
                "KUBERNETES_PORT_443_TCP=tcp://10.6.0.1:443",
                "KUBE_DNS_PORT=udp://10.6.2.250:53",
                "KUBERNETES_PORT=tcp://10.6.0.1:443",
                "TILLER_DEPLOY_PORT_44134_TCP=tcp://10.6.206.174:44134",
                "KUBERNETES_SERVICE_HOST=10.6.0.1",
                "KUBE_DNS_SERVICE_PORT=53",
                "KUBE_DNS_PORT_53_UDP_PORT=53",
                "KUBERNETES_DASHBOARD_PORT_80_TCP_PORT=80",
                "TILLER_DEPLOY_PORT=tcp://10.6.206.174:44134",
                "KUBERNETES_DASHBOARD_SERVICE_HOST=10.6.244.33",
                "KUBERNETES_DASHBOARD_PORT_80_TCP_ADDR=10.6.244.33",
                "KUBERNETES_SERVICE_PORT_HTTPS=443",
                "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOLANG_VERSION=1.9.2",
                "GOPATH=/go",
                "TILLER_VERSION=release-2.7"
]
```

**Comment by chandrureddy** [comment] 2017-11-21 08:08
Does helm support passing kuberntes config file in order make connection to the master ?

**Comment by xuelongjiang** [comment] 2017-11-24 06:42
I get the same problem:
[root@master ~]# helm version 
Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}


[root@master ~]# helm list
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp [::1]:8080: getsockopt: connection refused

[root@master ~]# kubectl exec tiller-deploy-833363792-tpftf  -it sh  --namespace kube-system

/ # env
KUBERNETES_PORT=tcp://10.254.0.1:443
KUBERNETES_SERVICE_PORT=443
KUBE_DNS_SERVICE_PORT_DNS_TCP=53
TILLER_DEPLOY_SERVICE_HOST=10.254.89.49
HOSTNAME=tiller-deploy-833363792-tpftf
SHLVL=1
HOME=/tmp
KUBE_DNS_SERVICE_HOST=10.254.0.100
TILLER_DEPLOY_SERVICE_PORT=44134
TILLER_DEPLOY_PORT=tcp://10.254.89.49:44134
TILLER_DEPLOY_PORT_44134_TCP_ADDR=10.254.89.49
TILLER_DEPLOY_PORT_44134_TCP_PORT=44134
KUBE_DNS_PORT=udp://10.254.0.100:53
KUBE_DNS_SERVICE_PORT=53
TILLER_DEPLOY_PORT_44134_TCP_PROTO=tcp
TILLER_NAMESPACE=kube-system
KUBERNETES_PORT_443_TCP_ADDR=10.254.0.1
TILLER_DEPLOY_SERVICE_PORT_TILLER=44134
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBE_DNS_PORT_53_TCP_ADDR=10.254.0.100
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBE_DNS_PORT_53_UDP_ADDR=10.254.0.100
KUBE_DNS_PORT_53_TCP_PORT=53
TILLER_DEPLOY_PORT_44134_TCP=tcp://10.254.89.49:44134
KUBE_DNS_PORT_53_TCP_PROTO=tcp
KUBE_DNS_PORT_53_UDP_PORT=53
KUBE_DNS_SERVICE_PORT_DNS=53
KUBE_DNS_PORT_53_UDP_PROTO=udp
KUBERNETES_PORT_443_TCP=tcp://10.254.0.1:443
KUBERNETES_SERVICE_PORT_HTTPS=443
PWD=/
KUBERNETES_SERVICE_HOST=10.254.0.1
KUBE_DNS_PORT_53_TCP=tcp://10.254.0.100:53
KUBE_DNS_PORT_53_UDP=udp://10.254.0.100:53

**Comment by adarshaj** [comment] 2018-01-20 04:22
similar error, what is the workaround for this? I have this issue on a job run by concourse ci..

**Comment by jascott1** [comment] 2018-01-22 22:50
@xixuejia I cannot reproduce your situation but I think your linkage from Tiller to the k8s API must be broken as otherwise you would not have that `dial tcp` error. A failed request from Helm client can return a similar error but that would not show up in the Tiller log. Since its in the Tiller log I believe its an error from Tiller contacting the API. Are you running k8s in insecure mode (typically port 8080) ?

@chandrureddy You can specify the kube config file to use with the `--kubeconfig` flag.

All, please be aware that a remote Helm client does use your ~/.kube/config. If that file is missing you will see the `127.0.0.1:8080: getsockopt: connection refused`. A local helm client (on the k8s API server) talking to an insecure k8s can still function without ~.kube/config file as the k8s client rebuilds its cache from localhost:8080 on servers running insecurely.

**Comment by farfeduc** [comment] 2018-04-30 16:12
I had a similar issue, I had to set KUBERNETES_MASTER=https://yoururl:yourport
with yoururl:yourport obtained from `kubectl cluster-info`
and as it was https, I also had to use my kubeconfig mounted as a read only volume inside the tiller pod.

I do not know why but on version 2.9.0 of helm, tiller does not get the configuration from the default /root/.kube/config values.

**Comment by jmcclell** [comment] 2018-04-30 21:17
I have this exact same issue on a cluster created via Kops.

```
kops create cluster kube.example.com \
  --node-count 3 \
  --zones "us-east-1a,us-east-1b,us-east-1c" \
  --master-zones "us-east-1a,us-east-1b,us-east-1c" \
  --dns-zone example.com \
  --node-size m4.xlarge \
  --master-size m4.xlarge \
  --topology private \
  --networking kube-router \
  --bastion
```

When the clust comes up, my local `kubectl` context is correct and I can interact with the cluster. However, if I install Helm and run `helm init`, the Tiller pod's logs show errors similar to what the client displays.

Here is the output from `helm list`:

```
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp [::1]:8080: connect: connection refused
```

Here is the log from the Tiller pod:

```
[main] 2018/04/30 20:38:41 Starting Tiller v2.9.0 (tls=false)
[main] 2018/04/30 20:38:41 GRPC listening on :44134
[main] 2018/04/30 20:38:41 Probes listening on :44135
[main] 2018/04/30 20:38:41 Storage driver is ConfigMap
[main] 2018/04/30 20:38:41 Max history per release is 0
[tiller] 2018/04/30 20:43:25 preparing install for data
[storage] 2018/04/30 20:43:25 getting release history for "data"
[storage/driver] 2018/04/30 20:43:25 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Ddata%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:25 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:25 preparing install for polling
[storage] 2018/04/30 20:43:25 getting release history for "polling"
[storage/driver] 2018/04/30 20:43:25 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Dpolling%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:25 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:25 preparing install for hosts
[storage] 2018/04/30 20:43:25 getting release history for "hosts"
[storage/driver] 2018/04/30 20:43:25 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Dhosts%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:25 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:26 preparing install for alerts
[storage] 2018/04/30 20:43:26 getting release history for "alerts"
[storage/driver] 2018/04/30 20:43:26 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Dalerts%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:26 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:26 preparing install for dash
[storage] 2018/04/30 20:43:26 getting release history for "dash"
[storage/driver] 2018/04/30 20:43:26 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Ddash%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:26 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:52 preparing install for data
[storage] 2018/04/30 20:43:52 getting release history for "data"
[storage/driver] 2018/04/30 20:43:52 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Ddata%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:52 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:52 preparing install for polling
[storage] 2018/04/30 20:43:52 getting release history for "polling"
[storage/driver] 2018/04/30 20:43:52 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Dpolling%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:52 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:52 preparing install for hosts
[storage] 2018/04/30 20:43:52 getting release history for "hosts"
[storage/driver] 2018/04/30 20:43:52 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Dhosts%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:52 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:52 preparing install for alerts
[storage] 2018/04/30 20:43:52 getting release history for "alerts"
[storage/driver] 2018/04/30 20:43:52 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Dalerts%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:52 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:53 preparing install for dash
[storage] 2018/04/30 20:43:53 getting release history for "dash"
[storage/driver] 2018/04/30 20:43:53 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Ddash%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:43:53 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:44:55 preparing install for data
[storage] 2018/04/30 20:44:55 getting release history for "data"
[storage/driver] 2018/04/30 20:44:55 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Ddata%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:44:55 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:49:29 preparing install for data
[storage] 2018/04/30 20:49:29 getting release history for "data"
[storage/driver] 2018/04/30 20:49:29 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Ddata%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:49:29 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:49:29 preparing install for polling
[storage] 2018/04/30 20:49:29 getting release history for "polling"
[storage/driver] 2018/04/30 20:49:29 query: failed to query with labels: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%3Dpolling%2COWNER%3DTILLER: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:49:29 failed install prepare step: Get http://localhost:8080/version: dial tcp [::1]:8080: connect: connection refused
[tiller] 2018/04/30 20:49:30 preparing install for hosts
[storage] 2018/04/30 20:49:30 getting release history for "hosts"
```

**Comment by bacongobbler** [comment] 2018-04-30 23:28
We've already merged a fix into master; we just need to cut a v2.9.1. The core maintainers are all travelling to KubeCon EU at this time so we haven't had the time to cut a release. You can track progress through the GitHub milestone if you'd like. :)

**Comment by kalbasit** [comment] 2018-04-30 23:30
Awesome, thx @bacongobbler.

**Comment by jskulavik** [comment] 2018-05-02 23:51
Just FYI @bacongobbler, a very similar issue occurs against ACI.  I ran into it trying to install Brigade
![image](https://user-images.githubusercontent.com/2044176/39554640-4a3de916-4e31-11e8-983a-fde0c0bc0c50.png)

**Comment by jskulavik** [comment] 2018-05-03 00:42
No problem! You all enjoy the conference.
