### ISSUE TITLE
upgrade stable/traefik not found, while search shows it exists 

### ISSUE THREAD

**Issue by c-knowles** [kubernetes/helm#2413] opened 2017-05-08 10:25 UTC
After upgrading from Helm 2.3.0 to 2.4.1 we seem to have some problems ensuring stable charts are up to date. I've been trying to spot any other significant changes in our CI flow but haven't found anything apart from a Helm upgrade.

Trying to upgrade/install from stable:
```
helm upgrade traefik-master stable/traefik --install --wait \
--kube-context=dev --namespace=kube-system --values=/tmp/traefik-values.yml
```

The result is `file "stable/traefik" not found`.

Tiller seems to be running fine and I've also tried deleting `~/.helm` and recreating it via `init` but with the same result.

```
✗ helm version
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}

✗ helm repo list
NAME  	URL                                             
stable	https://kubernetes-charts.storage.googleapis.com
local 	http://127.0.0.1:8879/charts

✗ helm search traefik
NAME          	VERSION	DESCRIPTION                                       
stable/traefik	1.2.1-a	A Traefik based Kubernetes ingress controller w...

✗ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
```

Had the same problem after `repo update` as well.

Helm has been initialised via `helm init --client-only` in the case of this install. I'm using Kubernetes 1.6.2 on AWS.

**Comment by c-knowles** [comment] 2017-05-08 10:32
I should also point out that in this case helm has been initialised via `helm init --client-only`.

**Comment by c-knowles** [comment] 2017-05-09 05:41
I believe also reported as https://github.com/kubernetes/charts/issues/999 and resolved by https://github.com/kubernetes/helm/pull/2408

**Comment by c-knowles** [comment] 2017-05-09 05:51
Would it be possible to clarify this in the 2.4.x changelog as a breaking change?

**Comment by c-knowles** [comment] 2017-05-09 06:26
I'm trying the workaround but it seems there's another issue, at this stage I'm not sure if it's chart specific or not. An upgrade with `--wait` times out but I can access Traefik in this case, it's running ok.

```
✗ helm upgrade traefik-master stable/traefik --install --wait \
--kube-context=dev --namespace=kube-system --values=/tmp/traefik-values.yml \
--version=">=1.2.1-b" --debug
[debug] Created tunnel using local port: '39847'

[debug] SERVER: "localhost:39847"

[debug] Fetched stable/traefik to traefik-1.2.1-b.tgz

Error: UPGRADE FAILED: timed out waiting for the condition
```

**Comment by thomastaylor312** [comment] 2017-05-09 23:55
@c-knowles Is there a pod that is not all the way up and running or a service that doesn't have an IP address? That is generally why a release fails because that resource is not technically "ready"

**Comment by c-knowles** [comment] 2017-05-10 01:55
@thomastaylor312 not that I've found. After each of the updates I tried I did have a look at the pods to see why it was waiting for so long since with the older version of Helm these update are generally taking 10-20 seconds. I only found health pods/services. Even a no-op update to the exact same chart version and config waits until timeout with Helm 2.4.1 (but successfully runs through with 2.3.1).

I've been looking through the [wait code](https://github.com/kubernetes/helm/blob/4566b1733c8fd012a4cf5c48ca87021806e3310a/pkg/kube/wait.go#L63) trying to determine what the cause could be. Traefik chart check list:
1. Deployment - all replicas running and `deployment.status` shows they are ready and non unavailable
1. Service - `LoadBalancer` type and has a hostname set in `status.loadBalancer.ingress`
1. Service, dashboard - `ClusterIP` type and has `spec.clusterIP` (had to be true anyway otherwise the service would not have been responding successfully when Helm was still waiting and I tried it a few times)
1. Ingress, dashboard - no waits that I'm aware of
1. ConfigMap/Secrets - no waits involved
1. PVC - not enabled in my config

I've since downgraded Tiller and Helm to 2.3.1 and all is working again with all other setup being identical.

**Comment by thomastaylor312** [comment] 2017-05-11 03:22
@c-knowles This may possibly be related to #2426. I am looking into that issue now and seeing if I can patch it

**Comment by c-knowles** [comment] 2017-05-11 05:20
@thomastaylor312 yeah it looks like the same issue. I can retest when there is a patch.

**Comment by thomastaylor312** [comment] 2017-05-11 05:25
@c-knowles I just pushed up #2430. Please let me know if it works or if you have any other feedback

**Comment by thomastaylor312** [comment] 2017-05-11 05:26
Marking as a duplicate, but leaving open until the issue is solved.

**Comment by thomastaylor312** [comment] 2017-05-11 21:34
This was fixed in #2430 which will be shipped as 2.4.2 in the next few days

**Closed by thomastaylor312** 2017-05-11 21:34 UTC
Labels: bug, duplicate

**Comment by c-knowles** [comment] 2017-05-17 14:03
I had a go at rebuilding helm from master but got caught on a few things (just some problems my end). I'll have another go in a few days if there isn't a release soon.

**Comment by thomastaylor312** [comment] 2017-05-18 23:39
@c-knowles This was released yesterday in 2.4.2

**Comment by c-knowles** [comment] 2017-06-01 01:57
@thomastaylor312 thanks! I've just run through this again with the latest Traefik chart and all seems good with 2.4.2 so it seems unaffected by the issues in https://github.com/kubernetes/helm/issues/2426.

**Comment by thomastaylor312** [comment] 2017-06-01 05:40
@c-knowles Thanks for circling back and letting me know!
