### ISSUE TITLE
Windows: Helm Install with Remote URL doesn't Work

### ISSUE THREAD

**Issue by robbiezhang** [kubernetes/helm#3219] opened 2017-12-01 18:26 UTC
`helm version`

> Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
> Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

`helm install https://github.com/Azure/aci-connector-k8s/raw/master/charts/aci-connector.tgz --name aci-conn-robbie --debug`

> [debug] Created tunnel using local port: '2117'
> 
> [debug] SERVER: "127.0.0.1:2117"
> 
> [debug] Original chart version: ""
> Error: no cached repo found. (try 'helm repo update'). open C:\Users\\[user]\\.helm\repository\cache\local-index.yaml: The system cannot find the file specified.

The chart exists. I download it locally, and run "helm install" against the local file it works.

**Comment by bacongobbler** [comment] 2017-12-01 18:37
Hey @robbiezhang, can you first try to run `helm init --client-only` first before running `helm install`?

**Comment by robbiezhang** [comment] 2017-12-01 21:55
yes, I tried to delete ~/.helm, and `helm init --client-only` and `helm repo update`, but I still get the error. 
I finally find a workaround. I notice that `C:\Users\[user]\.helm\repository\cache\local-index.yaml` doesn't exist. After I copy an empty index there, it works for me.
It looks like a bug in the `helm init` or `helm repo update`, since they should create the file for me.

**Comment by bacongobbler** [comment] 2017-12-01 22:10
Yeha this could be related to some other windows-related bugs we saw a few releases back. I'll tack this onto #2456.

**Comment by bacongobbler** [comment] 2017-12-01 22:12
interesting... This same error popped up in https://github.com/kubernetes/helm/issues/2071 as well. I'll see if I can re-validate that bug. If so then we'll re-open that one and close this out as a duplicate.

**Comment by bacongobbler** [comment] 2017-12-01 22:14
closing as a duplicate of #2071. I've gone ahead and re-opened that issue. Thank you for the report, @robbiezhang!

**Closed by bacongobbler** 2017-12-01 22:14 UTC
