### ISSUE TITLE
Helm seems to translate all-numeric image tags into scientific notation

### ISSUE THREAD

**Issue by arschles** [kubernetes/helm#3246] opened 2017-12-10 22:48 UTC
I don't yet have concrete repro steps, but it seems that if you pass the `helm` CLI an 8 digit number in a `--set` (such as something that `git rev-parse --short HEAD` might output), it converts it into scientific notation.

This can be problematic if you tag your docker images with shortened git SHAs, because the Docker image tag won't be the same as the one you pass Kubernetes. Additionally, Kubernetes correctly reports the image name invalid

**Comment by bacongobbler** [comment] 2017-12-11 07:21
closing as a duplicate of #1707 and #3001. This is an annoying bug for sure.

**Closed by bacongobbler** 2017-12-11 07:21 UTC

**Comment by arschles** [comment] 2017-12-11 08:26
Thanks @bacongobbler. FWIW, I simply suffixed the tag with `-gitsha`, which seems to ensure that the value is treated as a string. I'll post my +1 in #1707 as well
