### ISSUE TITLE
Helm Homebrew Binary - Context Deadline Exceeded Error

### ISSUE THREAD

**Issue by onlydole** [kubernetes/helm#3083] opened 2017-11-01 02:58 UTC
When using the Helm `v2.7.0` binary from the Homebrew package manager, the following error message is seen below. Yet, installing the binary via the "From Script" method allows for regular use without any issue.

```
helm ls --debug
[debug] Created tunnel using local port: 'XXX'

[debug] SERVER: "localhost:XXX"

Error: context deadline exceeded
```

**Comment by bacongobbler** [comment] 2017-11-01 17:21
seems related to #2409. What cloud provider are you using for your kubernetes cluster?

**Comment by onlydole** [comment] 2017-11-01 18:37
Hey @bacongobbler (Ha! Great name) - I’m using AWS for this cluster. It does work when not using the Brew binary too.

**Comment by bacongobbler** [comment] 2017-11-01 18:40
Okay, if it doesn't seem related to the CLI then I think we can rule this as a duplicate of #2409. Would you mind following that ticket instead? Thanks!

**Closed by bacongobbler** 2017-11-01 18:40 UTC
Labels: question/support

**Comment by onlydole** [comment] 2017-11-01 18:42
@bacongobbler - This is related to the binary and should be checked / updated I believe as I can reproduce. This is not a duplicate of #2409 (as it's a different cloud, though it is the same Golang error response).

**Comment by bacongobbler** [comment] 2017-11-01 18:51
We've started to pile in separate cloud providers into the same issue (minikube and AWS users alike have piled onto that issue). We're trying to keep all issues related to that error in the same issue so we can track bug reports all in the same issue rather than in many different issues. It's hard to track many different conversations around the same bug reports in separate tickets so we try to keep them together. Does that help clear things up? :)

If you can provide more debug information (like a wireshark network dump when using helm) that would be very helpful. Thanks!

**Comment by bacongobbler** [comment] 2017-11-01 18:51
I'll update that ticket to make it clearer.

**Comment by onlydole** [comment] 2017-11-01 18:56
@bacongobbler Ahhh! Got it 👍 Thank you
