### ISSUE TITLE
feature: helm to handle repo without using tar model

### ISSUE THREAD

**Issue by v1k0d3n** [kubernetes/helm#1840] opened 2017-01-19 22:02 UTC
it would be extremely helpful for large repository sources to follow a format of:

```
charts/
  |
  |- index.yaml
  |
  |- app01
    |- values.yaml
    |- requirements.yaml
    |- Chart.yaml
    |- templates
  |
  |- app02
    |- values.yaml
    |- requirements.yaml
    |- Chart.yaml
    |- templates
```

meaning, can Helm _clients_ be enabled to handle the creation and linting process, rather than the debt falling on the repo maintainers? this would be really helpful for large repo maintainers, or repos that have complex interdependencies in Charts (for instance, an Openstack application or collection of Charts).

**Comment by technosophos** [comment] 2017-01-24 00:20
How would the repo contain more than one version of the same chart?

Right now, it's:

```
charts/
  |
  |- index.yaml
  |- app01-1.2.3.tgz
  |- app01-1.2.4.tgz
  |- ...
```

I guess we could unpack those into directories...

```
charts/
  |
  |- index.yaml
  |- app01-1.2.3/
  |- app01-1.2.4/
  |- ...
```

But that might require a compatibility-breaking change, since the chart spec says that the directory has to be the _name_ of the chart, with no version info.

There's also the possibility of simply configuring the webserver to do all of this for you. While the Helm client tries to fetch tarballs, there's no reason you couldn't set up a web server that would respond to `GET /app01-1.2.3.tgz` by just tgz'ing the right directory.

**Comment by alanmeadows** [comment] 2017-01-24 21:05
@technosophos The real wish here is to be able to point at artbitrary Github (or whatever) URLs for charts and simply specify tags, branches, whatever makes sense.  I see a lot of similarities to what Berkshelf implemented (https://sethvargo.com/berksfile-magic/) which makes one wonder whether this belongs in helm or a companion tool, but given helm specifies urls for dependencies, I am inclined to point the finger at helm itself.

We have all also enjoyed the same functionality for go dependencies. 

In such a case, there is no possibility of the web server implementing something unique to satisfy this request, so it has to be client side. This really eases the burden for stringing together multiple repositories that can live in separate git repositories without needing to be "built" (which is simply a matter of tgz).  It also nearly removes the need to establish helm "repos" as you simply need to house your charts somewhere like github. Versions are merely just a tag, branch or commit reference. It seems the barrier at least to me to supporting native git urls is relatively low since the package processing is so thin.

**Comment by technosophos** [comment] 2017-01-26 20:35
Helm Classic actually used the model you lay out above. We moved from that to the present model because we wanted (a) guaranteed reproducibility, and (b) strong cryptographic integrity checking. But I can't deny that the old model had some real niceties.

If it has to be done client-side, this is _exactly_ the thing we had envisioned for plugins. CNR, for example, is implementing their repo tool this way. I'm not totally clear what the role of an index.yaml would be in this model. Probably, that could be skipped. And the rest could probably even be done as a shell script, provided you knew where you were cloning the master repo. It's sort of the opposite of the GitHub plugin that I started here: https://github.com/technosophos/helm-plugins/tree/master/github

**Comment by alanmeadows** [comment] 2017-01-26 23:12
@technosophos That is interesting, I never really ramped up on classic. Isn't reproducibility solved by not only a git pointer but one with specific tags or commit references? I have tools that have operated over a period of years with this approach.

The other challenge, integrity checking is a little harder to solve for -- some integrity is guaranteed with https but obviously, its not as in-depth as signing .tgz packages.

I figured the plugins would enter this discussion ;-) 

I accept that we should look there first and see whats lacking to accomplish this approach for git based repositories, but it does mean that everyone who agrees with this philosophy will need to grab a community "git repo" plugin that supports this before creating and using repo git targets within helm.

**Comment by technosophos** [comment] 2017-02-15 00:17
@redbaron also brought up this issue today. He also had some ideas about how it might be implemented.

And, yes, we'd have to supply a compelling alternative to signing packages, as well as thoroughly solving the issue of supporting multiple versions of the same chart in a way that's easily searchable, etc.

It's definitely worth looking at how Homebrew tried to solve this (and mostly faltered, IMO), compared to how Debian, Ubuntu, and RedHat solved it.

Between now and the (unscheduled) 3.0 release, pretty much the only viable way forward is via a plugin. But I still feel really strongly that this is the right way to proceed. We've already talked about pulling the `helm repo` commands out into a plugin. And in Helm 2.3.0 we will have a plugin manager that will make working with plugins much, much easier.

**Comment by jascott1** [comment] 2017-08-17 00:33
@v1k0d3n @alanmeadows Since this is not happening for 2.x I am going to close this issue and let us evaluate during 3.x design. Please feel free to re-open if necessary.

**Closed by jascott1** 2017-08-17 00:33 UTC
Labels: plugin
