### ISSUE TITLE
Tiller crashes when deployment with name containing '/' created

### ISSUE THREAD

**Issue by munnerz** [kubernetes/helm#1886] opened 2017-01-30 10:19 UTC
Hi there

Whilst developing some tooling around helm, I've noticed that when creating a resource with a name containing a '/' in it, the local helm client exits with `Error: transport is closed`, and the Tiller pod crashes (although recovers once k8s restarts it).

I wouldn't expect Tiller to support `/` characters in names, but I would expect a more helpful error message at some point during the creation. Specifically I'd also _not_ expect a crash from Tiller.

I can help pick apart the codepath to spot where this needs adding in, but want to make a note of it before I do.

**Comment by technosophos** [comment] 2017-01-30 20:18
Can you provide the crash log's stack trace? You are right that this should not cause a crash.

**Comment by technosophos** [comment] 2017-01-30 23:37
Having trouble reproducing. Here's my template:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foo/{{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
```

So this will generate names like `name: foo/quaffing-panda`.

Now if I run it, I get:

```console
$  helm install .
Error: release bold-possum failed: Deployment.extensions "foo/bold-possum" is invalid: metadata.name: Invalid value: "foo/bold-possum": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')
```

And if I look at the Tiller logs, I see:

```
2017/01/30 23:35:31 storage.go:37: Getting release "bold-possum" (v1) from storage
2017/01/30 23:35:31 release_server.go:872: Executing pre-install hooks for bold-possum
2017/01/30 23:35:31 release_server.go:899: Hooks complete for pre-install bold-possum
2017/01/30 23:35:31 storage.go:133: Getting release history for ''
2017/01/30 23:35:31 release_server.go:835: warning: Release "bold-possum" failed: Deployment.extensions "foo/bold-possum" is invalid: metadata.name: Invalid value: "foo/bold-possum": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')
2017/01/30 23:35:31 storage.go:45: Create release "bold-possum" (v1) in storage
2017/01/30 23:35:31 release_server.go:633: Failed install perform step: release bold-possum failed: Deployment.extensions "foo/bold-possum" is invalid: metadata.name: Invalid value: "foo/bold-possum": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')
```

This is on Helm 2.1 and Kubernetes 1.5.2.

Can you provide me a little more data to try to debug?

**Comment by technosophos** [comment] 2017-02-02 17:24
@munnerz anything you can add to this? I'm stalled out because I can't reproduce. If you can help me, I will push to get this into the next release.

**Comment by technosophos** [comment] 2017-02-08 01:25
If anyone can reproduce this, please let me know (and please provide an example). I can't reproduce, and I'll have to pull this off of the 2.2.0 milestone in a few days.

**Comment by technosophos** [comment] 2017-02-13 18:34
Alright, with no new information and a pending release tomorrow, I'm moving this off of the 2.2.0 milestone. Sorry.

**Comment by jascott1** [comment] 2017-07-21 05:30
@thomastaylor312 Close this as obsolete?

**Comment by thomastaylor312** [comment] 2017-07-21 18:47
Yep. Closing this as it has seen no activity in over 30 days. If this is still an issue, feel free to let us know here

**Closed** 2017-08-11 22:01 UTC
