### ISSUE TITLE
Subcharts values parsing has a few problems

### ISSUE THREAD

**Issue by rustyShacklefurd** [kubernetes/helm#2487] opened 2017-05-23 23:03 UTC
1. It appears that any value that is beyond one level deep cannot be parsed in the subcharts when testing/deploying the entire parent/child chart.  Example: when a value is being called such as `{{ .Values.images.worker.repository }}` this lookup will fail.  Changing the value name and values call overcomes this limitation but it seems that nested values are not supported in subcharts.
2. This may be part of the nested issue but the `{{ .Values.global }}` lookups fail in the same fashion.  All errors state "can't evaluate field x in type interface {}"; if the failed is `{{ .Values.global.x.y }}`

In an attempt to overcome the issues I changed the entire subchart values file to be only one level deep but it seems that then the values that were being returned were nil as stated from the error. Another attempt was made to ensure that there were no overlapping values in either of the values file and went so far as to setup the subchart values in the parent chart values file as is outlined in the docs; neither of these efforts yielded any results (returned the exact same error as stated in #2 above).

**Comment by thomastaylor312** [comment] 2017-05-23 23:08
@jascott1 Have you seen this before or have any ideas?

**Comment by rustyShacklefurd** [comment] 2017-05-24 01:31
[storm-0.9.zip](https://github.com/kubernetes/helm/files/1024180/storm-0.9.zip)

Zipped the whole chart/subchart together so that recreating the issues be accomplished.

**Comment by jascott1** [comment] 2017-05-26 00:51
@rustyShacklefurd 
Your folder is `storm-0.9.x/charts/worker-ui` but the Chart.yml there contains incorrect `name: storm-0.9.x`. After changing it to `name: worker-ui` the values were rendered.

@thomastaylor312 any idea why this wasn't failing on the chart folder / chart name mismatch? I could've sworn it threw an error at me before when I had this mismatch.

**Comment by jascott1** [comment] 2017-05-26 01:23
Also opened #2502 while working this issue which removes outdated info about nested globals.

**Comment by thomastaylor312** [comment] 2017-05-26 04:14
@jascott1 Thanks for the answer! I don't remember if there is actually a check done on the folder matching the chart name. @technosophos is that supposed to be the intended behavior?

@rustyShacklefurd Did @jascott1's answer solve it for you?

**Comment by technosophos** [comment] 2017-06-08 14:54
@thomastaylor312 Yeah, we deliberately made it more lenient about that stuff. The chart requirement remains the same, but the parser does not fail if the user makes a mistake when naming things.

So I am thinking we can close this one, right?

**Comment by thomastaylor312** [comment] 2017-06-08 16:43
I think we can close this. @rustyShacklefurd if you still have problems with this, feel free to reopen

**Closed by thomastaylor312** 2017-06-08 16:43 UTC
Labels: bug
