### ISSUE TITLE
helm install does not recognize semantic version

### ISSUE THREAD

**Issue by bassam** [kubernetes/helm#2797] opened 2017-08-11 19:19 UTC
I'm running helm v2.5.1 and performed the following:

```
helm repo add rook-master https://charts.rook.io/master
helm repo update
```

running helm search shows the release expected:
```
> helm search rook
NAME            	VERSION          	DESCRIPTION                
rook-master/rook	v0.5.0-8-g9118b5b	A Helm chart for Kubernetes
```

but helm install fails:

```
> helm install rook-master/rook
Error: file "rook-master/rook" not found
```

If I change the version number to v0.5.0 and drop the last component helm install works. Seems like a bug in version parsing/comparison logic.

**Comment by bacongobbler** [comment] 2017-08-11 19:51
v0.5.0-8-g9118b5b is not a valid semver tag. As per [semver law](http://semver.org/#spec-item-9) on pre-releases:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

So in your case it should be `v0.5.0-8.g9118b5b`. Can you try that and see if it works?

**Comment by bassam** [comment] 2017-08-11 19:54
@bacongobbler aah. Its the version generated from `git describe --dirty --always --tags` which looks like is not a valid semver. I'll modify it and report back.

**Comment by bassam** [comment] 2017-08-15 00:04
@bacongobbler still seeing the problem:

```
> helm search rook
NAME            	VERSION           	DESCRIPTION                                       
rook-master/rook	v0.5.0-24.gccf1df3	File, Block, and Object Storage Services for yo...
> helm install rook-master/rook
Error: file "rook-master/rook" not found
```

**Comment by ringods** [comment] 2017-08-23 08:17
@bassam why is your main version starting with a `v`? Semver 2 specifies it without:
http://semver.org/#spec-item-2

The `SemVerTag` part from Semver 1 was only for source control revisioning and considered out of scope of SemVer 2:
https://github.com/mojombo/semver.org/issues/50

**Comment by jipperinbham** [comment] 2017-10-06 18:12
I'm seeing the same issue and do not have the version prefixed with `v`.

```shell
bash-4.3# helm search dns-manager
NAME                   	VERSION     	DESCRIPTION
dns-manager/dns-manager	2017.10.06-1	dns-manager manages capsule and enterprise host...

bash-4.3# helm repo list
NAME       	URL
stable     	https://kubernetes-charts.storage.googleapis.com
local      	http://127.0.0.1:8879/charts
dns-manager	http://helm-chart-public/dev-lab/dns-manager

bash-4.3# helm install dns-manager/dns-manager -n dns-manager --namespace dev-lab -f ./deploy/values.yaml
Error: file "dns-manager/dns-manager" not found

bash-4.3# helm install dns-manager/dns-manager -n dns-manager --namespace dev-lab --version 2017.10.06-1 -f ./deploy/values.yaml
NAME:   dns-manager
LAST DEPLOYED: Fri Oct  6 18:08:16 2017
NAMESPACE: dev-lab
STATUS: DEPLOYED
```

```
bash-4.3# helm version
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
```

**Comment by jipperinbham** [comment] 2017-10-07 18:50
@bassam I think the issue we're hitting is the result of the charts having a `-suffix`. Similar issues are described in https://github.com/kubernetes/helm/issues/3009 where it's explained you have to use the `--devel` flag when trying to install a chart with the `-suffix` and not providing the `--version``.

**Comment by bacongobbler** [comment] 2017-11-01 20:02
yes, that is indeed the issue. development charts are not exposed by default unless you explicitly add the --devel flag to `helm install`. Good catch, @jipperinbham.

I'm going to close this as working as intended, but please re-open if there's some action item that I'm missing which we need to address. Thanks!

**Closed by bacongobbler** 2017-11-01 20:02 UTC
Labels: question/support
