### ISSUE TITLE
helm-fetch emits non-sensical error: Non-absolute URLs should be in form of repo_name/path_to_chart, got: true

### ISSUE THREAD

**Issue by dmccaffery** [kubernetes/helm#2670] opened 2017-07-11 08:05 UTC
This error is emitted whenever flags are passed to `helm fetch` in addition to the chart. The chart is still fetched regardless, but the warning is annoying.

WORKS:

```sh
helm fetch stable/nginx-ingress
```

WORKS (BUT EMITS AN ERROR):

```sh
helm fetch stable/nginx-ingress --untar true
```

VERSION INFO:

```js
{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

PLATFORM INFO:

```sh
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
```

**Comment by seh** [comment] 2017-07-11 14:49
I was going to say that is a limitation of [the _spf13/cobra_ library](spf13/cobra). Well, really, it would be [the underlying _spf13/pflag_ library](https://github.com/spf13/pflag). However, reading [the advertised syntax](https://github.com/spf13/pflag#command-line-flag-syntax) there, it claims the following:
> Flag parsing stops after the terminator "--". Unlike the flag package, flags can be interspersed with arguments anywhere on the command line before this terminator.

[The _helm fetch_ command](https://sourcegraph.com/github.com/appscode/helm/-/blob/cmd/helm/fetch.go#L68-80) is using _cobra_ as intended. I find that my own programs that use _cobra_ similarly behave as intended, not interpreting the flag/value pair ("--untar" and "true" in your case) as an argument.

**Comment by technosophos** [comment] 2017-07-11 21:41
The documentation in Go flag and pflag is very clear on this point. From the Go docs:

```
Command line flag syntax:
  -flag
  -flag=x
  -flag x  // non-boolean flags only
```

To pass `--untar` a bool value, it must be `--untar=true`.

In the case given in the original issue, here's how that command is parsed by Helm:

```
$ helm fetch ARG1 --untar ARG2
```

Fetch accepts multiple URLs, so it tries to fetch `ARG1` (stable/nginx) and succeeds. Then it tries to fetch`ARG2` (true). There is no chart named `true` in the current directory, so it kicks it to the URL parser, which fails to parse `true` as a valid Helm URL. Thus the error.

**Comment by seh** [comment] 2017-07-11 21:45
Ah, I missed the detail about the special treatment of boolean flags.

**Comment by bacongobbler** [comment] 2017-11-01 01:17
closing as this is working as intended.

**Closed by bacongobbler** 2017-11-01 01:17 UTC
Labels: wont fix
