### ISSUE TITLE
helm lint should support `-f` and `--set` (or an alternative)

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#2495] opened 2017-05-25 10:22 UTC
We keep secrets in a separate values file used with `-f secrets.yaml`. This breaks `helm lint` for us  because we get parse errors in the templates on missing `$.Values` entries. Supporting `--set` and `-f` in `helm lint` would fix this issue.

**Comment by technosophos** [comment] 2017-06-08 15:00
The prevailing line on this has been that you should use `default` in the template to specify an empty default. But I think we probably need to solve this as you suggest because we also need to support `required` in templates.

**Comment by andytom** [comment] 2017-06-12 11:55
I think this is related to, or maybe a duplicate of, #2347?

**Comment by eicnix** [comment] 2017-06-15 08:36
This is a usecase for me aswell. My current workaround consists of rendering the template with the values in question through https://github.com/technosophos/helm-template and validating the output.

**Comment by hypnoglow** [comment] 2017-08-03 14:28
So, let's make a decision about this. 

I think [@maratoid statement](https://github.com/kubernetes/helm/issues/2347#issuecomment-301184305) is eligible and seems right. But, for many use cases, it may be convenient to lint with custom values provided using `--set` or `-f`. This way you can ensure that not only the chart itself is valid, but the configured chart is valid.

I have already forked and patched lint to support `--set` and `-f` to see how it would behave. But do we want it in the upstream?

**Comment by FUSAKLA** [comment] 2017-08-04 10:57
In case of using required it is necessary to have this feature.
Otherwise there is no way of testing it.

**Comment by technosophos** [comment] 2017-08-10 16:11
@hypnoglow TL;DR: Yes, I think we want it in upstream.

For me, the argument you made is right: Any chart should be valid _without_ -f/--set. BUT it is also very useful to be able to validate/debug cases where custom values are set. Since -f/--set are optional, if we add them we are allowing users to choose which of those cases is most important to them.

So I think the right thing to do is add --set/-f to linter.

If you feel like opening a PR for that, we might still be able to get it into 2.6 as planned.

**Comment by thomastaylor312** [comment] 2017-10-06 01:23
It looks like there is some work on this in a fork, but there is no PR yet so I am going to bump it to 2.8

**Comment by bacongobbler** [comment] 2017-10-31 23:42
closing this as a duplicate of #2036.

**Closed by bacongobbler** 2017-10-31 23:42 UTC
Labels: feature
