### ISSUE TITLE
Please provide -ARCH tiller images

### ISSUE THREAD

**Issue by luxas** [kubernetes/helm#1948] opened 2017-02-12 09:07 UTC
Now that this is an official Kubernetes project (whohoo :tada:!!), it should comply with the multi-platform guidelines Kubernetes: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multi-platform.md

I see there has been great progress on this lately, and I think there's only one piece missing.

Please push tiller images for the Kubernetes server platforms: https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L77

They should be suffixed with `-ARCH`, i.e. `gcr.io/kubernetes-helm/tiller-amd64:v2.2.0`, `gcr.io/kubernetes-helm/tiller-arm:v2.2.0`, etc.

 `gcr.io/kubernetes-helm/tiller:v2.2.0` should be the same image as `gcr.io/kubernetes-helm/tiller-amd64:v2.2.0` for backwards-compability.

Ideally, we'd then want a [manifest list](https://integratedcode.us/2016/04/22/a-step-towards-multi-platform-docker-images/) named `gcr.io/kubernetes-helm/tiller:v2.2.0` with full backwards-compability and everything.
This is unfortunately not possible, gcr.io doesn't support these "fat manifests" yet, so we have to do a slight workaround for the time being.
`helm init` should read the server platform from `/version` on the api server and use the right `-arch` image when deploying tiller. We can remove that extra logic when gcr.io supports manifest lists.

Thank you!
cc @technosophos @michelleN

**Comment by bacongobbler** [comment] 2017-08-11 22:06
closing as a duplicate of #1862 and #1968.

**Closed by bacongobbler** 2017-08-11 22:06 UTC
Labels: feature

**Comment by missnebun** [comment] 2018-02-23 00:50
So I guess no support for ARM ?

**Comment by bacongobbler** [comment] 2018-02-23 07:03
Not presently. See my above comment

**Comment by teq0** [comment] 2018-03-10 07:02
Both of which are lifecycle/frozen from inactivity, making this the only live issue around potentially keeping tiller images up to date with helm versions. What is the logic behind having ARM helm images up to 2.8.1 but no corresponding tiller images?

**Comment by bacongobbler** [comment] 2019-09-30 18:04
> What is the logic behind having ARM helm images up to 2.8.1 but no corresponding tiller images?

You can have the Helm client running on a device using a 64-bit ARM chip interfacing with a Kubernetes cluster backed by machines using a 64-bit AMD chipset.
