### ISSUE TITLE
Helm does not create initContainers annotations for kubernetes cluster in version 1.5.x

### ISSUE THREAD

**Issue by rpiotrow** [kubernetes/helm#4129] opened 2018-05-27 20:22 UTC
When installing stable/prometheus chart in latest version (6.7.0) in Kubernetes cluster version 1.5.1 or 1.5.3 helm does not create init containers that are defined in [server-deployment.yaml](https://github.com/kubernetes/charts/blob/master/stable/promtheus/templates/server-deployment.yaml).

According to Kubernetes documentation initContainers are working in version 1.5, but need to be defined as annotation (see https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) - helm does not create that annotations for Kubernetes cluster version 1.5.x.

For cluster version 1.6 and 1.7 helm creates annotations and initContainers yaml definition, which works fine.

For cluster version 1.8 and above helm creates only initContainers yaml definition, which works fine.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T0:00:00Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

**Comment by magicalbanana** [comment] 2018-06-03 03:18
Same issue with mine. Trying to add init containers as an annotation to a deployment spec and it's not getting applied.

**Comment by magicalbanana** [comment] 2018-06-03 03:30
👍 anyone care to help us out?

**Comment by bacongobbler** [comment] 2018-06-08 06:14
The latest release of Helm can only reasonably support the releases kubernetes officially supports. At this time that'd be 1.9 and 1.10 if I'm not mistaken.

If this can be reproduced on a 1.10 cluster then we can start diving in, otherwise then I'd say this is something we cannot support. Sorry!

**Comment by bacongobbler** [comment] 2018-06-08 06:18
Oops, just saw that you already tested this on newer clusters and it sounds like this works as intended on supported clusters, so it looks like it's just a version incompatibility issue. In that case I'm going to close this as a wontfix. Thanks!

**Closed by bacongobbler** 2018-06-08 06:18 UTC
Labels: question/support
