### ISSUE TITLE
Error: no available release name found

### ISSUE THREAD

**Issue by latermonk** [kubernetes/helm#3774] opened 2018-03-28 06:07 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersi
on:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersi
on:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):   kubeadm  create the cluster
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVer
sion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

after install helm to  /usr/lcoal/bin , exec  helm init and then helm repo update       ,but  when  helm install stable/mysql , the output is  Error: no available release name found.

Is there  anyone  know the real reason for this  ?

**Comment by dshamanthreddy** [comment] 2018-03-29 04:12
Same issue

**Comment by bacongobbler** [comment] 2018-04-11 21:11
This is likely due to misconfigured RBAC permissions. See https://docs.helm.sh/using_helm/#role-based-access-control for more information.

Closing as a duplicate of #3055.

**Closed by bacongobbler** 2018-04-11 21:11 UTC
Labels: question/support
