### ISSUE TITLE
Feature: Add --wait option to helm init

### ISSUE THREAD

**Issue by rstuven** [kubernetes/helm#2796] opened 2017-08-11 14:19 UTC
As `helm install` has a `--wait` option ("_if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment are in a ready state before marking the release as successful._"), this could be useful for `helm init` too, in order to avoid "Error: could not find a ready tiller pod", for example, in a script that tries to install a chart right after installing Tiller, without waiting for an arbitrary amount of time.

**Comment by bacongobbler** [comment] 2017-08-11 19:57
closing as a duplicate of #2114.

**Closed by bacongobbler** 2017-08-11 19:57 UTC
