### ISSUE TITLE
helm dep up reports "directory not found" for local charts

### ISSUE THREAD

**Issue by furuholm** [kubernetes/helm#2887] opened 2017-09-01 07:12 UTC
I have a helm project with a local subchart ```mydep``` listed in requirements.yaml

```
dependencies:
- name: mydep
  version: 0.1.0
  repository: file://charts/mydep/
```

The following error is reported when I run ```helm dep up``` in Helm 1.6.0  

```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Save error occurred:  directory /Users/tobias/proj/charts/mydep not found
Deleting newly downloaded charts, restoring pre-update state
Error: directory /Users/tobias/proj/charts/mydep not found
```
Note that the directory /Users/tobias/proj/charts/mydep does indeed exist

The same command works in Helm 1.5.1 though:

```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Deleting outdated charts
Saving 1 charts
```

The issue is present on both Mac and Linux.

**Comment by spmason** [comment] 2017-09-04 21:26
I just came across this and it seems like helm doesn't like the referenced chart living in the same `charts/` folder that it's eventually going to place the tarball in

If I instead move my charts to a `helm-charts/`folder then local repositories work for me again

**Comment by furuholm** [comment] 2017-09-05 08:18
I've verified your findings @spmason. Thanks! 

Agree that this should either be considered a bug or a better message is warranted as this is a breaking change for those putting the charts in the charts directory (which to me seems reasonable).

**Comment by spmason** [comment] 2017-09-05 11:16
I'd like to weigh in with how, as a newcomer to helm, I intuitively expected this to work.  

Basically I expected my own charts in `charts/<chart_name>` folders to be ignored, because they're folders and thus implicitly "user managed".  Then any dependencies in `requirements.yaml` get added as tarballs in the root of `charts/` by the usual `helm dependency` commands.

How it seems to work instead is that helm expects to explicitly manage _everything_ inside `charts/`, to the point where it actively deletes any of my folders inside `charts/` when I `helm dependency update`.  The first time this happened I was quite surprised and very thankful for source-control!

Hopefully this will help guide contributors on the proper solution to this problem, or perhaps there are very valid reasons the reasons why it can't work the way I expected.

**Comment by jascott1** [comment] 2017-09-05 19:54
@furuholm You listed Helm 1.6.0 but I assume you mean 2.6.0. We just released version 2.6.1 which fixes dependency deleting. Would you be able to test 2.6.1 to see if it solves your issue? If not we can continue to troubleshoot. Thanks.

@spmason The deleted charts issue was fixed in the latest Helm release v2.6.1 as you can see in the Changelog. 
https://github.com/kubernetes/helm/releases/tag/v2.6.1
Please give that a try and let us know if you have any problems.

**Comment by jascott1** [comment] 2017-09-08 01:05
@furuholm I have confirmed this is a bug with relative charts. LoadFiles is not seeing the base filenames for the relative charts when it does the comparison to build the chart struct. I will keep looking at it and submit a PR. Sorry about the trouble but thanks for reporting this.

**Comment by jascott1** [comment] 2017-09-29 19:53
@furuholm Just realized I was seeing a separate issue with `file://` paths and conflated it with yours (sorry about that).  `requirements.yaml` specifies the source for the chart, so Im not sure that it makes sense to have source and destination (charts/) be the same.

**Comment by furuholm** [comment] 2017-09-30 09:14
I think it’s perfectly resonable to disallow charts as the source directory. But I also think it is reasonable to assume that many users will put them there when starting using relative charts. I think a better error message is the way to go.

**Comment by jascott1** [comment] 2017-10-02 22:24
I agree an error for that situation would be an improvement. Its confusing because you can just put charts into charts/ dir and not use requirements.yaml and that works.

**Comment by jascott1** [comment] 2017-10-02 22:25
@furuholm Im going to close this since we understand the problem but please open an issue for a better error if you feel strongly about it. Thanks!

**Closed by jascott1** 2017-10-02 22:25 UTC
Labels: bug
