### ISSUE TITLE
CustomResourceDefinitions in dependencies

### ISSUE THREAD

**Issue by michas2** [kubernetes/helm#3331] opened 2018-01-10 15:32 UTC
I tried to create a chart which should depend on nginx-ingress and cert-manager. (cert-manager should provide the certs for the nginx, which should connect the main application.)

Now that I put everything together, I tried to install the resulting chart, but it seems it created the different resources in the "wrong" order. Especially cert-manager defines some custom resources (certs), and my main application will try to create some of these. Unfortunately the definition comes **after** the creation and therefore the installation fails. :(

Is there a way to tell helm to **first** create the definitions and only then try to create those kind of resources?

**Comment by bacongobbler** [comment] 2018-01-10 15:40
closing this as a duplicate of https://github.com/kubernetes/helm/issues/2994 and https://github.com/kubernetes/helm/issues/3325 so we can keep the discussion all in one ticket. Thanks!

**Closed by bacongobbler** 2018-01-10 15:40 UTC
