### ISSUE TITLE
'Undelete' of a release not possible

### ISSUE THREAD

**Issue by mduft** [kubernetes/helm#4137] opened 2018-05-29 11:05 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm-dind-cluster with 2 nodes.

I want to use Helm to deploy our software. Unfortunately this software has some history, and is more like the opposite of cloud native :) This means that rolling upgrade and other cloud buzzwords simply don't match. So: we need to take the application offline during upgrades to be able to perform database schema and data migration. Since k8s/helm don't have a "stop" button, the approach is to delete the deployment, right? Now, I would prefer to not loose the helm history for my deployments, thus I tried to delete, and afterwards 'undelete' (with helm rollback). This does not seem to work - although I read somewhere that it /should/ work. It's a little hard to find information, maybe I'm doing something stupid :)

```
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm delete productive
release "productive" deleted
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm list -a
NAME      	REVISION	UPDATED                 	STATUS 	CHART           	NAMESPACE
productive	1       	Tue May 29 12:41:52 2018	DELETED	wamas-helm-5.8.0	default  
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm rollback productive 1
Error: "productive" has no deployed releases
```

Note that all the kubernetes objects for the deployment ARE re-created despite the error message (at least this seems to be a bug :D) but the release changes to PENDING_ROLLBACK.

```
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm list -a
NAME      	REVISION	UPDATED                 	STATUS          	CHART           	NAMESPACE
productive	3       	Tue May 29 12:50:36 2018	PENDING_ROLLBACK	wamas-helm-5.8.0	default  
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ kubectl get all
NAME                                              READY     STATUS    RESTARTS   AGE
pod/productive-all-in-one-58c5cb8999-cpx8n        1/1       Running   0          17m
pod/productive-message-server-64d5ccb4f-8wv69     1/1       Running   1          17m
pod/productive-settings-server-769cfb4777-4nn44   1/1       Running   0          17m

[snip more services, etc.]

```

I'm - as mentioned before - not sure whether this is a bug or not, any help appreciated.

**Comment by mduft** [comment] 2018-05-29 11:57
Saw that there is a way newer release, so re-setup the cluster with Helm/Tiller 2.9.1. Exactly the same behaviour:

mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm list -a
NAME      	REVISION	UPDATED                 	STATUS  	CHART           	NAMESPACE
productive	1       	Tue May 29 13:50:07 2018	DEPLOYED	wamas-helm-5.8.0	default  
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm delete productive
release "productive" deleted
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm list -a
NAME      	REVISION	UPDATED                 	STATUS 	CHART           	NAMESPACE
productive	1       	Tue May 29 13:50:07 2018	DELETED	wamas-helm-5.8.0	default  
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm rollback productive 1
Error: "productive" has no deployed releases
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm list -a
NAME      	REVISION	UPDATED                 	STATUS          	CHART           	NAMESPACE
productive	2       	Tue May 29 13:55:24 2018	PENDING_ROLLBACK	wamas-helm-5.8.0	default  
mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm status productive
LAST DEPLOYED: Tue May 29 13:55:24 2018
NAMESPACE: default
STATUS: PENDING_ROLLBACK

RESOURCES:
==> v1/PersistentVolumeClaim
NAME                   STATUS  VOLUME                 CAPACITY  ACCESS MODES  STORAGECLASS  AGE
productive-wamas-jms   Bound   productive-wamas-jms   5Gi       RWO           9s
productive-wamas-logs  Bound   productive-wamas-logs  5Gi       RWX           9s

[snip]

mduft@fril0041 /ssd/other/wamas-docker/wamas-helm-new $ helm upgrade productive .
Error: UPGRADE FAILED: "productive" has no deployed releases

**Comment by mduft** [comment] 2018-05-29 12:38
Found this, which describes the same issue: https://www.bountysource.com/issues/56292958-rollback-of-a-deleted-release-fails-in-helm-v2-8-2

**Comment by bacongobbler** [comment] 2018-05-29 13:52
Hey, because this is a duplicate of #3722 let's close this and follow up there so we're working off a single ticket. Thanks!

**Closed by bacongobbler** 2018-05-29 13:52 UTC

**Comment by mduft** [comment] 2018-05-29 13:55
Sure. Somehow I was unable to find the other issue :) good to see there is one already :D
