### ISSUE TITLE
How to set helm bin path to be part of jar file

### ISSUE THREAD

**Issue by Alol-sw** [kubernetes/helm#3630] opened 2018-03-07 23:02 UTC
Hi,

I am new to helm and I have the below query.

I am automating the helm chart installation using java.

I have installed the helm binary under path /home/user/bin/helm and whenever the helm command to be executed I am giving the complete path and the command like
/home/user/bin/helm list releasesname.

When I execute the code in my local environment it executes.Now I wanted to execute the same code in a Jenkins environment where it is not good way to have my home directory mentioned in the code.

Is there a way to set the generic path for the helm binary to execute the helm commands that the code can be executed in any environment without modifications.

@kamesh2229

**Comment by bacongobbler** [comment] 2018-03-07 23:05
You should be able to append $HOME/bin to your path, like so:

```
$ export PATH=$HOME/bin:$PATH
```

You could also move helm to `/usr/local/bin` which should work on most operating systems.

Most operating systems do not add $HOME/bin to your $PATH.

**Comment by bacongobbler** [comment] 2018-03-07 23:06
closing as a duplicate of #3604 :)

**Closed by bacongobbler** 2018-03-07 23:06 UTC
Labels: question/support
