### ISSUE TITLE
Proposal: Make kube-config values available to templates

### ISSUE THREAD

**Issue by rodcloutier** [kubernetes/helm#2613] opened 2017-06-22 17:27 UTC
In our daily usage, we often target minikube and cloud hosted clusters. 
Each have separate contraints that need to be adressed in the chart and have selectors to activate or deactivate the features needed which are controlled by the values file. Something along the lines of

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-name
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    project/app: api-gateway
    project/exposure: external
  annotations:
    {{- if eq .Values.clusterType "gke" }}
    company.com/dns-prefix: "{{ .Values.gke.dnsPrefix }}"
    company.com/dns-zone: "{{ .Values.gke.dnsZone }}"
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  tls:
    - secretName: api-gateway-secret
  rules:
  - http:
      paths:
        {{- if eq $.Values.clusterType "gke" }}
        - path: /*
        {{- else }}
        - path: /
        {{- end }}
          backend:
            serviceName: kong-proxy
            servicePort: kong-proxy

````

``` 
# values.yaml
# The type of cluster we deploy to.
clusterType: gke
```
Since we favor security, we have the default to be configuration for the cloud cluster. This leads to having helm command that look like:

`helm install --set clusterType=minikube repo/chart`

If were to have access to the kubeconfig values, we could use the information to avoid  asking the developers to remember the proper flag. Maybe something like

```
{{- if eq $.Kubeconfig.current-context "minikube" }}
- path: /
{{- else }}
- path: /*
{{- end }}
```
Further extension could be to actually properly query the config to avoid relying on the name of the context that can be changed:

```
 {{- if eq $.Kubeconfig.clusters[$.Kubeconfig.contexts[$..Kubeconfig.current-context].cluster].name "minikube" }}
```
> The syntax might not be possible but it is to present the objective

**Comment by rodcloutier** [comment] 2017-08-03 19:07
@thomastaylor312 @michelleN Any idea if this could become a reality? Would a PR be welcome?

**Comment by thomastaylor312** [comment] 2017-08-07 21:24
I can see a lot of value in this idea. I think a PR would be a good idea and we can discuss some of the details on there. It also may be helpful to bring up this proposal in the helm-users slack channel to get some more feedback

**Comment by bacongobbler** [comment] 2017-08-08 17:49
I think this would be valuable to add to the [`Capabilities`](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/builtin_objects.md) object if there was some way to identify the cloud provider from the Kubernetes API.

**Comment by rodcloutier** [comment] 2017-08-26 19:23
The api machinery version struct is actually information gathered at compile time. I doubt that the platform would reflect the cloud provider.

**Comment by rodcloutier** [comment] 2017-08-26 20:53
Looking at the API there doesn't seem to be any reliable way to query or inspect what the cloud provider is. The closest I have found is to inspect the `node.spec.providerID` which will have a `provider_name:id` value. 

In the case of minikube, it is empty. But this do would also be the case for any local install. Minikube also as the `ExternalID` set to `minikube`.

In the case of a cluster with nodes spread across providers, this becomes harder since every node could have a different provider.

I would go, at first,  with something along the line of exposing the kube config from which the `helm` command is run.

**Comment by bacongobbler** [comment] 2017-11-01 00:32
closing as a duplicate request. See https://github.com/kubernetes/helm/issues/2055

**Closed by bacongobbler** 2017-11-01 00:32 UTC
Labels: proposal

**Comment by rajatjindal** [comment] 2017-12-09 03:54
Hi @bacongobbler 

The issue https://github.com/kubernetes/helm/issues/2055 refers to this issue as dependency, and this is marked as duplicate of that issue. 

was it decided to fix this on helm side? can you please update the helm ticket to reflect what was the final decision
