### ISSUE TITLE
Multiple upgrades without changes generates new revisions

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [kubernetes/helm#3177] opened 2017-11-21 11:53 UTC
## Issue
Don't know if this is by design, running `helm upgrade` multiple times without changes generates new revisions.
Actually we are running upgrades in CI and using `--history-max` option cause our history to be filled of clone revisions erasing the different ones.

## How to reproduce
Run upgrade 2 times without changes
`helm upgrade --install --wait my-release ./my-chart -f./my-values.yaml`
`helm upgrade --install --wait my-release ./my-chart -f./my-values.yaml`

## Compare revisions
`helm get my-release --revision=2 > my-release-new`
`helm get my-release --revision=1 > my-release-old`
`diff my-release-old my-release-new`

**Comment by jascott1** [comment] 2017-11-27 22:37
Hi @SharpEdgeMarshall,
Helm increments the revision when you perform an upgrade. It does not diff the release to make any decisions. It does not auto increment anything other than the release revision. This behavior is by design. Perhaps we can find some solution for your use case. Can you describe more about what you are trying to accomplish?

**Comment by SharpEdgeMarshall** [comment] 2017-11-28 09:09
Actually i'm using a git repo containing initial configs for my cluster like: some manifests to install before Tiller, some custom values files for charts. When a commit is made the CI runs `helm upgrade xxx` on all charts configured and here the version increments even without changes.
I should give a look to brigade that helps orchestrating multiple charts but i don't know if it's able to mitigate the auto increment issue.

**Comment by jascott1** [comment] 2018-01-31 18:20
Since revision incrementing is functioning as designed Im going to close this. Please feel free to open an issue for a feature proposal if you want to discuss this for 3.x

**Closed by jascott1** 2018-01-31 18:20 UTC
Labels: question/support

**Comment by mausch** [comment] 2018-03-20 14:48
@SharpEdgeMarshall I've got the same setup and the exact same problem. Were you able to work around this with Brigade somehow?

**Comment by SharpEdgeMarshall** [comment] 2018-03-20 16:38
No I'm sorry, i didn't have time to try with brigade yet.
I think we need a more advanced solution to orchestrate and organize multiple Helm Charts upgrade and install.

**Comment by akin-tekeoglu** [comment] 2020-05-13 13:19
You can use [helm-diff](https://github.com/databus23/helm-diff) as a workaround.  You can apply `helm upgrade` if diff plugin returns something.
