### ISSUE TITLE
helm not working in kubernetes 1.9.0

### ISSUE THREAD

**Issue by thatsk** [kubernetes/helm#3371] opened 2018-01-22 06:18 UTC
Not working on Kubrnetes V1.9.0
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be4 GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be4 GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

helm list
Error: Unauthorized

helm install stable/nginx-ingress
Error: no available release name found

**Comment by thatsk** [comment] 2018-01-22 06:20
helm install --debug stable/nginx-ingress
[debug] Created tunnel using local port: '39896'

[debug] SERVER: "127.0.0.1:39896"

[debug] Original chart version: ""
[debug] Fetched stable/nginx-ingress to /home/kthakur/.helm/cache/archive/nginx-ingress-0.8.26.tgz

[debug] CHART PATH: /home/kthakur/.helm/cache/archive/nginx-ingress-0.8.26.tgz

Error: no available release name found

**Comment by bacongobbler** [comment] 2018-01-22 15:57
k8s 1.9 is not supported by v2.7.2. We'll be releasing v2.8.0 today which supports kubernetes v1.9. Can you try that once it's out? Thanks!

**Comment by tallaxes** [comment] 2018-01-22 22:59
Same problem with with helm 2.8.0 (k8s/kubeadm 1.9.1)

**Comment by bacongobbler** [comment] 2018-01-22 23:12
Yes, RBAC roles etc. are not installed by default. https://docs.helm.sh/using_helm/#role-based-access-control goes through the steps required to install tiller on an RBAC-enabled cluster (which the workaround in #2224 provides a solution for). :)

@thatsk can you please describe how you set up helm in your cluster?

**Comment by tallaxes** [comment] 2018-01-23 00:04
Missed that part, thanks!

**Comment by SlickNik** [comment] 2018-01-23 12:13
@tallaxes Awesome -- sounds like you got things working after following the instructions to install tiller on an RBAC-enabled cluster. Please confirm when you get a chance. :)

**Comment by thatsk** [comment] 2018-01-23 14:10
730  kubectl create serviceaccount tiller --namespace kube-system
  731  kubectl create -f rbac-config.yaml
  732  rm -rf ~/.helm/
  733  kubectl create -f rbac-config.yaml
  734  helm init --service-account tiller
  735  kubectl create namespace tiller-world
  736  kubectl create serviceaccount tiller --namespace tiller-world
  737   kubectl create -f role-tiller.yaml
  738  kubectl create -f rolebinding-tiller.yaml
  739  helm init --service-account tiller --tiller-namespace tiller-world
  740  helm install nginx --tiller-namespace tiller-world --namespace tiller-world
  741  helm install stable/nginx --tiller-namespace tiller-world --namespace tiller-world
  742  helm search
  743  helm install stable/nginx-ingress --tiller-namespace tiller-world --namespace tiller-world


The command 740 which is fetching nginx chart from helm repositories is not found and when i search i found there is another name with stable/nginx-ingress as per 743 command
but when I check the pod status it showing one container is crashloopbackoff

#->kubectl get pods --namespace tiller-world
NAME                                                         READY     STATUS             RESTARTS   AGE
queenly-cat-nginx-ingress-controller-687bf4b8f4-6l72r        0/1       CrashLoopBackOff   5          4m
queenly-cat-nginx-ingress-default-backend-558bc685df-vl4s4   1/1       Running            0          4m
tiller-deploy-6bf6bd5d98-xjq76                               1/1       Running            0          5m

and when i check the logs it shows permission issue.
 kubectl logs queenly-cat-nginx-ingress-controller-687bf4b8f4-6l72r --namespace tiller-world
I0123 14:09:34.244015       7 launch.go:113] &{NGINX 0.9.0-beta.15 git-a3e86f2 https://github.com/kubernetes/ingress}
I0123 14:09:34.244057       7 launch.go:116] Watching for ingress class: nginx
I0123 14:09:34.244370       7 launch.go:291] Creating API client for https://xx.xx.xx.xx1:443
I0123 14:09:34.263811       7 launch.go:304] Running in Kubernetes Cluster version v1.9 (v1.9.0) - git (clean) commit 925c127ec6b946659ad0fd596fa959be43f0cc05 - platform linux/amd64
F0123 14:09:34.264954       7 launch.go:136] ✖ It seems the cluster it is running with Authorization enabled (like RBAC) and there is no permissions for the ingress controller. Please check the configuration

**Comment by SlickNik** [comment] 2018-01-23 14:55
From the given output, it looks like helm and tiller are working correctly. 👍 

If you're trying to install the stable/nginx-ingress helm chart, you will need to set the value `rbac.create=true` (or specify an appropriate service account using `rbac.serviceAccountName`). Please take a look at the [nginx-ingress chart documentation](https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress) for more details.

**Comment by tallaxes** [comment] 2018-01-23 15:38
@SlickNik I had used the workaround, and have not not (yet) reinstalled from scratch using the instructions, but it looks like the instructions are roughly equivalent.

**Comment by thatsk** [comment] 2018-01-24 05:09
https://github.com/kubernetes/ingress-nginx/issues/1966

**Comment by thatsk** [comment] 2018-01-24 05:22
@SlickNik i already tired that and give an error i have mentioned in last comment at last
**helm install stable/nginx-ingress --tiller-namespace tiller-world --namespace tiller-world --set rbac.create=true**
Error: release interesting-chinchilla failed: clusterroles.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:tiller-world:tiller" cannot create clusterroles.rbac.authorization.k8s.io at the cluster scope

**Comment by SlickNik** [comment] 2018-01-24 11:22
@thatsk - It looks like the user you're running under doesn't have the required permissions to create  artifacts like clusterroles. Please ensure you're running with an account that has the required permissions. The other option here is for your cluster admin to create a ServiceAccount for the nginx ingress controller and then for you to set `rbac.serviceAccountName` in the nginx-ingress chart.

**Comment by bacongobbler** [comment] 2018-04-11 21:12
Closing as a duplicate of #3055.

**Closed by bacongobbler** 2018-04-11 21:12 UTC
Labels: question/support
