### ISSUE TITLE
`helm ls` output as JSON or YAML

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/helm#3462] opened 2018-02-06 16:00 UTC
Then the output could more easily be used in scripting.

My use case is orphaned CI runs that timed out and didn't clean up after themselves. To be able to list all helm releases, look at the dates, and delete the obviously orphaned ones. JSON and YAML are much easier to work with than parsing the text response.

**Comment by bacongobbler** [comment] 2018-02-06 16:05
https://github.com/kubernetes/helm/pull/2950 :)

**Comment by jascott1** [comment] 2018-02-07 19:41
Closing since its a duplicate of #1534 and PR #2950 is in-flight.

**Closed by jascott1** 2018-02-07 19:41 UTC
