### ISSUE TITLE
helm 2.8.1/2.8.2 issues with GKE clusters

### ISSUE THREAD

**Issue by calas** [kubernetes/helm#3664] opened 2018-03-13 12:11 UTC
I'm having issues trying run helm in a GKE cluster, I keep getting permission issues: 

```
$ helm list
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system": Unknown user "system:serviceaccount:kube-system:default"
```
Then when I try to install any chart I get the following: 

```
$ helm install stable/wordpress --name wordpress 
Error: release wordpress failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "default": Unknown user "system:serviceaccount:kube-system:default"

$ helm install stable/docker-registry --name docker-registry
Error: release docker-registry failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "default": Unknown user "system:serviceaccount:kube-system:default"

$ helm install stable/concourse --name concourse
Error: release concourse failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get namespaces in the namespace "default": Unknown user "system:serviceaccount:kube-system:default"
```
I'm using the following versions: 

* k8s: 1.7.12-gke.1, 1.8.7-gke.1 and 1.9.3-gke.0
* helm: 2.8.1 & 2.8.2
* tiller: 2.8.1 & 2.8.2

I've tried removing my `$HOME/.helm/` directory, creating a new cluster, reinstalling tiller several times but none worked.

**Comment by thomastaylor312** [comment] 2018-03-14 00:18
@calas I am betting that RBAC is configured and blocking tiller from working. Please check out [this guide](https://docs.helm.sh/using_helm/#securing-your-helm-installation) for more information about how to configure the proper RBAC roles. You may also want to check out the [secure-helm](https://github.com/michelleN/helm-secure-tiller) plugin

**Comment by calas** [comment] 2018-03-14 15:22
@thomastaylor312 That was the problem. I had helm working on an older cluster and it was very confusing that it stops working. Maybe the errors should be more clear or the documentation on how to install and setup a basic helm installation should be updated.

**Comment by bacongobbler** [comment] 2018-03-14 15:27
This isn't the first time I've heard that. I'll make a comment in the quickstart docs pointing to the RBAC documentation. :)

**Comment by bacongobbler** [comment] 2018-04-11 21:13
Closing as a duplicate of #3055.

**Closed by bacongobbler** 2018-04-11 21:13 UTC
Labels: question/support
