### ISSUE TITLE
linting empty scaffolded chart results in panic

### ISSUE THREAD

**Issue by michelleN** [kubernetes/helm#912] opened 2016-06-29 17:38 UTC
```
helm [master]$ bin/helm create mychart
Creating mychart
helm [master*]$ bin/helm lint mychart
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x1169880, 0xc8202180f0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
k8s.io/helm/pkg/chartutil.CoalesceValues(0xc820063e60, 0xc8201b5f80, 0xc8201a4a50, 0xc820515960, 0x0, 0x0)
	/Users/michellenoorali/gocode/src/k8s.io/helm/pkg/chartutil/values.go:153 +0x1f1
k8s.io/helm/pkg/lint/rules.Templates(0xc820515ac8)
	/Users/michellenoorali/gocode/src/k8s.io/helm/pkg/lint/rules/template.go:65 +0x542
k8s.io/helm/pkg/lint.All(0x7fff5fbffa06, 0x7, 0x0, 0x0, 0x0)
	/Users/michellenoorali/gocode/src/k8s.io/helm/pkg/lint/lint.go:35 +0x16a
main.lintCmd(0x21e0280, 0xc8202b1980, 0x1, 0x1, 0x0, 0x0)
	/Users/michellenoorali/gocode/src/k8s.io/helm/cmd/helm/lint.go:63 +0x18b
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0x21e0280, 0xc8202b1940, 0x1, 0x1, 0x0, 0x0)
	/Users/michellenoorali/gocode/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:561 +0x62c
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x21dfa80, 0x21e0280, 0x0, 0x0)
	/Users/michellenoorali/gocode/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:651 +0x55c
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0x21dfa80, 0x0, 0x0)
	/Users/michellenoorali/gocode/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:610 +0x2d
main.main()
	/Users/michellenoorali/gocode/src/k8s.io/helm/cmd/helm/helm.go:89 +0x23
```

I believe this is due to empty values.yaml

**Comment by prydonius** [comment] 2016-06-29 19:16
Did some debugging and found that the issue is when the values.yaml file is not empty, but has no data inside (i.e. completely commented). It seems that the unmarshalling in [values.go#L115](/kubernetes/helm/blob/master/pkg/chartutil/values.go#L115) returns a nil map if there is nothing to unmarshal. This causes the panic when trying to assign the overrides. Should be easily fixable in that function by ensuring we always return a non-nil map.

By the way, I noticed that the overrides map isn't really being used anymore in [release_server.go#L241](/kubernetes/helm/blob/master/cmd/tiller/release_server.go#L241), and @migmartri's change in the linter in #899 also [stops using it](https://github.com/kubernetes/helm/pull/899/files#diff-c508e0fda01b39eddfe1d6a4449fe685R312). I'm wondering if the overrides param is actually being used before, and if not, should we remove it?

/cc @technosophos

**Comment by michelleN** [comment] 2016-06-29 20:07
Thanks @prydonius. It looks like this gets fixed by #912. 

I'll let @technosophos answer the overrides param question.

**Comment by prydonius** [comment] 2016-06-29 20:22
#899 does fix the linting, but only since it doesn't pass any overrides, and therefore it doesn't try to assign anything to the map. Since overrides is not being used anymore, I'm not sure if it's worth fixing ReadValues to always return a non-nil map

**Comment by technosophos** [comment] 2016-06-29 22:32
One of my recent changes in PR #902 fixes the nil map problem, too. So this _should_ go away when we have those two PRs merged.

**Comment by technosophos** [comment] 2016-06-29 22:42
The error is still there with #902 merged.

**Closed** 2016-06-29 23:01 UTC
