### ISSUE TITLE
helm list fails

### ISSUE THREAD

**Issue by wilreichert** [kubernetes/helm#1085] opened 2016-08-22 05:58 UTC
Following the helm getting started docs & not getting very far.

Starting with
-  n1-standard 3 node kube 1.3.4 cluster on google cloud, all defaults.
- latest helm 2.0.0 alpha 3 build
- most recent git pull of helm repo

```
goat@monkey ~/src/helm $ helm init
$HELM_HOME has been configured at /home/goat/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
goat@monkey ~/src/helm $ kubectl get deployments --namespace=kube-system
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
heapster-v1.1.0   1         1         1            1           2m
tiller-deploy     1         1         1            1           58s
goat@monkey ~/src/helm $ helm install docs/examples/alpine
left-waterbuffalo
goat@monkey ~/src/helm $ helm status left-waterbuffalo
Last Deployed: Mon Aug 22 14:53:11 2016
Status: DEPLOYED
Resources:
==> v1/Pod
NAME                          READY     STATUS    RESTARTS   AGE
left-waterbuffalo-my-alpine   1/1       Running   0          18s


goat@monkey ~/src/helm $ helm list
2016/08/22 14:53:41 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
```

logs on the tiller pod
```
$ kubectl logs -f pod/tiller-deploy-610593871-ulo1c --namespace=kube-system
Tiller is running on :44134
Tiller probes server is running on :44135
Storage driver is ConfigMap
2016-08-22 05:53:11.094872 I | Getting release "left-waterbuffalo" from storage
2016-08-22 05:53:11.098251 I | Preparing template alpine/templates/alpine-pod.yaml
2016-08-22 05:53:11.099207 I | Executing pre-install hooks for left-waterbuffalo
2016-08-22 05:53:11.099291 I | Hooks complete for pre-install left-waterbuffalo
2016-08-22 05:53:11.117677 I | Executing post-install hooks for left-waterbuffalo
2016-08-22 05:53:11.117893 I | Hooks complete for post-install left-waterbuffalo
2016-08-22 05:53:11.118288 I | Create release "left-waterbuffalo" in storage
2016-08-22 05:53:29.772096 I | Getting release "left-waterbuffalo" from storage
2016-08-22 05:53:29.776565 I | Doing get for: 'left-waterbuffalo-my-alpine'
2016-08-22 05:53:40.938282 I | Listing all deployed releases in storage
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x576ec9]

goroutine 57 [running]:
panic(0x14729c0, 0xc42000a030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/pkg/storage.StatusFilter.func1(0xc420389570, 0xc4203cabe0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/filter.go:65 +0x19
k8s.io/helm/pkg/storage.FilterFunc.Check(0xc4203cabe0, 0xc420389570, 0xc420389570)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/filter.go:30 +0x35
k8s.io/helm/pkg/storage.(*Storage).ListDeployed.func1(0xc420389570, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:84 +0x41
k8s.io/helm/pkg/storage/driver.(*ConfigMaps).List(0xc42044bd10, 0x16c1610, 0x1, 0x13d1d60, 0xc4203ca1f0, 0x37ece7d1, 0x1ec2f80)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/driver/cfgmaps.go:108 +0x282
k8s.io/helm/pkg/storage.(*Storage).ListDeployed(0xc42044bd20, 0x7f6a2daeb000, 0x0, 0x0, 0xc420451b78, 0x16be01e)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/storage/storage.go:85 +0xc1
main.(*releaseServer).ListReleases(0xc420022038, 0xc420014840, 0x1e950a0, 0xc4203ca1e0, 0x0, 0xc420020cd0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/cmd/tiller/release_server.go:64 +0x4a
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_ListReleases_Handler(0x1588420, 0xc420022038, 0x1e937e0, 0xc420451b00, 0x0, 0xc420139000)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:518 +0x117
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420450000, 0x1e951c0, 0xc42043b710, 0xc420076700, 0xc420104d00, 0x1eb06c0, 0xc42028bbc0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:575 +0x22a
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420450000, 0x1e951c0, 0xc42043b710, 0xc420076700, 0xc42028bbc0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:650 +0xc33
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4203ca0e0, 0xc420450000, 0x1e951c0, 0xc42043b710, 0xc420076700)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:323 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:324 +0xa3
```

**Comment by technosophos** [comment] 2016-08-22 19:31
This is a duplicate of #1083.

**Comment by adamreese** [comment] 2016-08-30 17:52
For cause/fix/workaround: https://github.com/kubernetes/helm/issues/1083#issuecomment-243520610

**Closed by adamreese** 2016-08-30 17:52 UTC

**Comment by vhosakot** [comment] 2018-05-30 20:50
I saw the `Error: transport is closing` error too when I ran `helm install`, and after doing `rm -rf ~/.helm`, the error was not seen anymore. Guess deleting the helm cache (`rm -rf ~/.helm`) may resolve the error.
