### ISSUE TITLE
String value cut off after comma during template expansion

### ISSUE THREAD

**Issue by mkornacker** [kubernetes/helm#4173] opened 2018-06-05 02:58 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
install --dry-run will reproduce this

I am supplying command line parameters to a binary like so: 
helm install ... --set component.extraargs="--vmodule=a=2,b=2" ...
which is appended to the binaries command line args.

However, this is cut off at the first comma, and all I'm getting is 
--vmodule=a=2

I need to escape the ',' ("--vmodule=a=2\\,b=2") in order to get the desired command line.

If this is a feature, it's certainly an unexpected one, and also not one that I was able to locate with moderate effort in any kind of docs.

**Comment by bacongobbler** [comment] 2018-06-08 05:56
https://docs.helm.sh/using_helm/#the-format-and-limitations-of-set goes into more detail on the format and how to escape things like quotes. This is the intended behaviour of the --set parser according to the docs, and it sounds like you've found the workaround as described in the docs. :)

Closing!

**Closed by bacongobbler** 2018-06-08 05:56 UTC
