### ISSUE TITLE
docs.helm.sh has multiple broken links

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/helm#4155] opened 2018-06-01 18:42 UTC
Tried using latest Chrome|Firefox (on Linux)

https://docs.helm.sh/
https://docs.helm.sh/using_helm/#quickstart
![image](https://user-images.githubusercontent.com/1022400/40857649-96fb50d8-6590-11e8-8f54-6ad68d334ab8.png)

These links don't appear to do anything: perhaps the anchors are broken?
https://docs.helm.sh/using_helm/#quickstart-guide 
https://docs.helm.sh/using_helm/#installing-helm
https://docs.helm.sh/using_helm/#kubernetes-distribution-guide

https://docs.helm.sh/using_helm/#installation-frequently-asked-questions
![image](https://user-images.githubusercontent.com/1022400/40857719-d4fb37d6-6590-11e8-8527-07878518850e.png)

Going to try navigate the content directly on the github repo

**Comment by bacongobbler** [comment] 2018-06-01 19:15
Might be relevant since we changed a few things in https://github.com/helm/helm-www/pull/93

**Comment by bacongobbler** [comment] 2018-06-07 02:13
Closing as a duplicate of helm/helm-www#99

**Closed by bacongobbler** 2018-06-07 02:13 UTC

**Comment by flynnduism** [comment] 2018-06-07 17:48
Caching issues with blob storage have been resolved - all the rendering issues should now be purged and resolved.

[https://docs.helm.sh/using_helm/#quickstart-guide](https://docs.helm.sh/using_helm/#quickstart-guide)

**Comment by trjh** [comment] 2019-04-02 22:28
Has this issue re-occured?  I'm seeing the exact same problems, from Chrome on a Windows 7 system, and from Safari on an OS-X system.

**Comment by flynnduism** [comment] 2019-04-03 04:32
@trjh I see those sections you are referring to - the content seems to have been only partially built on the most recent deployment.

I've rebuilt the site now - it has restored those sections back to normal. Thanks for spotting this!
