### ISSUE TITLE
Helm unable to use merged kubeconfig

### ISSUE THREAD

**Issue by FUSAKLA** [kubernetes/helm#3453] opened 2018-02-05 09:27 UTC
Hi, recently I refactored structure of my kubeconfigs and used kubectl feature [allowing to merge multiple kube configs](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#append-homekubeconfig-to-your-kubeconfig-environment-variable).

Sadly it looks like Helm does not support this feature failing with

```bash
$HELM_HOME has been configured at /home/bar/.helm.
Error: could not get kubernetes client: could not get Kubernetes config for context "": stat /home/bar/.kube/conf/foo1.yaml:/home/bar/.kube/conf/foo2.yaml:/home/bar/.kube/conf/foo3.yaml:/home/bar/.kube/conf/foo4.yaml:/home/bar/.kube/conf/foo5.yaml: no such file or directory
```

Am I missing some option to allow this or is it really impossible. 
If it's the second case would be possible to add this feature?

**Comment by bacongobbler** [comment] 2018-02-05 14:39
Closing as a duplicate of https://github.com/kubernetes/helm/issues/3378.

**Closed by bacongobbler** 2018-02-05 14:39 UTC

**Comment by FUSAKLA** [comment] 2018-02-05 19:41
Sorry for the duplicate I did not find the mentioned issue before.
