### ISSUE TITLE
Getting Error: context deadline exceeded with AWS and helm 2.5.1

### ISSUE THREAD

**Issue by Miyurz** [kubernetes/helm#2827] opened 2017-08-18 11:46 UTC
As I try to list all helm releases from one of the repos, I am able to reproduce https://github.com/kubernetes/helm/issues/2409 though on AWS this time 

How did I reproduce this:
`helm list --kube-context np.domain.net --host domain-helm-charts.s3-website-eu-west-1.amazonaws.com --all`

Look my comment here :  https://github.com/kubernetes/helm/issues/2409#issuecomment-323308304
 
**helm version: 2.5.1 (both client and server)**

```
$ helm version --kube-context np.k8s.saltside.io
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}


Tiller logs here:
$ kubectl logs tiller-deploy-3354727571-cmjvn -n kube-system -f
[main] 2017/08/18 11:05:29 Starting Tiller v2.5.1 (tls=false)
[main] 2017/08/18 11:05:29 GRPC listening on :44134
[main] 2017/08/18 11:05:29 Probes listening on :44135
[main] 2017/08/18 11:05:29 Storage driver is ConfigMap
[storage] 2017/08/18 11:06:08 listing all releases with filter
[tiller] 2017/08/18 11:06:29 getting history for release kube2iam
[storage] 2017/08/18 11:06:29 getting release history for "kube2iam"
[tiller] 2017/08/18 11:06:29 preparing update for kube2iam
[storage] 2017/08/18 11:06:29 getting last revision of "kube2iam"
[storage] 2017/08/18 11:06:29 getting release history for "kube2iam"
[tiller] 2017/08/18 11:06:29 rendering kube2iam chart using values
[tiller] 2017/08/18 11:06:29 performing update for kube2iam
[tiller] 2017/08/18 11:06:29 executing 0 pre-upgrade hooks for kube2iam
[tiller] 2017/08/18 11:06:29 hooks complete for pre-upgrade kube2iam
[kube] 2017/08/18 11:06:29 building resources from updated manifest
[kube] 2017/08/18 11:06:29 checking 1 resources for changes
[kube] 2017/08/18 11:06:29 Looks like there are no changes for DaemonSet "kube2iam-kube2iam"
[tiller] 2017/08/18 11:06:29 executing 0 post-upgrade hooks for kube2iam
[tiller] 2017/08/18 11:06:29 hooks complete for post-upgrade kube2iam
[storage] 2017/08/18 11:06:29 updating release "kube2iam.v6"
[tiller] 2017/08/18 11:06:29 creating updated release for kube2iam
[storage] 2017/08/18 11:06:29 creating release "kube2iam.v7"
[storage] 2017/08/18 11:06:30 getting last revision of "kube2iam"
[storage] 2017/08/18 11:06:30 getting release history for "kube2iam"
[kube] 2017/08/18 11:06:30 Doing get for DaemonSet: "kube2iam-kube2iam"
[storage] 2017/08/18 11:27:30 listing all releases with filter
[storage] 2017/08/18 11:29:31 listing all releases with filter

```

**Comment by philchristensen** [comment] 2017-08-18 19:02
One scenario that routinely causes this error is when you're running k8s on AWS and the node names don't exist as real host names. For example, in my env, my k8s hosts end up with the ip-x-x-x-x default hostname, which doesn't exist in my internal DNS.

The fix was to edit the manifest for the APIServer to include the `--kubelet-preferred-address-types=InternalIP` flag.

**Comment by SiriusRed** [comment] 2017-08-22 16:04
I have the same issue when I'm running any helm command (status, delete, update) and return 
```
E0822 16:01:19.279092     564 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:39597: bind: cannot assign requested address
Error: context deadline exceeded
$ echo $?
$ 1

**Comment by bacongobbler** [comment] 2017-08-22 16:25
@SiriusRed how is your cluster deployed? Did you use @philchristensen's suggestion? There's not a whole lot of information in this thread to help debug. We need cluster info/cloud provider info/helm version etc. to assist in support.

**Comment by thomastaylor312** [comment] 2017-09-02 22:14
@bacongobbler It looks like people are still reporting problems with it in the [original issue](https://github.com/kubernetes/helm/issues/2409#issuecomment-326532445) as well

**Comment by srossross** [comment] 2017-09-21 19:11
> The fix was to edit the manifest for the APIServer to include the --kubelet-preferred-address-types=InternalIP flag.

what does this mean?

**Comment by bacongobbler** [comment] 2017-09-21 19:16
While it's not very informative, [the CLI](https://kubernetes.io/docs/admin/kube-apiserver/) shows

> List of the preferred NodeAddressTypes to use for kubelet connections. (default [Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP])

**Comment by srossross** [comment] 2017-09-21 19:19
For me, this does not appear to be a kubelet/tiller issue. It seems to be the client. I can run `helm ls` from my mac just fine, but when I try to run it from an alpine docker container (where kubectl works fine) I get the `context deadline exceeded` error.

**Comment by gdmello** [comment] 2017-09-25 16:55
Got this issue as well. Here's my setup-
kubernetes: 1.7.1
AWS
Client: v2.5.0
Server: v2.6.0

i'll have to try @philchristensen suggestion.

**Comment by bacongobbler** [comment] 2017-11-01 18:57
closing this as a duplicate of #2409. Let's keep issues related to this error all in one ticket so we can collaborate and work together to solve this problem. Thanks so much for your reports!

**Closed by bacongobbler** 2017-11-01 18:57 UTC
Labels: question/support
