### ISSUE TITLE
helm list fails

### ISSUE THREAD

**Issue by jirih** [kubernetes/helm#3882] opened 2018-04-12 10:52 UTC
```
C:\minikube>helm list
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 127.0.0.1:8080: connect: connection refused
```

However, if I try to open the url in a browser, I get a valid page.

**Comment by bacongobbler** [comment] 2018-04-12 14:41
Dupe of #2464

**Closed by bacongobbler** 2018-04-12 14:41 UTC
