### ISSUE TITLE
helm test times out without an informative error message

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/helm#2340] opened 2017-04-28 10:02 UTC
**What Happened**

I ran `helm test` as documented below:

```
env KUBE_CONTEXT=np.k8s.saltside.io KUBE_NAMESPACE=development script/test-release test-tonaton
RUNNING: test-tonaton-kviberg-ton-smoke-test
E0428 09:51:24.205454   29091 portforward.go:175] lost connection to pod
Error: transport is closing
test-tonaton test failed! Capturing logs and cleaning up
test-tonaton-kviberg-ton-smoke-test Logs:

Error from server (NotFound): the server could not find the requested resource ( pods/log test-tonaton-kviberg-ton-smoke-test)
```

Note the `E0428 09:51:24.205454   29091 portforward.go:175] lost connection to pod`.  I described the pod and found these events:

```
Events:
  FirstSeen     LastSeen        Count   From                                                    SubObjectPath        Type             Reason          Message
  ---------     --------        -----   ----                                                    -------------        -------- ------          -------
  10m           10m             1       {default-scheduler }                                                         Normal           Scheduled       Successfully assigned test-tonaton-kviberg-ton-smoke-test to ip-172-20-41-138.ap-south-1.compute.internal
  10m           10m             1       {kubelet ip-172-20-41-138.ap-south-1.compute.internal}  spec.containers{smoke-test}   Normal          Pulling         pulling image "saltside/kviberg-smoke-test:245719c"
  5m            5m              1       {kubelet ip-172-20-41-138.ap-south-1.compute.internal}  spec.containers{smoke-test}   Normal          Pulling         pulling image "saltside/kviberg-smoke-test:245719c"
  4m            4m              1       {kubelet ip-172-20-41-138.ap-south-1.compute.internal}  spec.containers{smoke-test}   Normal          Pulled          Successfully pulled image "saltside/kviberg-smoke-test:245719c"
  4m            4m              1       {kubelet ip-172-20-41-138.ap-south-1.compute.internal}  spec.containers{smoke-test}   Normal          Created         Created container with docker id a0b7b344fbeb; Security:[seccomp=unconfined]
  4m            4m              1       {kubelet ip-172-20-41-138.ap-south-1.compute.internal}  spec.containers{smoke-test}   Normal          Started         Started container with docker id a0b7b344fbeb
```

You can see that it took longer to pull the image and start the container than the default `--timeout`.

**What I expected to Happen**

`helm test` should say "timed-out waiting for pod" or the like. This way I know the problem was with the test pod and _not_ with helm/tiller.

**Work-around**

I've doubled the `--timeout` to account for the time to pull images. The real pull time varies greatly depending on the node the pod schedules on (with how many existing layers there are or what else is happening on that node).

**Versions**

```
kviberg $ helm version
Client: &version.Version{SemVer:"v2.2.3", GitCommit:"1402a4d6ec9fb349e17b912e32fe259ca21181e3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
```

**Comment by michelleN** [comment] 2017-05-07 03:45
hey @ahawkins - I tried to re-creating this scenario and got:
```
helm [master*]$  bin/helm test quarreling-boxer
RUNNING: quarreling-boxer-service-test
UNKNOWN: quarreling-boxer-service-test: timed out waiting for the condition
```

Could you verify this is still a problem for you and if so, would you mind providing more details on how to reproduce it?
Thank you.

**Comment by ahawkins** [comment] 2017-05-07 04:03
I'm not sure how to reproduce it. My best guest is to create a pod that
cannot move out of the `Pending` state. Perhaps create a test pod that
uses defines a node selector that does not match any nodes in the
cluster. I guessing this happened when the Docker daemon on one of my
cluster nodes locked up breaking new pods/containers. That is difficult
to reproduce for sure!

On Sun, May 7, 2017, at 09:15 AM, Michelle Noorali wrote:
> hey @ahawkins[1] - I tried to re-creating this scenario and got:


> helm [master*]$  bin/helm test quarreling-boxer RUNNING: quarreling-boxer-service-
> test UNKNOWN: quarreling-boxer-service-test: timed out waiting for the
> condition
>> Could you verify this is still a problem for you and if so, would you
> mind providing more details on how to reproduce it?>  Thank you.


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/ahawkins
  2. https://github.com/kubernetes/helm/issues/2340#issuecomment-299680493

**Comment by michelleN** [comment] 2017-05-10 20:43
hm. I tried that and I'm still getting this:
```
helm $ bin/helm test bald-macaw
RUNNING: bald-macaw-service-test
ERROR: timed out waiting for the condition
```

**Comment by michelleN** [comment] 2017-06-07 02:22
Not able to reproduce this. If you haven't had any issues recently, would it be alright for me to close this issue and re-open if you see it again? @ahawkins

**Comment by bacongobbler** [comment] 2017-10-31 23:08
closing as inactive. Please re-open if this is reproducible. Thanks!

**Closed by bacongobbler** 2017-10-31 23:08 UTC
Labels: bug
