### ISSUE TITLE
Error: UPGRADE FAILED: no resource with the name "anything_goes" found

### ISSUE THREAD

**Issue by zuzzas** [kubernetes/helm#3275] opened 2017-12-19 11:18 UTC
Hi,

We are constantly hitting a problem that manifests itself with this `Error: UPGRADE FAILED: no resource with the name "site-ssl" found`, for example. They can appear after any innocuous update to a template.
Could you, please, help me with understanding the problem. What causes those messages to appear?

I've been unsuccessful in triaging the issue further, it may happen anytime, haven't really found a pattern yet.

Perhaps, there is a problem with how we deploy? `helm upgrade hmmmmm /tmp/dapp-helm-chart-20171219-20899-1ppm74grrwrerq --set global.namespace=hmm --set global.env=test --set global.erlang_cookie=ODEzMTBlZjc5ZGY5NzQwYTM3ZDkwMzEx --set global.tests=no --set global.selenium_tests=no --namespace hmm --install --timeout 300`

Helm: v2.7.2, v2.6.2, Kubernetes: v1.7.6, v1.8.5. I've tried every possible combination of these 4 versions, neither work.

**Comment by zuzzas** [comment] 2017-12-20 06:51
Completely removing release from Helm via `helm delete release` or simply deleting NS from Kubernetes works, but it is not a viable solution.

Why can't Helm just overwrite whatever is currently installed? Aren't we living in a declarative world with Kubernetes?

**Comment by jpoizat** [comment] 2017-12-21 15:25
Just got the same thing... quite new for me at it seems to be a new issue. delete the resource will fix it.
v2.7.2 with Kubernetes 1.7.7.
pretty it worked before...

**Comment by ajtrichards** [comment] 2017-12-21 15:31
I had this problem - it was due to a PersistentVolume that i'd created. To resolve, I deleted the PV and PVC. Ran `helm upgrade XXX XXX` and it worked fine. Probably still something that should be investigated as the PV did exist.

**Comment by jpoizat** [comment] 2017-12-21 15:34
I got the feeling it might be related to bad pv... but then the error is quite misleading !
also some weirds logs from tiller... seems that it is working on 2 version at the same time...

just tried with 2.7.1 with no luck...

[main] 2017/12/21 15:30:48 Starting Tiller v2.7.1 (tls=false)
[main] 2017/12/21 15:30:48 GRPC listening on :44134
[main] 2017/12/21 15:30:48 Probes listening on :44135
[main] 2017/12/21 15:30:48 Storage driver is ConfigMap
[main] 2017/12/21 15:30:48 Max history per release is 0
[tiller] 2017/12/21 15:30:55 preparing update for xxx
[storage] 2017/12/21 15:30:55 getting deployed release from "xxx" history
[tiller] 2017/12/21 15:30:56 copying values from xxx (v65) to new release.
[storage] 2017/12/21 15:30:56 getting last revision of "xxx"
[storage] 2017/12/21 15:30:56 getting release history for "xxx"
[tiller] 2017/12/21 15:30:59 rendering helm-xxx chart using values
2017/12/21 15:30:59 info: manifest "helm-xxx/templates/scheduler-deploy.yaml" is empty. Skipping.
2017/12/21 15:30:59 info: manifest "helm-xxx/templates/recomposer-deploy.yaml" is empty. Skipping.
2017/12/21 15:31:00 info: manifest "helm-xxx/templates/recomposer-pvc.yaml" is empty. Skipping.
2017/12/21 15:31:00 info: manifest "helm-xxx/templates/scheduler-pvc.yaml" is empty. Skipping.
2017/12/21 15:31:00 info: manifest "helm-xxx/templates/scheduler-secret.yaml" is empty. Skipping.
2017/12/21 15:31:00 info: manifest "helm-xxx/templates/recomposer-secret.yaml" is empty. Skipping.
[tiller] 2017/12/21 15:31:09 creating updated release for xxx
[storage] 2017/12/21 15:31:09 creating release "xxx.v80"
[tiller] 2017/12/21 15:31:09 performing update for xxx
[tiller] 2017/12/21 15:31:09 executing 0 pre-upgrade hooks for xxx
[tiller] 2017/12/21 15:31:09 hooks complete for pre-upgrade xxx
[tiller] 2017/12/21 15:31:11 preparing update for xxx
[storage] 2017/12/21 15:31:11 getting deployed release from "xxx" history
[storage] 2017/12/21 15:31:11 getting last revision of "xxx"
[storage] 2017/12/21 15:31:11 getting release history for "xxx"
[tiller] 2017/12/21 15:31:18 rendering helm-xxx chart using values
2017/12/21 15:31:18 info: manifest "helm-xxx/templates/scheduler-secret.yaml" is empty. Skipping.
2017/12/21 15:31:18 info: manifest "helm-xxx/templates/scheduler-pvc.yaml" is empty. Skipping.
2017/12/21 15:31:19 info: manifest "helm-xxx/templates/scheduler-deploy.yaml" is empty. Skipping.
[kube] 2017/12/21 15:31:28 building resources from updated manifest
[tiller] 2017/12/21 15:31:46 creating updated release for xxx
[storage] 2017/12/21 15:31:46 creating release "xxx.v81"
[tiller] 2017/12/21 15:31:47 performing update for xxx
[tiller] 2017/12/21 15:31:47 executing 0 pre-upgrade hooks for xxx
[tiller] 2017/12/21 15:31:47 hooks complete for pre-upgrade xxx
[kube] 2017/12/21 15:31:49 checking 7 resources for changes
[kube] 2017/12/21 15:31:49 Looks like there are no changes for Secret "xxx-helm-xxx-nginx-secret"
[kube] 2017/12/21 15:31:50 Looks like there are no changes for Secret "xxx-application-secret"
[kube] 2017/12/21 15:31:50 Looks like there are no changes for Secret "azure-secret"
[kube] 2017/12/21 15:31:51 Looks like there are no changes for ConfigMap "xxx-helm-xxx-nginx-config"
[kube] 2017/12/21 15:31:51 Looks like there are no changes for ConfigMap "xxx-application-config"
[kube] 2017/12/21 15:31:51 Looks like there are no changes for Service "xxx-application-svc"
[kube] 2017/12/21 15:31:51 Looks like there are no changes for StatefulSet "xxx-application"
[tiller] 2017/12/21 15:31:51 executing 0 post-upgrade hooks for xxx
[tiller] 2017/12/21 15:31:51 hooks complete for post-upgrade xxx
[storage] 2017/12/21 15:31:51 updating release "xxx.v65"
[tiller] 2017/12/21 15:31:51 updating status for updated release for xxx
[storage] 2017/12/21 15:31:51 updating release "xxx.v80"
[kube] 2017/12/21 15:31:57 building resources from updated manifest
[kube] 2017/12/21 15:32:10 checking 11 resources for changes
[kube] 2017/12/21 15:32:10 Looks like there are no changes for Secret "xxx-helm-xxx-nginx-secret"
[tiller] 2017/12/21 15:32:10 warning: Upgrade "xxx" failed: no resource with the name "xxx-recomposer-secret" found
[storage] 2017/12/21 15:32:10 updating release "xxx.v65"
[storage] 2017/12/21 15:32:10 updating release "xxx.v81"

**Comment by jpoizat** [comment] 2017-12-21 16:12
seems it get confused at doing to release at the same time...

just reapplied the same config twice... 

[tiller] 2017/12/21 15:50:46 preparing update for xxx
[storage] 2017/12/21 15:50:46 getting deployed release from "xxx" history
[storage] 2017/12/21 15:50:46 getting last revision of "xxx"
[storage] 2017/12/21 15:50:46 getting release history for "xxx"
[tiller] 2017/12/21 15:50:50 rendering helm-xxx chart using values
2017/12/21 15:50:50 info: manifest "helm-xxx/templates/scheduler-pvc.yaml" is empty. Skipping.
2017/12/21 15:50:50 info: manifest "helm-xxx/templates/recomposer-deploy.yaml" is empty. Skipping.
2017/12/21 15:50:50 info: manifest "helm-xxx/templates/scheduler-secret.yaml" is empty. Skipping.
2017/12/21 15:50:50 info: manifest "helm-xxx/templates/scheduler-deploy.yaml" is empty. Skipping.
2017/12/21 15:50:50 info: manifest "helm-xxx/templates/recomposer-secret.yaml" is empty. Skipping.
2017/12/21 15:50:50 info: manifest "helm-xxx/templates/recomposer-pvc.yaml" is empty. Skipping.
[tiller] 2017/12/21 15:50:58 creating updated release for xxx
[storage] 2017/12/21 15:50:58 creating release "xxx.v85"
[tiller] 2017/12/21 15:50:59 performing update for xxx
[tiller] 2017/12/21 15:50:59 executing 0 pre-upgrade hooks for xxx
[tiller] 2017/12/21 15:50:59 hooks complete for pre-upgrade xxx
[kube] 2017/12/21 15:51:13 building resources from updated manifest
[kube] 2017/12/21 15:51:22 checking 7 resources for changes
[kube] 2017/12/21 15:51:22 Looks like there are no changes for Secret "xxx-helm-xxx-nginx-secret"
[kube] 2017/12/21 15:51:23 Looks like there are no changes for Secret "xxx-application-secret"
[kube] 2017/12/21 15:51:23 Looks like there are no changes for Secret "azure-secret"
[kube] 2017/12/21 15:51:23 Looks like there are no changes for ConfigMap "xxx-helm-xxx-nginx-config"
[kube] 2017/12/21 15:51:23 Looks like there are no changes for ConfigMap "xxx-application-config"
[kube] 2017/12/21 15:51:24 Looks like there are no changes for Service "xxx-application-svc"
[kube] 2017/12/21 15:51:24 Deleting "xxx-recomposer-secret" in xxx...
[kube] 2017/12/21 15:51:24 Failed to delete "xxx-recomposer-secret", err: secrets "xxx-recomposer-secret" not found
[kube] 2017/12/21 15:51:24 Deleting "xxx-recomposer-config" in xxx...
[kube] 2017/12/21 15:51:24 Failed to delete "xxx-recomposer-config", err: configmaps "xxx-recomposer-config" not found
[kube] 2017/12/21 15:51:24 Deleting "xxx-recomposer-pv" in ...
[kube] 2017/12/21 15:51:24 Failed to delete "xxx-recomposer-pv", err: persistentvolumes "xxx-recomposer-pv" not found
[kube] 2017/12/21 15:51:24 Deleting "xxx-recomposer-pvc" in xxx...
[kube] 2017/12/21 15:51:24 Failed to delete "xxx-recomposer-pvc", err: persistentvolumeclaims "xxx-recomposer-pvc" not found
[kube] 2017/12/21 15:51:24 Deleting "xxx-recomposer" in xxx...
[kube] 2017/12/21 15:51:24 Using reaper for deleting "xxx-recomposer"
[kube] 2017/12/21 15:51:24 Failed to delete "xxx-recomposer", err: deployments.extensions "xxx-recomposer" not found
[tiller] 2017/12/21 15:51:24 executing 0 post-upgrade hooks for xxx
[tiller] 2017/12/21 15:51:24 hooks complete for post-upgrade xxx
[storage] 2017/12/21 15:51:24 updating release "xxx.v68"
[tiller] 2017/12/21 15:51:24 updating status for updated release for xxx
[storage] 2017/12/21 15:51:24 updating release "xxx.v85"
[storage] 2017/12/21 15:51:25 getting last revision of "xxx"
[storage] 2017/12/21 15:51:25 getting release history for "xxx"
[kube] 2017/12/21 15:51:38 Doing get for Secret: "xxx-helm-xxx-nginx-secret"
[kube] 2017/12/21 15:51:39 get relation pod of object: xxx/Secret/xxx-helm-xxx-nginx-secret
[kube] 2017/12/21 15:51:39 Doing get for Secret: "xxx-application-secret"
[kube] 2017/12/21 15:51:39 get relation pod of object: xxx/Secret/xxx-application-secret
[kube] 2017/12/21 15:51:39 Doing get for Secret: "azure-secret"
[kube] 2017/12/21 15:51:39 get relation pod of object: xxx/Secret/azure-secret
[kube] 2017/12/21 15:51:39 Doing get for ConfigMap: "xxx-helm-xxx-nginx-config"
[kube] 2017/12/21 15:51:39 get relation pod of object: xxx/ConfigMap/xxx-helm-xxx-nginx-config
[kube] 2017/12/21 15:51:39 Doing get for ConfigMap: "xxx-application-config"
[kube] 2017/12/21 15:51:39 get relation pod of object: xxx/ConfigMap/xxx-application-config
[kube] 2017/12/21 15:51:39 Doing get for Service: "xxx-application-svc"
[kube] 2017/12/21 15:51:39 get relation pod of object: xxx/Service/xxx-application-svc
[kube] 2017/12/21 15:51:39 Doing get for StatefulSet: "xxx-application"
[kube] 2017/12/21 15:51:39 get relation pod of object: xxx/StatefulSet/xxx-application

**Comment by jpoizat** [comment] 2017-12-21 16:20
might be related to #2941

**Comment by jpoizat** [comment] 2017-12-21 16:28
a said in the other thread, one of the way to fix the issue was to delete the buggy configmaps ... seems to do it for me currently...

**Comment by zuzzas** [comment] 2017-12-21 21:54
That is all fine and dandy. Until that time, when you have to delete something critical from a production namespace. Which, coincidentally, happened to me just now. :c

**Comment by jubel-han** [comment] 2017-12-25 04:04
I've faced the issue as well when we upgrade an release if there are multiple `DEPLOYED` status of this release, Have to fix it with delete those corresponding configmaps.

**Comment by amritb** [comment] 2018-01-16 19:55
Same problem. Everything was just fine yesterday and I did multiple upgrades. Today I just added a new yaml with `service` and `deployment` block separated with `---` and the upgrade failed.

**The interesting thing is**, helm created the `service` and then complained about it (and didn't do the deployment).
I commented out the `service` and just ran upgrade with the `deployment` block - it worked. However, helm didn't delete the service - which it should have as it's removed from the yaml file.

**Comment by awwithro** [comment] 2018-01-18 19:05
I was having this exact error. It looks like the issue is related to templates with multiple API objects similar to what @amritb saw. In my case, I had a template that had multiple API objects that could be toggled on and off similar to:
`{{ if .Values.enabled }}
---
...
 `
Breaking that into its own template file and cleaning up the orphaned objects that helm created and forgot about resolved the issue for me. It sounds like there is a bug in how helm gets previous config if the number of objects per template changes between releases.

**Comment by shz** [comment] 2018-01-19 23:05
Adding another datapoint: I appear to be having the exact same issue as @awwithro.  We're using a jinja loop to create multiple cronjobs via a template, and when a new upgrade caused this loop to fill in an additional cronjob, we ran into the bug.  Seemed to trigger #2941 as well (or possibly one bug causes the other), and deleting the zombie configmaps fixes it.

**Comment by nick4fake** [comment] 2018-01-23 20:48
Just trapped into this even without using any configmaps

**Comment by lsthornt** [comment] 2018-01-27 01:50
Some extra color for anyone who may be stuck:
I was running into this when introducing new subcharts and objects to my release. I was able to solve by checking every object type that was being added, and deleting any existing objects that would cause a naming collision.

This seems to be in line with others' evidence that deletion is the only way to solve right now 😕

**Comment by quicksnap** [comment] 2018-01-30 22:05
Also running across this =\

**Comment by quicksnap** [comment] 2018-01-30 22:07
I also needed to delete affected resources. Not good for a production environment =_(

**Comment by jan-g** [comment] 2018-01-31 13:40
I'm seeing something I think is similar. The problem appears to be that a `helm upgrade` does *not* --reuse-values from the previous deploy. If I specify the same set of values on the command-line as the initial installation did, then `helm upgrade` works. Dunno if this helps (or anyone else can confirm this).

**Comment by ryanlovett** [comment] 2018-01-31 17:59
Like @amritb, after I manually deleted the object that helm initially failed on, it succeeded after the next upgrade. I did not experience #2941.

**Comment by Zhomart** [comment] 2018-02-01 02:07
The same problem using helm `2.8.0`.  Kubernetes versions `client=v1.8.6` and `server=v1.8.5-gke.0`.

```
$ helm upgrade bunny ./app --debug
[debug] Created tunnel using local port: '54274'

[debug] SERVER: "127.0.0.1:54274"

Error: UPGRADE FAILED: no ConfigMap with the name "bunny-proxy-config" found
```

But the configmap exists in `$ kubectl get configmap`. If I manually delete the configmap, it works, but next time it fails again.

Here is the configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "proxy.fullname" . }}-config
  # namespace: {{ .Release.Namespace }} # I've tried adding and removing it
  labels: # labels are the same as labels from $ kubectl describe configmap bunny-proxy-config
    app: {{ template "proxy.name" . }}
    chart: {{ template "proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  asd: qwe
```

**Comment by Zhomart** [comment] 2018-02-01 05:34
I deleted release and re-installed again. Also, I was using api version `extensions/v1beta` for deployment, I've changed to `apiVersion: apps/v1beta2`, I don't know if this helped or not.
Also currently I'm running `tiller` locally.

Right now seems like everything is working.

**Comment by nick4fake** [comment] 2018-02-04 17:14
This is really easy to reproduce, happens if there is an error in manifest.

Like we have resource1 and resource2, resource2 depends on first. When we upgrade release, resource1 is created (eg PV & PVC), but resource2 fails. After this only deletion of resource1 helps, as helm always reports a problem on upgrade (PersistentVolume with name ... not found)

**Comment by bviolier** [comment] 2018-02-05 13:57
We had the same issue (the resource that got us was Secrets). Removing the new secrets and re-deploying fixed it.

Do note that because of the failures, we now have 11 different releases when we do `helm list`, 10 FAILED ones and 1 DEPLOYED. That's not expected, right? Same issue as here it seems: https://github.com/kubernetes/helm/issues/2941

**Comment by bviolier** [comment] 2018-02-05 15:13
We had the same issues with resources (which were secrets). After removing all new secrets and re-deploying everything is working again.

Do note that we now have 11 releases when doing `helm list`. 10 of them are Failed and 1 is deployed, is that expected behavior? Seems like this issue: https://github.com/kubernetes/helm/issues/2941 Although, we don't have any `ConfigMaps`.

**Comment by yuvipanda** [comment] 2018-02-08 02:15
This has pretty much made helm unusable for regular production deploys for us :( We're currently investigating doing things like passing --dry-run to helm and piping it to kubectl apply... Since this seems to affect only a subset of users, am unsure what it is that we are doing wrong :(

**Comment by binoculars** [comment] 2018-02-14 18:44
After tailing the tiller logs, I found that tiller was trying to update an old release at the same time:

```
[storage] 2018/02/14 18:25:40 updating release "s2osf.v10"
[storage] 2018/02/14 18:25:40 updating release "s2osf.v44"
```

Deleting the old configmap for s2osf.v10 and then upgrading worked.

```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Comment by balboah** [comment] 2018-02-15 10:27
Having the same issue as  @binoculars:
```
[storage] 2018/02/15 10:20:50 updating release "control.v136"
[storage] 2018/02/15 10:20:50 updating release "control.v226"
```

Causing weird problems with `UPGRADE FAILED: no Secret with the name "foobar" found`.
I even tried deleting this secret which then caused errors on some configmap instead, and at 3rd run it once again complained on the previous secret.

This might have been triggered after upgrading from helm 2.7.x to 2.8.1.

**Comment by balboah** [comment] 2018-02-20 09:31
if your last resort is about deleting the old release, there might be a less destructive work around as my comment https://github.com/kubernetes/helm/issues/3513#issuecomment-366918019

basically finding that old revision in the logs and editing the configmap manually where tiller stores the deployed status. There should not be two revisions with DEPLOYED status afaik.

**Comment by zuzzas** [comment] 2018-02-22 06:45
Found a new solution to this problem.

`kubectl -n kube-system edit cm name_of_your_release.v2`, where v2 is the latest revision number marked as FAILED in `helm list`. You might also want to edit one of the DEPLOYED releases and change status to SUPERSEDED, so that we wont have two deployed releases at the same time.

**Comment by balboah** [comment] 2018-02-22 13:35
@zuzzas this is what I referred to. Worked for me as well

**Comment by zuzzas** [comment] 2018-02-22 14:04
@balboah the problem is that we've got only one deployment in DEPLOYED state, but if it's not of the latest ones, it'll still crash. The problem seems unrelated to have two or more deployments in DEPLOYED state in most of our cases.

**Comment by balboah** [comment] 2018-02-22 14:22
@zuzzas do you have many releases in the same namespace or only one?

**Comment by bacongobbler** [comment] 2018-02-27 18:26
We believe this has been fixes via #3539. Please re-open if I happen to be wrong. :)

**Comment by quicksnap** [comment] 2018-02-27 18:27
Thank you everyone for your work on this!

**Comment by bacongobbler** [comment] 2018-02-27 18:28
Note that this has not been fixed for existing charts in this state; you'll still need to remove the old releases that are in state DEPLOYED for things to work again. @balboah just prevented the case where you can get into the "multiple releases as DEPLOYED" state. :)

**Comment by Pneumaticat** [comment] 2018-05-11 23:31
Hm, I still get this issue on Helm 2.8.2 (not the latest, but I tried with 2.9.0 and it gives the same error.) Usually deleting the offending resource manually can fix it, though often it cascades into multiple resources that all need deletion before it successfully upgrades.

I have a bit of a large helm chart with nested dependencies; might that be it?

**Comment by ramyala** [comment] 2018-05-15 00:09
I'm seeing the same issue with clusterrolebinding. I added the new resource to my chart and `upgrade` as well as `upgrade --install` would fail with `Error: UPGRADE FAILED: no ClusterRoleBinding with the name "test-clusterrolebinding" found`

**Comment by numbsafari** [comment] 2018-05-15 17:53
I'm experiencing the same issue as @ramyala with ClusterRole. The ClusterRole exists, but creating the RoleBinding fails with that error.

**Comment by tomislater** [comment] 2018-05-17 14:33
On Helm `2.9.1` I have encountered the same issue:

```
helm upgrade --install --namespace my-namespace my-stack stack
Error: UPGRADE FAILED: no ConfigMap with the name "my-stack-my-app" found
```

While I see this ConfigMap on my cluster.

**Comment by nerumo** [comment] 2018-05-18 18:27
I experience this issue if I have a multiple resources with hooks in one file

**Comment by DrEsteban** [comment] 2018-05-27 20:04
+1, this is happening again with 2.9.1.  Please reopen.

**Comment by bacongobbler** [comment] 2018-06-08 06:32
Re-labeling this as a bug. We're not sure what caused this regression to occur but if anyone can provide steps on how to reproduce this bug on 2.9.1 that would be most appreciated.

**Comment by abobwhite** [comment] 2018-06-10 18:31
@bacongobbler 

I am seeing this too when trying to deploy a new Ingress in my helm chart. I am admittedly new to Ingress but it seems like it's correct based on all the examples and I've been doing other helm/k8s stuff for a couple months.

I already deployed the helm chart `stable/nginx-ingress` so the controller is present. The error seems to suggest it's trying to find the one I'm trying to create. Here is the command I'm running:

`helm upgrade some-existing-release-name -i --set imageTag=$TAG-$BUILD_NUMBER --namespace=default ./deploy/helm` where `deploy/helm` contains my chart manifests.

```Error: UPGRADE FAILED: no Ingress with the name "my-ingress" found```

yaml:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  labels:
    app: my-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ $.Values.appDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: web-app
          servicePort: 80
      - path: /api
        backend:
          serviceName: api
          servicePort: 8080
```

**Comment by pslavova** [comment] 2018-06-11 13:53
Hi,
Here are the steps that introduced the issue in my env:
1. I had a helm chart deployed and upgraded several times.
2. Created new CronJob object in the chart and upgraded again - the cron job was created successfully.
3. All next upgrades are failing with the reported error "Error: UPGRADE FAILED: no CronJob with the name “cronjob-name” found"

**Comment by ramyala** [comment] 2018-06-11 23:36
I'm also seeing the issue when i add a Secret which didnt' exist earlier. I tried adding a "db-credentials"
secret which led to:
```
Error: UPGRADE FAILED: no Secret with the name "db-credentials" found
```

**Comment by bacongobbler** [comment] 2018-06-11 23:39
potentially relevant fix: #4146 

if anyone running into this error could test that PR and see if it fixes this, then we'd be able to confirm that it's likely a regression in the k8s API and move forward with that fix. Thanks!

**Comment by jdotjdot** [comment] 2018-06-11 23:43
I can't 100% confirm if this will always reproduce, but I've noticed this tends to happen in the following situation:

1. I upgrade a Helm chart, including a new resource
2. That upgrade fails, but the resource was created as part of the failed upgrade
3. All subsequent upgrades fail

If I do a `helm rollback` to the last succeeded deploy and then try re-upgrading, it does seem to work.

**Comment by ljakimczuk** [comment] 2018-06-13 09:15
It seems very easy to reproduce it manually, without intentionally trying to upgrade a chart with harmful changes (for example, modifying an immutable Job objects):

1. Take some chart and deploy it (but omit one resource, let's say a Service)
2. Add omitted resource manually (for example, with "kubectl create"), but with the name corresponding to the release
3. Add the omitted resource back to the chart and then try to upgrade it, helm should report "UPGRADE FAILED: no <kind> with the name <name> found"

The steps are different but still the root cause seems the same. Correct me if I'm wrong, but it seems to me that the last DEPLOYED release's revision does not have information about the particular resource, either because it was added "outside" Helm (manually for example) or the latest upgrade failed on some step (let's say on upgrading an immutable Job), at the same time deploying other objects and then recording them in the FAILED revision (but still without any track in the DEPLOYED revision what is expected, otherwise it would mean changing the history). On the next run the Tiller's kube client sees the resources on the cluster, meaning they should be already deployed and thus recorded, but they are not listed in the DEPLOYED revision (it seems the FAILED revision is not contacted).

**Comment by ramyala** [comment] 2018-06-13 22:29
@bacongobbler I tried the fix from #4146 but that didn't help. This has been a fairly consistent issue with helm upgrades and been a blocker for some time. Were you able to repro this issue?

**Comment by ramyala** [comment] 2018-06-13 22:50
@bacongobbler I tested #4146 with a custom tiller image and it did fix this issue! For others who are looking for a solution, you can apply the patch in the issue on current master and compile:

`make bootstrap build docker-build`

You will have to upload the tiller image to your repo and reinstall tiller to your cluster. I was able to get away with a force reset and re-install without destroying the current releases.

`$GO_HOME/src/k8s.io/helm/bin/helm init -i gcr.io/my-repo/tiller:1 --service-account tiller`

**Comment by bacongobbler** [comment] 2018-06-13 23:19
thank you @ramyala for testing the fix!

**Comment by bacongobbler** [comment] 2018-06-14 19:39
So I found a few bugs with #4146 that makes it an undesirable PR to move forward with. I reported my findings between master, #4146, and #4223 here: https://github.com/kubernetes/helm/pull/4223#issuecomment-397413568

I've managed to identify the underlying bug that causes this particular error, and go through the different scenarios and edge cases with each of the proposed PRs. If anyone else could confirm my findings or find other edge cases, that would be much appreciated!

**Comment by bacongobbler** [comment] 2018-06-14 19:54
Oh, and something I failed to mention: because the cluster's in an inconsistent state, this can easily be worked around by manually intervening and deleting the resource that the error reports as "not found". Following the example I demonstrated in https://github.com/kubernetes/helm/pull/4223#issuecomment-397413568:

```
><> helm fetch --untar https://github.com/kubernetes/helm/files/2103643/foo-0.1.0.tar.gz
><> helm install ./foo/
...
><> vim foo/templates/service.yaml
><> kubectl create -f foo/templates/service.yaml
service "foo-bar" created
><> helm upgrade $(helm last) ./foo/
Error: UPGRADE FAILED: no Service with the name "foo-bar" found
><> kubectl delete svc foo-bar
service "foo-bar" deleted
><> helm upgrade $(helm last) ./foo/
Release "riotous-echidna" has been upgraded. Happy Helming!
...
><> kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
foo-bar      ClusterIP   10.104.143.52   <none>        80/TCP    3s
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP   1h
```

**Comment by bacongobbler** [comment] 2018-06-14 19:56
In the interest of keeping things all together, I'm going to close this as a duplicate of #1193 since the two tickets are identical. Please report any findings there so we can all work off a single ticket. Thanks!

**Closed by bacongobbler** 2018-06-14 19:56 UTC
Labels: kind/bug

**Comment by joeauty** [comment] 2018-10-23 21:14
Warning: this information is kind of sketchy and I can't make sense of it, but just in case this is useful to somebody, I worked around this problem by changing my service selector from:

```
selector:
    app: {{ template "mything.name" . }}
```

to

```
selector:
    app: mything
```

Perhaps there is some sort of issue with using a variable in this context?

**Comment by yuri1992** [comment] 2018-11-22 11:17
Try `helm delete RELEASE_NAME --purge`
and install it again.

**Comment by pq-dong** [comment] 2019-02-20 09:54
> Same problem. Everything was just fine yesterday and I did multiple upgrades. Today I just added a new yaml with `service` and `deployment` block separated with `---` and the upgrade failed.
> 
> **The interesting thing is**, helm created the `service` and then complained about it (and didn't do the deployment).
> I commented out the `service` and just ran upgrade with the `deployment` block - it worked. However, helm didn't delete the service - which it should have as it's removed from the yaml file.
> 
> **Update**: I manually deleted the `service`, uncommented it from the yaml and ran the upgrade - this time it worked like a charm!

hi，i also has this problem, and i can not solve it , can you would like give me some prompts.

**Comment by bacongobbler** [comment] 2019-02-20 18:08
see https://github.com/helm/helm/issues/1193#issuecomment-419555433.

**Comment by thedumbtechguy** [comment] 2019-03-11 11:49
Just confirming I am witnessing the same issue and the cause also is as earlier indicated.

Added a new secret, referenced it in a volume (invalid syntax). Upgrade failed, subsequent upgrades failed with the error as above.

Listing secrets showed it had been created. Manually deleted secret and the upgrade went through successfully.

**Comment by tdavis** [comment] 2019-03-15 22:48
Same, @thedumbtechguy. I run into this issue routinely. It's especially fun when Helm decides you need to delete _all_ your secrets, configmaps, roles, etc. Upgrading becomes a game of wack-a-mole with an ever-increasing list of arguments to `kubectl delete`. I should have thrown in the towel on this sisyphean task months ago, but it's too late for that now. Sure hope this and the dozens of similar issues can be fixed!

**Comment by thedumbtechguy** [comment] 2019-03-16 00:11
I've been using helm for one week and already faced everything outlined
here https://medium.com/@7mind_dev/the-problems-with-helm-72a48c50cb45

A lot needs fixing here.

**Comment by geosword** [comment] 2019-03-22 21:13
I experienced the same with Helm v2.10. I already had a chart deployed, added another configMap to the chart. It reported that the deployment failed because it couldn't find configMap "blah". I did
```
helm upgrade <NAME> chart --debug --dryrun 
```
To verify the configMap was indeed being rendered, it was. Checked the configMaps in the cluster, and found it there. Deleted the blah configMap, re-ran the upgrade, it worked.

**Comment by bacongobbler** [comment] 2019-03-22 21:22
https://github.com/helm/helm/pull/5460 should better clarify the error message going forward.

**Comment by geosword** [comment] 2019-03-22 21:25
Fair point.

```
$ helm upgrade linting-unicorn testrail                                                                                                                                                                                        
Error: UPGRADE FAILED: no ConfigMap with the name "linting-unicorn-testrail-php-config" found
```

Keep up the good work helm team.

**Comment by fbcbarbosa** [comment] 2019-03-22 22:18
In case this is a big deal to anyone else, thought I'd point out https://github.com/helm/helm/pull/4871 should fix these issues.

Note that it appears it still hasn't been approved by the Helm team. Plus there were some concerns about the automatic deletion resources. Just mentioning it in case anyone wants to build it from source and give it a try.

**Comment by dNetGuru** [comment] 2019-03-26 23:43
Having the same issue and only workaround seems to be `helm delete --purge release` and install again!

**Comment by kvangrae** [comment] 2019-04-20 00:03
I ran into the same issue. @fbcbarbosa it looks like it was [merged](https://github.com/helm/helm/pull/4871#pullrequestreview-223369034) 2 weeks ago. It should hopefully be a part of the next release [2.14.0](https://github.com/helm/helm/milestone/61).

**Comment by majewsky** [comment] 2019-04-24 13:05
> Having the same issue and only workaround seems to be `helm delete --purge release` and install again!

A less destructive option is doing a `helm rollback` to the /current/ version (i.e. by 0 steps). I cannot guarantee success, but for us so far, it has always unwedged things successfully.

**Comment by CDingerdis** [comment] 2019-06-05 14:06
Is there an idea if this is going to be in the next release, and if it does when it is coming?

**Comment by bacongobbler** [comment] 2019-06-05 15:46
#5460 was merged 2 months ago, which means it should be in helm 2.14.0.

**Comment by IamGabrielWu** [comment] 2019-06-26 08:11
I fixed the issue by
1. delete those resources that complained by "helm upgrade". (It says Not found but actually it can be found). Don't delete the whole release, otherwise if in production you will be screwed completely.  
2. redo helm upgrade. Now this time it should be "Happy Helming" shows up. :)

**Comment by Benbentwo** [comment] 2019-10-11 16:50
We ran into this issue in PROD, when a requirement to our umbrella helm chart added a configmap based on a conditional. For us the work around fix was to 
```
helm rollback <some revision that's acceptable>
helm upgrade <desired version>
```

**Comment by tobypeschel** [comment] 2020-03-04 12:32
For us, a rollback to the **current revision** has always worked:
```
helm ls
helm rollback <NAME> <current REVISION>
```

**Comment by tobypeschel** [comment] 2020-03-04 12:33
For us, a simple rollback to the **current revision** has always worked:
```
helm ls
helm rollback <NAME> <current REVISION>
```

**Comment by ypadlyak** [comment] 2020-08-26 19:59
@tobypeschel do you have idea how your fix works?
