### ISSUE TITLE
`helm lint` doesn't support `--set-string`

### ISSUE THREAD

**Issue by OndraZizka** [kubernetes/helm#4098] opened 2018-05-21 14:46 UTC
Following htting issue #1707 , I have switched everything to `--set-string`.

    + helm lint ./csa-application/src/main/helm/charts/collab-services-api --set-string image.tag=57e15901
    + helm install --replace --name h4452 --wait --timeout 600 ./... --set image.tag=44526276

What a surprise when I get this:

    Error: unknown flag: --set-string

This should be consistent; how else can `helm lint` really verify / validate the templates if it can't really reproduce the same output?

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

**Comment by bacongobbler** [comment] 2018-05-29 17:33
Same here:

```
><> helm version -c
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
><> helm help lint | grep set-string
      --set-string stringArray   set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
><> helm create foo
Creating foo
><> helm lint foo --set-string replicaCount=300
==> Linting foo
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
><> helm template foo --set-string replicaCount=300 | grep replicas
  replicas: 300
```

I'm going to close this since it appears to be there as intended on `helm install`, `helm lint` and `helm template` but let us know if there's somewhere else the flag should exist. Thanks!

**Closed by bacongobbler** 2018-05-29 17:33 UTC
