### ISSUE TITLE
helm install hangs with 'Error: no available release name found' 

### ISSUE THREAD

**Issue by CalvinHartwell** [kubernetes/helm#3839] opened 2018-04-05 23:33 UTC
Hi all, 

I am trying to use Helm with my Kubernetes cluster but when I attempt to install packages it just hangs and gives me the error 'no available release name found'. Any ideas would be appreciated. I assume this is most likely an RBAC issue or connectivity problem, I am running helm and kubectl out-side of my cluster, so it could be a blocked port. 

Output of `helm version`:

```
calvinh@calvinh-MacBookPro:~$ helm version
Client: &version.Version{SemVer:"v2.9.0-rc2", GitCommit:"08db2d0181f4ce394513c32ba1aee7ffc6bc3326", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0-rc2", GitCommit:"08db2d0181f4ce394513c32ba1aee7ffc6bc3326", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
calvinh@calvinh-MacBookPro:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Canonical Kubernetes v1.9.3

Output from logs within tiller container: 

```
[main] 2018/04/05 23:12:42 Storage driver is ConfigMap
[main] 2018/04/05 23:12:42 Max history per release is 0
[tiller] 2018/04/05 23:23:11 preparing install for 
[storage] 2018/04/05 23:23:11 getting release "loping-echidna.v1"
[storage/driver] 2018/04/05 23:23:41 get: failed to get "loping-echidna.v1": Get http://localhost:8080/api/v1/namespaces/default/configmaps/loping-echidna.v1: dial tcp: i/o timeout
[tiller] 2018/04/05 23:23:41 info: generated name loping-echidna is taken. Searching again.
[storage] 2018/04/05 23:23:41 getting release "nonplussed-antelope.v1"
[storage/driver] 2018/04/05 23:24:11 get: failed to get "nonplussed-antelope.v1": Get http://localhost:8080/api/v1/namespaces/default/configmaps/nonplussed-antelope.v1: dial tcp: i/o timeout
[tiller] 2018/04/05 23:24:11 info: generated name nonplussed-antelope is taken. Searching again.
[storage] 2018/04/05 23:24:11 getting release "opinionated-sloth.v1"
[storage/driver] 2018/04/05 23:24:41 get: failed to get "opinionated-sloth.v1": Get http://localhost:8080/api/v1/namespaces/default/configmaps/opinionated-sloth.v1: dial tcp: i/o timeout
[tiller] 2018/04/05 23:24:41 info: generated name opinionated-sloth is taken. Searching again.
[storage] 2018/04/05 23:24:41 getting release "harping-wolverine.v1"
[storage/driver] 2018/04/05 23:25:11 get: failed to get "harping-wolverine.v1": Get http://localhost:8080/api/v1/namespaces/default/configmaps/harping-wolverine.v1: dial tcp: i/o timeout
[tiller] 2018/04/05 23:25:11 info: generated name harping-wolverine is taken. Searching again.
[storage] 2018/04/05 23:25:11 getting release "ornery-meerkat.v1"
[storage/driver] 2018/04/05 23:25:41 get: failed to get "ornery-meerkat.v1": Get http://localhost:8080/api/v1/namespaces/default/configmaps/ornery-meerkat.v1: dial tcp: i/o timeout
[tiller] 2018/04/05 23:25:41 info: generated name ornery-meerkat is taken. Searching again.
[tiller] 2018/04/05 23:25:41 warning: No available reease names found after 5 tries
[tiller] 2018/04/05 23:25:41 failed install prepare step: no available release name found
```

**Comment by bacongobbler** [comment] 2018-04-05 23:54
Hey! Yes this is most likely an RBAC issue. Have you taken a look at the documentation to set up Tiller with RBAC? https://docs.helm.sh/using_helm/#role-based-access-control goes into detail about this. :)

**Comment by bacongobbler** [comment] 2018-04-11 21:11
Closing as a duplicate of #3055.

**Closed by bacongobbler** 2018-04-11 21:11 UTC
Labels: question/support

**Comment by CalvinHartwell** [comment] 2018-04-11 21:14
@bacongobbler FYI I managed to resolve it by installing a previous version, which lead me to believe this is an actual bug with 2.9.0r2 and k8s 1.9.3. We're now shipping k8s 1.10 at Canonical so I'll try that and report back, but something weird was going on between the versions.
