### ISSUE TITLE
Error: grpc: received message larger than max (5841327 vs. 4194304)

### ISSUE THREAD

**Issue by nmiculinic** [kubernetes/helm#3586] opened 2018-03-01 13:26 UTC
When fetching histroy for one release

**Comment by bacongobbler** [comment] 2018-03-02 23:30
closing as a duplicate of #3322.

**Closed by bacongobbler** 2018-03-02 23:30 UTC

**Comment by bacongobbler** [comment] 2018-03-02 23:49
Rather, https://github.com/kubernetes/helm/pull/3514 was merged so this bug should no longer be present in the canary releases. #3322 is more about what happens when the number of releases stored in tiller exceed that 20MB limit.
