### ISSUE TITLE
'Release not found' on status, delete etc after 'successfull' install 

### ISSUE THREAD

**Issue by luck02** [kubernetes/helm#2582] opened 2017-06-15 20:59 UTC
Installed mysql stable/mysql

I can list, but I can not get / delete / status

```
garylucas@gary-lucas:~/dev/ub-data-hub/local-dev|DAT-581
⇒  helm install --name msyql-latest stable/mysql
NAME:   msyql-latest
LAST DEPLOYED: Thu Jun 15 13:33:36 2017
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME                TYPE    DATA  AGE
msyql-latest-mysql  Opaque  2     0s

==> v1/PersistentVolumeClaim
NAME                STATUS   VOLUME    CAPACITY  ACCESSMODES  STORAGECLASS  AGE
msyql-latest-mysql  Pending  standard  0s

==> v1/Service
NAME                CLUSTER-IP  EXTERNAL-IP  PORT(S)   AGE
msyql-latest-mysql  10.0.0.235  <none>       3306/TCP  0s

==> v1beta1/Deployment
NAME                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
msyql-latest-mysql  1        1        1           0          0s


NOTES:
MySQL can be accessed via port 3306 on the following DNS name from within your cluster:
msyql-latest-mysql.default.svc.cluster.local

To get your root password run:

    kubectl get secret --namespace default msyql-latest-mysql -o jsonpath="{.data.mysql-root-password}" | base64 --decode; echo

To connect to your database:

1. Run an Ubuntu pod that you can use as a client:

    kubectl run -i --tty ubuntu --image=ubuntu:16.04 --restart=Never -- bash -il

2. Install the mysql client:

    $ apt-get update && apt-get install mysql-client -y

3. Connect using the mysql cli, then provide your password:
    $ mysql -h msyql-latest-mysql -p
```

Examples:
```
garylucas@gary-lucas:~/dev/ub-data-hub/local-dev|DAT-581⚡
⇒  helm list
NAME        	REVISION	UPDATED                 	STATUS  	CHART      	NAMESPACE
msyql-latest	1       	Thu Jun 15 13:33:36 2017	DEPLOYED	mysql-0.2.6	default
```

```
garylucas@gary-lucas:~/dev/ub-data-hub/local-dev|DAT-581⚡
⇒  helm delete mysql-latest
Error: Unable to lock release mysql-latest: release not found
```

Same response for other commands (get, status etc)

Versions:
```
garylucas@gary-lucas:~/dev/ub-data-hub/local-dev/db|DAT-581⚡
⇒  helm version
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}

⇒  kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T22:30:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-30T22:03:41Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
garylucas@gary-lucas:~/dev/ub-data-hub/local-dev/db|DAT-581⚡

garylucas@gary-lucas:~/dev/ub-data-hub/local-dev/db|DAT-581⚡
⇒  minikube version
minikube version: v0.19.1
```

Thanks!

**Comment by luck02** [comment] 2017-06-15 23:13
it's not 'fixed' but I did `helm reset --force`, nuke the pod and nuke the config map so it's gone...

**Comment by sushilkm** [comment] 2017-06-27 18:53
assign this one to me, I am working on this one, was able to repro, it seems there is something in the particular name, as this works with other names, only `mysql-latest` has issue

**Comment by sushilkm** [comment] 2017-06-27 21:24
hehehe, the fix is a funny one:

the issue is nothing but the typo in name when install command was issued

```
helm install --name **msyql-latest** stable/mysql
```
but we were trying to query/delete the instance which really never existed 👍 

```
helm delete **mysql-latest**
```

**Comment by luck02** [comment] 2017-06-27 21:30
I'm not sure what you're trying to say.  I'll try to reproduce this issue again in my local env and see what happens.  Was I issuing a bad command of some sort?

**Comment by jascott1** [comment] 2017-06-27 21:34
@luck02 you typo'd mysql in the command
`helm install --name msyql-latest stable/mysql`

**Comment by luck02** [comment] 2017-06-27 21:51
OMG :(  sorry  I literally couldn't see that :(

**Closed** 2017-06-27 21:52 UTC
Labels: bug
